'use client'

import { FormEvent,useCallback,useEffect,useState } from 'react'

type Session={accessToken:string;role:string;societyName?:string}
type Account={id:string;code:string;bankName:string;accountName:string;maskedAccountNumber:string;ifsc?:string|null;ledgerAccountId:string;openingBalancePaise:string;active:boolean;ledgerCode:string;ledgerName:string}
type Ledger={id:string;code:string;name:string;type:string;active:boolean}
type Tx={id:string;bankAccountId:string;bankCode:string;externalKey:string;transactionDate:string;direction:'CREDIT'|'DEBIT';amountPaise:string;reference?:string|null;description?:string|null;status:string;journalEntryId?:string|null;entryNumber?:string|null}
type Summary={transactionCount:number;unmatchedCount:number;matchedCount:number;statementMovementPaise:string;reconciledMovementPaise:string}
const base=(process.env.NEXT_PUBLIC_AARAGATE_API_BASE_URL??'http://localhost:3000').replace(/\/$/,'')
const readRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','COMMITTEE_MEMBER','ACCOUNTANT']),manageRoles=new Set(['SUPER_ADMIN','ACCOUNTANT'])
function session():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw) as Session:null}catch{return null}}
async function api<T>(s:Session,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${base}/api/v1${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.accessToken}`,...init.headers}});const text=await r.text();const body=text?JSON.parse(text):null;if(!r.ok)throw new Error(Array.isArray(body?.message)?body.message.join(', '):body?.message??`Request failed (${r.status})`);return body as T}
const money=(v:string|number|undefined)=>`₹${(Number(v??0)/100).toLocaleString('en-IN',{maximumFractionDigits:2})}`,today=()=>new Date().toISOString().slice(0,10)

export default function BankReconciliationPage(){
  const[s,setS]=useState<Session|null>(null),[accounts,setAccounts]=useState<Account[]>([]),[ledgers,setLedgers]=useState<Ledger[]>([]),[txs,setTxs]=useState<Tx[]>([]),[summary,setSummary]=useState<Summary|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const[code,setCode]=useState(''),[bankName,setBankName]=useState(''),[accountName,setAccountName]=useState(''),[masked,setMasked]=useState(''),[ifsc,setIfsc]=useState(''),[ledger,setLedger]=useState('')
  const[bankAccountId,setBankAccountId]=useState(''),[externalKey,setExternalKey]=useState(''),[transactionDate,setTransactionDate]=useState(today()),[direction,setDirection]=useState<'CREDIT'|'DEBIT'>('CREDIT'),[amount,setAmount]=useState(''),[reference,setReference]=useState('')
  const canRead=!!s&&readRoles.has(s.role),canManage=!!s&&manageRoles.has(s.role)
  const load=useCallback(async(x:Session)=>{setLoading(true);setError('');try{const[a,l,t,sum]=await Promise.all([api<Account[]>(x,'/accounting/bank-reconciliation/accounts'),api<Ledger[]>(x,'/accounting/accounts'),api<Tx[]>(x,'/accounting/bank-reconciliation/transactions'),api<Summary[]>(x,'/accounting/bank-reconciliation/summary')]);setAccounts(a);setLedgers(l.filter(v=>v.type==='ASSET'&&v.active));setTxs(t);setSummary(Array.isArray(sum)?sum[0]??null:sum as unknown as Summary)}catch(e){setError(e instanceof Error?e.message:'Could not load bank reconciliation')}finally{setLoading(false)}},[])
  useEffect(()=>{const x=session();setS(x);if(x&&readRoles.has(x.role))void load(x);else setLoading(false)},[load])
  async function createAccount(e:FormEvent){e.preventDefault();if(!s||!canManage)return;setBusy(true);setError('');try{await api(s,'/accounting/bank-reconciliation/accounts',{method:'POST',body:JSON.stringify({code,bankName,accountName,maskedAccountNumber:masked,ifsc:ifsc||undefined,ledgerAccountId:ledger})});setCode('');setBankName('');setAccountName('');setMasked('');setIfsc('');setLedger('');await load(s)}catch(err){setError(err instanceof Error?err.message:'Could not create bank account')}finally{setBusy(false)}}
  async function importTx(e:FormEvent){e.preventDefault();if(!s||!canManage)return;const rupees=Number(amount);if(!bankAccountId||!Number.isFinite(rupees)||rupees<=0)return setError('Select a bank account and enter a positive amount.');setBusy(true);setError('');try{await api(s,'/accounting/bank-reconciliation/transactions/import',{method:'POST',body:JSON.stringify({bankAccountId,externalKey,transactionDate,direction,amountPaise:Math.round(rupees*100),reference:reference||undefined})});setExternalKey('');setAmount('');setReference('');await load(s)}catch(err){setError(err instanceof Error?err.message:'Could not import transaction')}finally{setBusy(false)}}
  async function action(path:string,body?:unknown){if(!s||!canManage)return;setBusy(true);setError('');try{await api(s,path,{method:'POST',body:body===undefined?undefined:JSON.stringify(body)});await load(s)}catch(err){setError(err instanceof Error?err.message:'Reconciliation action failed')}finally{setBusy(false)}}
  async function match(t:Tx){const journalEntryId=prompt('Posted journal UUID to match');if(journalEntryId)await action(`/accounting/bank-reconciliation/transactions/${t.id}/match`,{journalEntryId})}
  if(loading)return <main style={{padding:32}}>Loading bank reconciliation…</main>
  if(!canRead)return <main style={{padding:32}}><h1>Finance access required</h1></main>
  return <main style={{maxWidth:1240,margin:'0 auto',padding:'28px 22px 80px'}}><header style={header}><div><small>{s?.societyName??'Current society'}</small><h1 style={{margin:'4px 0'}}>Bank reconciliation</h1><p style={{margin:0}}>Match imported bank evidence to posted accounting journals without rewriting history.</p></div><button style={secondary} onClick={()=>s&&void load(s)}>Refresh</button></header>{error&&<div style={errorBox}>{error}</div>}{summary&&<section style={metrics}><Metric label="Transactions" value={String(summary.transactionCount)}/><Metric label="Unmatched" value={String(summary.unmatchedCount)}/><Metric label="Matched" value={String(summary.matchedCount)}/><Metric label="Statement movement" value={money(summary.statementMovementPaise)}/><Metric label="Reconciled movement" value={money(summary.reconciledMovementPaise)}/></section>}
  {canManage&&<section style={panel}><h2>Register bank account</h2><form onSubmit={createAccount} style={grid}><label>Code<input required value={code} onChange={e=>setCode(e.target.value)} style={input}/></label><label>Bank<input required value={bankName} onChange={e=>setBankName(e.target.value)} style={input}/></label><label>Account name<input required value={accountName} onChange={e=>setAccountName(e.target.value)} style={input}/></label><label>Masked number<input required placeholder="XXXX1234" value={masked} onChange={e=>setMasked(e.target.value)} style={input}/></label><label>IFSC<input value={ifsc} onChange={e=>setIfsc(e.target.value)} style={input}/></label><label>Bank ledger<select required value={ledger} onChange={e=>setLedger(e.target.value)} style={input}><option value="">Choose ASSET ledger</option>{ledgers.map(l=><option key={l.id} value={l.id}>{l.code} · {l.name}</option>)}</select></label><button disabled={busy} style={primary}>Add bank</button></form></section>}
  {canManage&&accounts.length>0&&<section style={panel}><h2>Import statement transaction</h2><form onSubmit={importTx} style={grid}><label>Bank<select required value={bankAccountId} onChange={e=>setBankAccountId(e.target.value)} style={input}><option value="">Choose bank</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.bankName} · {a.maskedAccountNumber}</option>)}</select></label><label>External key<input required value={externalKey} onChange={e=>setExternalKey(e.target.value)} style={input}/></label><label>Date<input type="date" value={transactionDate} onChange={e=>setTransactionDate(e.target.value)} style={input}/></label><label>Direction<select value={direction} onChange={e=>setDirection(e.target.value as 'CREDIT'|'DEBIT')} style={input}><option value="CREDIT">Credit / money in</option><option value="DEBIT">Debit / money out</option></select></label><label>Amount (₹)<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} style={input}/></label><label>Reference<input value={reference} onChange={e=>setReference(e.target.value)} style={input}/></label><button disabled={busy} style={primary}>Import</button></form></section>}
  <section style={panel}><h2>Bank accounts</h2>{accounts.length===0?<p>No bank accounts registered.</p>:accounts.map(a=><div key={a.id} style={row}><span><b>{a.code} · {a.bankName}</b><br/><small>{a.accountName} · {a.maskedAccountNumber} · ledger {a.ledgerCode}</small></span><span>{a.active?'Active':'Inactive'}</span></div>)}</section>
  <section style={panel}><h2>Statement transactions</h2><div style={{overflowX:'auto'}}><table style={table}><thead><tr><th>Date</th><th>Bank</th><th>Reference</th><th>Direction</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{txs.map(t=><tr key={t.id}><td>{new Date(t.transactionDate).toLocaleDateString('en-IN')}</td><td>{t.bankCode}</td><td>{t.reference??t.externalKey}</td><td>{t.direction}</td><td>{money(t.amountPaise)}</td><td>{t.status}</td><td>{t.status==='UNMATCHED'&&canManage?<><button style={secondary} onClick={()=>void match(t)}>Match</button> <button style={secondary} onClick={()=>void action(`/accounting/bank-reconciliation/transactions/${t.id}/ignore`)}>Ignore</button></>:t.status==='MATCHED'&&canManage?<button style={secondary} onClick={()=>void action(`/accounting/bank-reconciliation/transactions/${t.id}/unmatch`)}>Unmatch</button>:t.entryNumber??'—'}</td></tr>)}</tbody></table></div></section></main>
}
function Metric({label,value}:{label:string;value:string}){return <div style={metric}><small>{label}</small><div style={{fontSize:22,fontWeight:800}}>{value}</div></div>}
const header:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'},panel:React.CSSProperties={marginTop:20,padding:20,border:'1px solid #dbe7ea',borderRadius:16,background:'white'},metrics:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:12,marginTop:20},metric:React.CSSProperties={padding:16,border:'1px solid #dbe7ea',borderRadius:14,background:'white'},grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,alignItems:'end'},row:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:16,padding:'11px 0',borderBottom:'1px solid #eef2f7',flexWrap:'wrap'},input:React.CSSProperties={display:'block',width:'100%',boxSizing:'border-box',marginTop:6,padding:10,border:'1px solid #cbd5e1',borderRadius:10},primary:React.CSSProperties={padding:'10px 14px',borderRadius:10,border:0,background:'#126e82',color:'white',fontWeight:700},secondary:React.CSSProperties={padding:'8px 11px',borderRadius:9,border:'1px solid #94a3b8',background:'white'},errorBox:React.CSSProperties={marginTop:16,padding:12,borderRadius:10,background:'#fee2e2',color:'#991b1b'},table:React.CSSProperties={width:'100%',borderCollapse:'collapse',textAlign:'left'}
