'use client'

import { FormEvent, useEffect, useState } from 'react'
import { api, type Session } from '../../lib/admin-client'

type AssistantResult={intent:string;answer:string;facts:unknown;sources:string[];grounded:boolean;mutationPerformed:boolean}
type NoticeDraft={title:string;body:string;language:string;humanApprovalRequired:boolean;mutationPerformed:boolean}
type AuditItem={id:string;actorUserId:string;action:string;status:string;confirmedAt?:string|null;executedAt?:string|null;createdAt:string}
type RetrievalAuditItem={id:string;actorUserId:string;toolId:string;intent:string;unitId?:string|null;sources:string[];status:string;createdAt:string}
type EvidenceQuality={sourceCount:number;basis:'CURRENT_QUERY_SNAPSHOT';causalClaim:false;interpretation:'DETERMINISTIC_SIGNAL_NOT_CAUSAL_PROOF'|'FACT_SUMMARY'}
type ActionIntent={mode:'READ_ONLY_DRILLDOWN';workspaceHref:string;workspaceLabel:string;confirmationRequired:true;mutationAllowed:false}
type ActionCard={id:string;domain:string;severity:'LOW'|'MEDIUM'|'HIGH';title:string;summary:string;prompt:string;sources:string[];metrics:Record<string,number|string|null>;whyNow?:string;recommendedNextStep?:string;likelyCause?:string;safeWorkflow?:string[];actionIntent?:ActionIntent;evidenceQuality?:EvidenceQuality}
type ActionBrief={highPriorityCount:number;mediumPriorityCount:number;attentionCount:number;recommendedFocus?:{domain:string;title:string;prompt:string;whyNow:string;recommendedNextStep:string;likelyCause:string;safeWorkflow:string[];actionIntent?:ActionIntent;evidenceQuality?:EvidenceQuality}|null;explanation:string}
type ActionCentre={cards:ActionCard[];brief?:ActionBrief;generatedAt?:string;grounded:boolean;mutationPerformed:boolean}
type AssistantTool={id:string;label:string;context:'SOCIETY'|'PROPERTY';readOnly:boolean}
type AssistantTools={tools:AssistantTool[];mutationAllowList:string[]}
type HelpdeskCandidate={id:string;title:string;priority:string;status:string;unitNumber:string;buildingName:string;assignedToId?:string|null}
type HelpdeskOperations={unassigned:HelpdeskCandidate[]}
type Assignee={id:string;name:string;phone:string}
type AssignmentProposal={id?:string;proposalId?:string;status:string;impactPreview?:{ticketId:string;title:string;priority:string;property:string;currentAssigneeName?:string|null;targetAssigneeName?:string|null;impact:string;expectedUpdatedAt:string};requiresConfirmation?:boolean;autonomousExecution?:boolean;result?:Record<string,string>}

function session():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw) as Session:null}catch{return null}}

export default function AiAssistantPage(){
  const[s,setSession]=useState<Session|null>(null),[message,setMessage]=useState(''),[result,setResult]=useState<AssistantResult|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const[topic,setTopic]=useState(''),[language,setLanguage]=useState<'en-IN'|'hi-IN'|'ta-IN'>('en-IN'),[draft,setDraft]=useState<NoticeDraft|null>(null),[audit,setAudit]=useState<AuditItem[]>([]),[retrievals,setRetrievals]=useState<RetrievalAuditItem[]>([]),[centre,setCentre]=useState<ActionCentre|null>(null),[tools,setTools]=useState<AssistantTools|null>(null)
  const[helpdeskCandidates,setHelpdeskCandidates]=useState<HelpdeskCandidate[]>([]),[assignees,setAssignees]=useState<Assignee[]>([]),[assignmentTicketId,setAssignmentTicketId]=useState(''),[assignmentAssigneeId,setAssignmentAssigneeId]=useState(''),[assignmentProposal,setAssignmentProposal]=useState<AssignmentProposal|null>(null)
  useEffect(()=>{const current=session();setSession(current);if(current){void loadTools(current);void loadCentre(current);if(['SUPER_ADMIN','SOCIETY_ADMIN','COMMITTEE_MEMBER','FACILITY_MANAGER','ACCOUNTANT','AUDITOR','SECURITY_SUPERVISOR'].includes(current.role)){void loadAudit(current)}}},[])
  async function loadTools(current:Session){try{const discovered=await api<AssistantTools>('/ai-operations/assistant/tools',{},current);setTools(discovered);if(discovered.mutationAllowList.includes('ASSIGN_HELPDESK_TICKET')){const[ops,people]=await Promise.all([api<HelpdeskOperations>('/ai-operations/operations-summary',{},current),api<Assignee[]>('/helpdesk/review/context',{},current)]);setHelpdeskCandidates(ops.unassigned);setAssignees(people);setAssignmentTicketId(value=>value&&ops.unassigned.some(item=>item.id===value)?value:ops.unassigned[0]?.id??'');setAssignmentAssigneeId(value=>value&&people.some(item=>item.id===value)?value:people[0]?.id??'')}}catch{/* tool discovery is additive; query authorization remains server-side */}}
  async function loadCentre(current:Session){try{setCentre(await api<ActionCentre>('/ai-operations/assistant/action-centre',{},current))}catch{/* centre is permission/entitlement dependent; assistant remains usable */}}
  async function loadAudit(current:Session){try{const data=await api<{items:AuditItem[];retrievals:RetrievalAuditItem[]}>('/ai-operations/assistant/audit?page=1&pageSize=20',{},current);setAudit(data.items);setRetrievals(data.retrievals)}catch{/* audit is permission-dependent; assistant remains usable without it */}}
  async function ask(e:FormEvent){e.preventDefault();if(!s||message.trim().length<2)return;setBusy(true);setError('');setResult(null);try{setResult(await api<AssistantResult>('/ai-operations/assistant/query',{method:'POST',body:JSON.stringify({message:message.trim()})},s))}catch(e){setError(e instanceof Error?e.message:'Assistant request failed')}finally{setBusy(false)}}
  async function draftNotice(e:FormEvent){e.preventDefault();if(!s||topic.trim().length<3)return;setBusy(true);setError('');try{setDraft(await api<NoticeDraft>('/ai-operations/assistant/notice-draft',{method:'POST',body:JSON.stringify({topic:topic.trim(),language})},s))}catch(e){setError(e instanceof Error?e.message:'Notice draft failed')}finally{setBusy(false)}}
  async function prepareAssignment(){if(!s||!assignmentTicketId||!assignmentAssigneeId)return;setBusy(true);setError('');setAssignmentProposal(null);try{setAssignmentProposal(await api<AssignmentProposal>('/ai-operations/proposals/helpdesk-assignment',{method:'POST',body:JSON.stringify({ticketId:assignmentTicketId,assignedToId:assignmentAssigneeId})},s))}catch(e){setError(e instanceof Error?e.message:'Assignment preview failed')}finally{setBusy(false)}}
  async function resolveAssignment(confirm:boolean){const proposalId=assignmentProposal?.proposalId??assignmentProposal?.id;if(!s||!proposalId)return;setBusy(true);setError('');try{const suffix=confirm?'confirm-helpdesk-assignment':'cancel-helpdesk-assignment';setAssignmentProposal(await api<AssignmentProposal>(`/ai-operations/proposals/${proposalId}/${suffix}`,{method:'POST'},s));if(confirm){await loadTools(s);await loadCentre(s);await loadAudit(s)}}catch(e){setError(e instanceof Error?e.message:'Controlled assignment failed')}finally{setBusy(false)}}
  if(!s)return <main style={{padding:32}}><h1>Sign in required</h1><a href="/">Return to Admin</a></main>
  return <main style={{maxWidth:1120,margin:'0 auto',padding:'28px 22px 80px'}}>
    <header><small>{s.societyName??'Current society'} · {s.role.replaceAll('_',' ')}</small><h1 style={{marginBottom:8}}>Aaraagate Assistant</h1><p style={{maxWidth:820}}>Permission-aware operational assistance grounded in current Aaraagate records. The assistant cannot mutate domain data directly. Resident actions use explicit proposals and confirmation; admin drafting is human-review only.</p><a href="/">← Admin console</a></header>
    {error&&<div style={errorBox}>{error}</div>}
    {centre&&centre.cards.length>0&&<section style={panel}>
      <h2 style={{marginTop:0}}>Daily operations briefing</h2><p>Permission-scoped priorities from authoritative society records. Selecting a card only prepares a grounded query; it does not execute an action.</p>
      {centre.generatedAt&&<p><small>Updated {new Date(centre.generatedAt).toLocaleString('en-IN')} · read only</small></p>}
      {centre.brief?.recommendedFocus&&<div style={focusBox}><strong>Recommended focus · {centre.brief.recommendedFocus.title}</strong><span><b>Why now:</b> {centre.brief.recommendedFocus.whyNow}</span><span><b>Likely cause:</b> Likely signal — not causal proof · {centre.brief.recommendedFocus.likelyCause}</span><span><b>Next step:</b> {centre.brief.recommendedFocus.recommendedNextStep}</span><span><b>Safe workflow:</b> {centre.brief.recommendedFocus.safeWorkflow.join(' → ')}</span><small>{centre.brief.explanation}</small></div>}
      <div style={cardGrid}>{centre.cards.map(card=><div key={card.id} style={actionCard}><span style={severity(card.severity)}>{card.severity}</span><strong>{card.title}</strong><span>{card.summary}</span>{card.whyNow&&<small><b>Why now:</b> {card.whyNow}</small>}{card.likelyCause&&<small><b>Likely cause:</b> Likely signal — not causal proof · {card.likelyCause}</small>}{card.recommendedNextStep&&<small><b>Next step:</b> {card.recommendedNextStep}</small>}{card.safeWorkflow&&<small><b>Safe workflow:</b> {card.safeWorkflow.join(' → ')}</small>}{card.actionIntent&&<small><b>Execution boundary:</b> read-only drill-down · explicit confirmation required before any permitted mutation · autonomous mutation: no</small>}{card.evidenceQuality&&<small><b>Evidence:</b> {card.evidenceQuality.sourceCount} source set{card.evidenceQuality.sourceCount===1?'':'s'} · current query snapshot · causal claim: no</small>}<small>{card.domain} · {card.sources.join(', ')}</small><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:4}}><button type="button" style={button} onClick={()=>setMessage(card.prompt)}>Prepare grounded query</button>{card.actionIntent&&<a href={card.actionIntent.workspaceHref} style={{...button,display:'inline-block',textDecoration:'none',background:'#e2e8f0',color:'#0f172a'}}>Open workspace · {card.actionIntent.workspaceLabel}</a>}</div></div>)}</div>
    </section>}
    {tools?.mutationAllowList.includes('ASSIGN_HELPDESK_TICKET')&&<section style={panel}><h2>Controlled action · Helpdesk assignment</h2><p>Prepare → preview impact → explicit confirmation → normal Helpdesk audit. The Assistant cannot select or execute an arbitrary mutation.</p>{helpdeskCandidates.length===0?<p>No unassigned Helpdesk ticket is currently available.</p>:<div style={{display:'grid',gap:12,maxWidth:700}}><label>Unassigned ticket<select value={assignmentTicketId} onChange={e=>{setAssignmentTicketId(e.target.value);setAssignmentProposal(null)}} style={{...input,maxWidth:'100%',display:'block',width:'100%',marginTop:6}}>{helpdeskCandidates.map(item=><option key={item.id} value={item.id}>{item.priority} · {item.title} · {item.buildingName} {item.unitNumber}</option>)}</select></label><label>Assign to<select value={assignmentAssigneeId} onChange={e=>{setAssignmentAssigneeId(e.target.value);setAssignmentProposal(null)}} style={{...input,maxWidth:'100%',display:'block',width:'100%',marginTop:6}}>{assignees.map(item=><option key={item.id} value={item.id}>{item.name} · {item.phone}</option>)}</select></label><button type="button" onClick={()=>void prepareAssignment()} disabled={busy||!assignmentTicketId||!assignmentAssigneeId} style={button}>Prepare assignment preview</button></div>}{assignmentProposal?.impactPreview&&<div style={resultBox}><strong>Review impact before confirming</strong><p>{assignmentProposal.impactPreview.title} · {assignmentProposal.impactPreview.priority} · {assignmentProposal.impactPreview.property}</p><p>{assignmentProposal.impactPreview.impact}</p><small>Current: {assignmentProposal.impactPreview.currentAssigneeName??'Unassigned'} → Target: {assignmentProposal.impactPreview.targetAssigneeName??'Unassigned'} · autonomous execution: no</small>{assignmentProposal.status==='PROPOSED'&&<div style={{display:'flex',gap:10,marginTop:12}}><button type="button" onClick={()=>void resolveAssignment(false)} disabled={busy} style={{...button,background:'#e2e8f0',color:'#0f172a'}}>Cancel</button><button type="button" onClick={()=>void resolveAssignment(true)} disabled={busy} style={button}>Confirm assignment</button></div>}</div>}{assignmentProposal&&assignmentProposal.status==='EXECUTED'&&<div style={resultBox}><strong>Assignment executed through Helpdesk controls.</strong><p><small>Proposal {(assignmentProposal.proposalId??assignmentProposal.id??'unknown').slice(0,8)}… · downstream Helpdesk activity retained.</small></p></div>}</section>}

    <section style={panel}><h2>Ask operations</h2><p>Only capabilities authorized for this role are shown below. Unsupported questions return no invented answer.</p>{tools&&tools.tools.length>0&&<div style={toolWrap} aria-label="Available assistant capabilities">{tools.tools.map(tool=><span key={tool.id} style={toolChip}>{tool.label}<small style={{opacity:.68}}> · {tool.context==='PROPERTY'?'property':'society'} · read only</small></span>)}</div>}<form onSubmit={ask}><textarea value={message} onChange={e=>setMessage(e.target.value)} rows={4} placeholder="Example: Show overdue maintenance above ₹5000" style={textarea}/><button disabled={busy||message.trim().length<2} style={button}>{busy?'Checking…':'Ask assistant'}</button></form>{result&&<div style={resultBox}><strong>{result.answer}</strong><p><small>Intent: {result.intent} · grounded: {String(result.grounded)} · mutation: {String(result.mutationPerformed)}</small></p><FactView facts={result.facts}/><small>Sources: {result.sources.join(', ')||'None'}</small></div>}</section>
    <section style={panel}><h2>Draft a notice</h2><p>This produces copy only. It never publishes a notice and always requires human review.</p><form onSubmit={draftNotice} style={{display:'grid',gap:12}}><textarea value={topic} onChange={e=>setTopic(e.target.value)} rows={3} placeholder="Example: Water shutdown from 10 AM to 1 PM for pump maintenance" style={textarea}/><select value={language} onChange={e=>setLanguage(e.target.value as typeof language)} style={input}><option value="en-IN">English</option><option value="hi-IN">Hindi</option><option value="ta-IN">Tamil</option></select><button disabled={busy||topic.trim().length<3} style={button}>Create review draft</button></form>{draft&&<div style={resultBox}><h3>{draft.title}</h3><p>{draft.body}</p><small>Human approval required · no mutation performed</small></div>}</section>
    {(retrievals.length>0||audit.length>0)&&<section style={panel}><h2>Recent AI evidence</h2><p>Retrieval evidence is privacy-minimal and excludes prompt and returned payload text. Confirmed actions remain separately traceable through proposals and downstream domain audits.</p>{retrievals.length>0&&<><h3>Retrieval evidence</h3><div style={{display:'grid',gap:8}}>{retrievals.map(item=><div key={item.id} style={auditRow}><div><strong>{item.toolId.replaceAll('_',' ')}</strong><div><small>{item.intent.replaceAll('_',' ')} · {item.status} · {new Date(item.createdAt).toLocaleString('en-IN')}</small></div><div><small>{item.unitId?'Property scoped':'Society scoped'} · Sources: {item.sources.join(', ')||'None'}</small></div></div><code>{item.id.slice(0,8)}…</code></div>)}</div></>}{audit.length>0&&<><h3>Confirmed-action evidence</h3><div style={{display:'grid',gap:8}}>{audit.map(item=><div key={item.id} style={auditRow}><div><strong>{item.action.replaceAll('_',' ')}</strong><div><small>{item.status} · {new Date(item.createdAt).toLocaleString('en-IN')}</small></div></div><code>{item.id.slice(0,8)}…</code></div>)}</div></>}</section>}
  </main>
}

function FactView({facts}:{facts:unknown}){if(!facts||typeof facts!=='object')return <p>{String(facts??'No additional records returned.')}</p>;if(Array.isArray(facts))return <ul style={{paddingLeft:20}}>{facts.slice(0,8).map((item,index)=><li key={index}>{displayValue(item)}</li>)}</ul>;const entries=Object.entries(facts as Record<string,unknown>);if(entries.length===0)return <p>No additional records returned.</p>;return <dl style={factGrid}>{entries.map(([key,value])=><div key={key}><dt style={{fontSize:12,fontWeight:800,color:'#64748b'}}>{key.replaceAll('_',' ')}</dt><dd style={{margin:'3px 0 10px'}}>{displayValue(value)}</dd></div>)}</dl>}
function displayValue(value:unknown):string{if(value==null)return '—';if(Array.isArray(value))return value.map(displayValue).join(' · ');if(typeof value==='object')return Object.entries(value as Record<string,unknown>).map(([k,v])=>`${k}: ${displayValue(v)}`).join(' · ');return String(value)}

const panel={background:'white',border:'1px solid #e5e7eb',borderRadius:18,padding:20,marginTop:18,boxShadow:'0 8px 24px rgba(15,23,42,.05)'} as const
const textarea={width:'100%',padding:'12px 14px',border:'1px solid #cbd5e1',borderRadius:12,boxSizing:'border-box',font:'inherit',marginBottom:12} as const
const input={padding:'10px 12px',border:'1px solid #cbd5e1',borderRadius:10,maxWidth:220} as const
const button={padding:'11px 16px',border:0,borderRadius:10,background:'#111827',color:'white',fontWeight:800,cursor:'pointer'} as const
const resultBox={marginTop:16,padding:16,borderRadius:14,background:'#f8fafc'} as const
const errorBox={marginTop:18,padding:14,borderRadius:12,background:'#fee2e2',color:'#991b1b'} as const
const toolWrap={display:'flex',flexWrap:'wrap',gap:8,margin:'12px 0 16px'} as const
const toolChip={padding:'8px 11px',border:'1px solid #dbe4ea',borderRadius:999,background:'#f8fafc',fontSize:13,fontWeight:800} as const
const factGrid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:'4px 16px',margin:'14px 0'} as const
const auditRow={display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',padding:'10px 0',borderBottom:'1px solid #e5e7eb'} as const
const cardGrid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12} as const
const actionCard={display:'grid',gap:8,textAlign:'left',padding:16,border:'1px solid #dbe4ea',borderRadius:14,background:'#fff',cursor:'pointer',font:'inherit'} as const
const focusBox={display:'grid',gap:6,padding:14,margin:'12px 0 16px',border:'1px solid #cbd5e1',borderRadius:14,background:'#f8fafc'} as const
function severity(level:ActionCard['severity']){return {justifySelf:'start',padding:'3px 8px',borderRadius:999,fontSize:11,fontWeight:900,background:level==='HIGH'?'#fee2e2':level==='MEDIUM'?'#fef3c7':'#dcfce7',color:level==='HIGH'?'#991b1b':level==='MEDIUM'?'#92400e':'#166534'} as const}
