'use client'

import { FormEvent,useState } from 'react'

type Session={accessToken:string;role:string;societyName?:string}
type Snapshot={paymentId:string;status:string;amountPaise:string;grossAllocatedPaise:string;reversedAllocatedPaise:string;netAllocatedPaise:string;refundedPaise:string;refundablePaise:string}
type Allocation={id:string;receivableId:string;amountPaise:string;reversedPaise:string;reversiblePaise:string;allocatedAt:string}
type Reversal={id:string;allocationId:string;receivableId:string;amountPaise:string;reason:string;reversedAt:string}
type Refund={id:string;amountPaise:string;reason:string;providerReference?:string;refundedAt:string}
const base=(process.env.NEXT_PUBLIC_AARAGATE_API_BASE_URL??'http://localhost:3000').replace(/\/$/,'')
const manageRoles=new Set(['SUPER_ADMIN','ACCOUNTANT'])
function session():Session|null{try{const r=sessionStorage.getItem('aaraagate.admin.session');return r?JSON.parse(r):null}catch{return null}}
async function api<T>(s:Session,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${base}/api/v1${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.accessToken}`,...init.headers}});const t=await r.text(),b=t?JSON.parse(t):null;if(!r.ok)throw new Error(Array.isArray(b?.message)?b.message.join(', '):b?.message??`Request failed (${r.status})`);return b as T}
const money=(v:string|number|undefined)=>`₹${(Number(v??0)/100).toLocaleString('en-IN',{maximumFractionDigits:2})}`
export default function PaymentExceptions(){const[paymentId,setPaymentId]=useState(''),[snap,setSnap]=useState<Snapshot|null>(null),[allocs,setAllocs]=useState<Allocation[]>([]),[revs,setRevs]=useState<Reversal[]>([]),[refunds,setRefunds]=useState<Refund[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[providerRef,setProviderRef]=useState('');const s=typeof window==='undefined'?null:session(),canManage=!!s&&manageRoles.has(s.role)
async function inspect(e?:FormEvent){e?.preventDefault();if(!s||!paymentId.trim())return;setBusy(true);setError('');try{const id=paymentId.trim();const[x,a,r,f]=await Promise.all([api<Snapshot>(s,`/accounting/payment-exceptions/payments/${id}`),api<Allocation[]>(s,`/accounting/settlements/payments/${id}/allocations`),api<Reversal[]>(s,`/accounting/payment-exceptions/payments/${id}/allocation-reversals`),api<Refund[]>(s,`/accounting/payment-exceptions/payments/${id}/refunds`)]);setSnap(x);setAllocs(a);setRevs(r);setRefunds(f)}catch(e){setError(e instanceof Error?e.message:'Could not inspect payment')}finally{setBusy(false)}}
async function reverse(a:Allocation){if(!s||!canManage)return;const rupees=Number(prompt(`Reverse allocation ${a.id}. Amount in ₹ (max ${money(a.reversiblePaise)}):`)??'0'),why=prompt('Reason for reversal:')?.trim();if(!rupees||!why)return;setBusy(true);try{await api(s,`/accounting/payment-exceptions/allocations/${a.id}/reverse`,{method:'POST',body:JSON.stringify({amountPaise:Math.round(rupees*100),reason:why,idempotencyKey:`admin-reversal-${a.id}-${Date.now()}`})});await inspect()}catch(e){setError(e instanceof Error?e.message:'Could not reverse allocation')}finally{setBusy(false)}}
async function refund(e:FormEvent){e.preventDefault();if(!s||!canManage||!snap)return;const rupees=Number(amount);if(!rupees||!reason.trim())return;setBusy(true);setError('');try{await api(s,`/accounting/payment-exceptions/payments/${snap.paymentId}/refunds`,{method:'POST',body:JSON.stringify({amountPaise:Math.round(rupees*100),reason:reason.trim(),providerReference:providerRef.trim()||undefined,idempotencyKey:`admin-refund-${snap.paymentId}-${Date.now()}`})});setAmount('');setReason('');setProviderRef('');await inspect()}catch(e){setError(e instanceof Error?e.message:'Could not record refund')}finally{setBusy(false)}}
if(!s)return <main style={{padding:32}}><h1>Finance access required</h1><a href="/">Return to Admin</a></main>;return <main style={{maxWidth:1100,margin:'0 auto',padding:'28px 22px 80px'}}><header><small>{s.societyName??'Current society'} · {s.role.replaceAll('_',' ')}</small><h1>Payment exceptions</h1><p>Auditable allocation reversals and refund recording. Captured payments are never rewritten.</p><a href="/finance">← Finance workspace</a></header>{error&&<p style={{padding:12,background:'#fee2e2',borderRadius:10}}>{error}</p>}<section style={panel}><form onSubmit={inspect} style={row}><label style={{flex:1}}>Payment ID<input value={paymentId} onChange={e=>setPaymentId(e.target.value)} placeholder="UUID" style={input}/></label><button disabled={busy||!paymentId.trim()} style={button}>Inspect</button></form></section>{snap&&<><section style={grid}>{[['Captured',snap.amountPaise],['Gross allocated',snap.grossAllocatedPaise],['Reversed',snap.reversedAllocatedPaise],['Net allocated',snap.netAllocatedPaise],['Refunded',snap.refundedPaise],['Refundable',snap.refundablePaise]].map(([k,v])=><div key={k} style={metric}><small>{k}</small><b>{money(v)}</b></div>)}</section><section style={panel}><h2>Allocations</h2>{allocs.length===0?<p>No allocations.</p>:allocs.map(a=><div key={a.id} style={item}><span><b>{money(a.amountPaise)}</b> to {a.receivableId}<br/><small>Reversed {money(a.reversedPaise)} · reversible {money(a.reversiblePaise)}</small></span>{canManage&&Number(a.reversiblePaise)>0&&<button disabled={busy} onClick={()=>void reverse(a)} style={button}>Reverse</button>}</div>)}</section>{canManage&&<section style={panel}><h2>Record refund</h2><p>Only genuinely refundable cash can be recorded. Reverse allocations first when necessary.</p><form onSubmit={refund} style={grid}><label>Amount (₹)<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} style={input}/></label><label>Reason<input value={reason} onChange={e=>setReason(e.target.value)} style={input}/></label><label>Provider reference<input value={providerRef} onChange={e=>setProviderRef(e.target.value)} style={input}/></label><button disabled={busy||!amount||!reason.trim()} style={button}>Record refund</button></form></section>}<section style={panel}><h2>Audit history</h2><h3>Allocation reversals</h3>{revs.length===0?<p>None.</p>:revs.map(r=><div key={r.id} style={item}><span>{money(r.amountPaise)} · {r.reason}</span><small>{new Date(r.reversedAt).toLocaleString('en-IN')}</small></div>)}<h3>Refunds</h3>{refunds.length===0?<p>None.</p>:refunds.map(r=><div key={r.id} style={item}><span>{money(r.amountPaise)} · {r.reason}{r.providerReference?` · ${r.providerReference}`:''}</span><small>{new Date(r.refundedAt).toLocaleString('en-IN')}</small></div>)}</section></>}</main>}
const panel={background:'white',border:'1px solid #e5e7eb',borderRadius:16,padding:18,marginTop:18} as const,input={display:'block',width:'100%',padding:'10px 12px',border:'1px solid #d1d5db',borderRadius:9,marginTop:5,boxSizing:'border-box'} as const,button={padding:'10px 14px',border:0,borderRadius:9,background:'#111827',color:'white',fontWeight:700,cursor:'pointer'} as const,row={display:'flex',gap:12,alignItems:'end',flexWrap:'wrap'} as const,grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:12,marginTop:18} as const,metric={background:'#f8fafc',borderRadius:14,padding:16,display:'grid',gap:5} as const,item={display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',padding:'10px 0',borderBottom:'1px solid #e5e7eb'} as const