version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: pub
    directory: /apps/resident
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: pub
    directory: /apps/guard
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
