version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      nestjs-major:
        patterns:
          - "@nestjs/common"
          - "@nestjs/core"
          - "@nestjs/platform-express"
        update-types:
          - "major"
      prisma-major:
        patterns:
          - "prisma"
          - "@prisma/client"
        update-types:
          - "major"
  - package-ecosystem: pub
    directory: /apps/resident
    target-branch: develop
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: pub
    directory: /apps/guard
    target-branch: develop
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
