'use client'

import { FormEvent, useCallback, useEffect, useState } from 'react'

type Session={accessToken:string;role:string;societyId:string;societyName?:string}
type Building={id:string;name:string;code:string}
type Floor={id:string;name:string;sortOrder:number}
type Unit={id:string;number:string;floor?:Floor|null}
const base=(process.env.NEXT_PUBLIC_AARAGATE_API_BASE_URL??'http://localhost:3000').replace(/\/$/,'')
function getSession():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw) as Session:null}catch{return null}}
async function api<T>(s:Session,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${base}/api/v1${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.accessToken}`,...init.headers}});const t=await r.text();const b=t?JSON.parse(t):null;if(!r.ok)throw new Error(b?.message??`Request failed (${r.status})`);return b as T}

export default function PropertyPage(){
  const[session,setSession]=useState<Session|null>(null),[buildings,setBuildings]=useState<Building[]>([]),[buildingId,setBuildingId]=useState(''),[floors,setFloors]=useState<Floor[]>([]),[units,setUnits]=useState<Unit[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const[buildingName,setBuildingName]=useState(''),[buildingCode,setBuildingCode]=useState(''),[floorName,setFloorName]=useState(''),[floorOrder,setFloorOrder]=useState('0'),[unitNumber,setUnitNumber]=useState(''),[unitFloorId,setUnitFloorId]=useState('')
  const allowed=(s:Session|null)=>!!s&&['SUPER_ADMIN','SOCIETY_ADMIN'].includes(s.role)
  const loadBuildings=useCallback(async(s:Session)=>{setLoading(true);setError('');try{const rows=await api<Building[]>(s,`/societies/${s.societyId}/buildings`);setBuildings(rows);setBuildingId(v=>v||rows[0]?.id||'')}catch(e){setError(e instanceof Error?e.message:'Could not load property structure')}finally{setLoading(false)}},[])
  const loadChildren=useCallback(async(s:Session,bid:string)=>{if(!bid){setFloors([]);setUnits([]);return}try{const[f,u]=await Promise.all([api<Floor[]>(s,`/societies/${s.societyId}/buildings/${bid}/floors`),api<Unit[]>(s,`/societies/${s.societyId}/buildings/${bid}/units`)]);setFloors(f);setUnits(u);setUnitFloorId(v=>f.some(x=>x.id===v)?v:f[0]?.id??'')}catch(e){setError(e instanceof Error?e.message:'Could not load floors and units')}},[])
  useEffect(()=>{const s=getSession();setSession(s);if(allowed(s))void loadBuildings(s);else setLoading(false)},[loadBuildings])
  useEffect(()=>{if(session&&buildingId)void loadChildren(session,buildingId)},[session,buildingId,loadChildren])
  const run=async(fn:()=>Promise<unknown>)=>{if(!session)return;setBusy(true);setError('');try{await fn();await loadBuildings(session);if(buildingId)await loadChildren(session,buildingId)}catch(e){setError(e instanceof Error?e.message:'Property update failed')}finally{setBusy(false)}}
  const addBuilding=(e:FormEvent)=>{e.preventDefault();if(!session)return;void run(async()=>{const created=await api<Building>(session,`/societies/${session.societyId}/buildings`,{method:'POST',body:JSON.stringify({name:buildingName.trim(),code:buildingCode.trim()})});setBuildingName('');setBuildingCode('');setBuildingId(created.id)})}
  const addFloor=(e:FormEvent)=>{e.preventDefault();if(!session||!buildingId)return;void run(async()=>{await api(session,`/societies/${session.societyId}/buildings/${buildingId}/floors`,{method:'POST',body:JSON.stringify({name:floorName.trim(),sortOrder:Number(floorOrder)})});setFloorName('');setFloorOrder('0')})}
  const addUnit=(e:FormEvent)=>{e.preventDefault();if(!session||!buildingId||!unitFloorId)return;void run(async()=>{await api(session,`/societies/${session.societyId}/buildings/${buildingId}/units`,{method:'POST',body:JSON.stringify({number:unitNumber.trim(),floorId:unitFloorId})});setUnitNumber('')})}
  if(loading)return <main style={{padding:32}}>Loading property setup…</main>
  if(!allowed(session))return <main style={{padding:32}}><h1>Society administration required</h1><a href="/">Return to Admin</a></main>
  return <main style={{maxWidth:1120,margin:'0 auto',padding:'28px 22px 80px'}}><header style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><small>{session?.societyName??'Current society'}</small><h1 style={{margin:'4px 0'}}>Property structure</h1><p style={{margin:0}}>Configure the V1 hierarchy as Building / Block → Floor → Unit / Flat.</p></div><a href="/">← Admin console</a></header>{error&&<div style={errorBox}>{error}</div>}<section style={panel}><h2>Buildings / blocks</h2><form onSubmit={addBuilding} style={formGrid}><label style={label}>Name<input style={input} value={buildingName} onChange={e=>setBuildingName(e.target.value)} required/></label><label style={label}>Code<input style={input} value={buildingCode} onChange={e=>setBuildingCode(e.target.value)} required/></label><button disabled={busy} style={primary}>Add building</button></form><label style={{...label,marginTop:16,maxWidth:480}}>Working building<select style={input} value={buildingId} onChange={e=>setBuildingId(e.target.value)}><option value="">Select building</option>{buildings.map(b=><option key={b.id} value={b.id}>{b.name} · {b.code}</option>)}</select></label></section>{buildingId&&<><section style={panel}><h2>Floors</h2><form onSubmit={addFloor} style={formGrid}><label style={label}>Floor name<input style={input} placeholder="Ground Floor / 1st Floor" value={floorName} onChange={e=>setFloorName(e.target.value)} required/></label><label style={label}>Sort order<input style={input} type="number" value={floorOrder} onChange={e=>setFloorOrder(e.target.value)} required/></label><button disabled={busy} style={primary}>Add floor</button></form><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:14}}>{floors.map(f=><span key={f.id} style={chip}>{f.name}</span>)}{floors.length===0&&<p>Add the first floor before creating new units.</p>}</div></section><section style={panel}><h2>Units / flats</h2><form onSubmit={addUnit} style={formGrid}><label style={label}>Unit number<input style={input} placeholder="A-101" value={unitNumber} onChange={e=>setUnitNumber(e.target.value)} required/></label><label style={label}>Floor<select style={input} value={unitFloorId} onChange={e=>setUnitFloorId(e.target.value)} required><option value="">Select floor</option>{floors.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><button disabled={busy||!unitFloorId} style={primary}>Add unit</button></form><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10,marginTop:16}}>{units.map(u=><article key={u.id} style={unitCard}><b>{u.number}</b><small>{u.floor?.name??'Legacy unit · floor unassigned'}</small></article>)}{units.length===0&&<p>No units configured.</p>}</div></section></>}</main>
}
const panel:React.CSSProperties={marginTop:20,padding:20,border:'1px solid #dbe7ea',borderRadius:16,background:'white'}
const formGrid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:10,alignItems:'end'}
const label:React.CSSProperties={display:'grid',gap:6}
const input:React.CSSProperties={padding:11,border:'1px solid #cbd5e1',borderRadius:10}
const primary:React.CSSProperties={padding:'11px 14px',borderRadius:10,border:'1px solid #05879A',background:'#05879A',color:'white',fontWeight:700}
const chip:React.CSSProperties={padding:'7px 10px',borderRadius:999,background:'#e6f8fa',border:'1px solid #b9e8ed'}
const unitCard:React.CSSProperties={padding:12,border:'1px solid #e5e7eb',borderRadius:12,display:'grid',gap:4}
const errorBox:React.CSSProperties={marginTop:18,padding:12,border:'1px solid #ef4444',borderRadius:10}
