'use client'

import {FormEvent,useEffect,useMemo,useState} from 'react'
import { ActionBar, ErrorState, EvidenceGrid, FormField, PageHeader, PageShell, PrimaryButton, SecondaryButton, SelectField, Timeline } from '../../components/admin-ui'

type Session={accessToken:string;role:string;societyName?:string}
type Asset={id:string;code:string;name:string;category:string;location?:string|null;manufacturer?:string|null;model?:string|null;serialNumber?:string|null;installedAt?:string|null;warrantyEndsAt?:string|null;status:'ACTIVE'|'OUT_OF_SERVICE'|'RETIRED';notes?:string|null}
type Assignee={id:string;name:string;phone:string}
type WorkOrder={id:string;assetId?:string|null;assetCode?:string|null;assetName?:string|null;workType:'CORRECTIVE'|'PREVENTIVE'|'INSPECTION';priority:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';title:string;description?:string|null;status:'OPEN'|'IN_PROGRESS'|'COMPLETED'|'CANCELLED';scheduledAt?:string|null;dueAt?:string|null;assignedUserId?:string|null;assignedUserName?:string|null;completionNote?:string|null;completedAt?:string|null;createdAt:string}
type WorkOrderEvent={id:string;eventType:string;fromStatus?:string|null;toStatus?:string|null;note?:string|null;actorName?:string|null;occurredAt:string}

const base=(process.env.NEXT_PUBLIC_AARAGATE_API_BASE_URL??'http://localhost:3000').replace(/\/$/,'')
const readRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','FACILITY_MANAGER','COMMITTEE_MEMBER'])
const manageRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','FACILITY_MANAGER'])
function getSession():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw):null}catch{return null}}
async function api<T>(s:Session,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${base}/api/v1${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.accessToken}`,...init.headers}});const text=await r.text(),body=text?JSON.parse(text):null;if(!r.ok)throw new Error(Array.isArray(body?.message)?body.message.join(', '):body?.message??`Request failed (${r.status})`);return body as T}
const fmt=(v?:string|null)=>v?new Date(v).toLocaleString('en-IN'):'—'
const iso=(v:string)=>v?new Date(v).toISOString():undefined

export default function FacilitiesPage(){
 const s=typeof window==='undefined'?null:getSession(),canRead=!!s&&readRoles.has(s.role),canManage=!!s&&manageRoles.has(s.role)
 const[assets,setAssets]=useState<Asset[]>([]),[orders,setOrders]=useState<WorkOrder[]>([]),[assignees,setAssignees]=useState<Assignee[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const[history,setHistory]=useState<WorkOrderEvent[]>([]),[historyOrderId,setHistoryOrderId]=useState('')
 const[actionOrderId,setActionOrderId]=useState(''),[actionStatus,setActionStatus]=useState<'COMPLETED'|'CANCELLED'>('COMPLETED'),[actionNote,setActionNote]=useState('')
 const[code,setCode]=useState(''),[name,setName]=useState(''),[category,setCategory]=useState(''),[location,setLocation]=useState(''),[manufacturer,setManufacturer]=useState(''),[model,setModel]=useState(''),[serialNumber,setSerialNumber]=useState(''),[installedAt,setInstalledAt]=useState(''),[warrantyEndsAt,setWarrantyEndsAt]=useState(''),[notes,setNotes]=useState('')
 const[assetId,setAssetId]=useState(''),[workType,setWorkType]=useState<WorkOrder['workType']>('CORRECTIVE'),[priority,setPriority]=useState<WorkOrder['priority']>('MEDIUM'),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[scheduledAt,setScheduledAt]=useState(''),[dueAt,setDueAt]=useState(''),[assignedUserId,setAssignedUserId]=useState('')
 const openCount=useMemo(()=>orders.filter(o=>o.status==='OPEN'||o.status==='IN_PROGRESS').length,[orders])
 const selectedActionOrder=orders.find(o=>o.id===actionOrderId)??null

 async function load(){if(!s||!canRead)return;setBusy(true);setError('');try{const[a,w,u]=await Promise.all([api<Asset[]>(s,'/facilities/assets'),api<WorkOrder[]>(s,'/facilities/work-orders'),api<Assignee[]>(s,'/facilities/operator-context')]);setAssets(a);setOrders(w);setAssignees(u)}catch(e){setError(e instanceof Error?e.message:'Could not load facilities workspace')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])

 async function createAsset(e:FormEvent){e.preventDefault();if(!s||!canManage)return;setBusy(true);setError('');setNotice('');try{await api(s,'/facilities/assets',{method:'POST',body:JSON.stringify({code:code.trim(),name:name.trim(),category:category.trim(),location:location.trim()||undefined,manufacturer:manufacturer.trim()||undefined,model:model.trim()||undefined,serialNumber:serialNumber.trim()||undefined,installedAt:iso(installedAt),warrantyEndsAt:iso(warrantyEndsAt),notes:notes.trim()||undefined})});setCode('');setName('');setCategory('');setLocation('');setManufacturer('');setModel('');setSerialNumber('');setInstalledAt('');setWarrantyEndsAt('');setNotes('');setNotice('Facility asset created.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not create facility asset')}finally{setBusy(false)}}

 async function createOrder(e:FormEvent){e.preventDefault();if(!s||!canManage)return;setBusy(true);setError('');setNotice('');try{await api(s,'/facilities/work-orders',{method:'POST',body:JSON.stringify({assetId:assetId||undefined,workType,priority,title:title.trim(),description:description.trim()||undefined,scheduledAt:iso(scheduledAt),dueAt:iso(dueAt),assignedUserId:assignedUserId||undefined})});setAssetId('');setTitle('');setDescription('');setScheduledAt('');setDueAt('');setAssignedUserId('');setNotice('Work order created.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not create work order')}finally{setBusy(false)}}

 async function startOrder(o:WorkOrder){if(!s||!canManage)return;setBusy(true);setError('');setNotice('');try{await api(s,`/facilities/work-orders/${o.id}/status`,{method:'POST',body:JSON.stringify({status:'IN_PROGRESS'})});setNotice('Work order started.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not start work order')}finally{setBusy(false)}}

 function prepareTransition(o:WorkOrder,status:'COMPLETED'|'CANCELLED'){setActionOrderId(o.id);setActionStatus(status);setActionNote(status==='COMPLETED'?(o.completionNote??''):'')}

 async function submitTransition(e:FormEvent){e.preventDefault();if(!s||!canManage||!selectedActionOrder)return;const note=actionNote.trim();if(actionStatus==='COMPLETED'&&note.length<5){setError('Completion note must contain at least 5 characters.');return}setBusy(true);setError('');setNotice('');try{await api(s,`/facilities/work-orders/${selectedActionOrder.id}/status`,{method:'POST',body:JSON.stringify({status:actionStatus,completionNote:note||undefined})});setNotice(actionStatus==='COMPLETED'?'Work order completed.':'Work order cancelled.');setActionOrderId('');setActionNote('');await load()}catch(e){setError(e instanceof Error?e.message:'Could not update work order')}finally{setBusy(false)}}

 async function openHistory(id:string){if(!s)return;setBusy(true);setError('');try{setHistory(await api<WorkOrderEvent[]>(s,`/facilities/work-orders/${id}/events`));setHistoryOrderId(id)}catch(e){setError(e instanceof Error?e.message:'Could not load work-order history')}finally{setBusy(false)}}

 if(!s||!canRead)return <PageShell><PageHeader title="Facilities access required" actions={<a href="/">Return to Admin</a>}/></PageShell>

 return <PageShell>
  <PageHeader context={`${s.societyName??'Current society'} · ${s.role.replaceAll('_',' ')}`} title="Facilities operations" description="Track common-area assets and maintenance work orders separately from resident amenity bookings." actions={<a href="/">← Admin home</a>}/>
  {error&&<ErrorState title="Facilities operation failed" description={error}/>}<ActionBar feedback={notice} label="Facilities workspace actions"><SecondaryButton loading={busy} onClick={()=>void load()}>Reload workspace</SecondaryButton></ActionBar>

  <section style={grid}><div style={panel}><h2>Operations summary</h2><EvidenceGrid items={[{id:'assets',label:'Assets',value:assets.length},{id:'open-orders',label:'Open work orders',value:openCount},{id:'critical-active',label:'Critical active',value:orders.filter(o=>o.priority==='CRITICAL'&&o.status!=='COMPLETED'&&o.status!=='CANCELLED').length}]}/></div><div style={panel}><h2>Access boundary</h2><p>Read access follows FACILITIES_READ; creation and lifecycle changes follow FACILITIES_MANAGE.</p></div></section>

  {canManage&&<section style={grid}>
   <form onSubmit={createAsset} style={panel}><h2>Add facility asset</h2><FormField label="Code" required value={code} onChange={e=>setCode(e.target.value)}/><FormField label="Name" required value={name} onChange={e=>setName(e.target.value)}/><FormField label="Category" required value={category} onChange={e=>setCategory(e.target.value)} placeholder="Lift, pump, generator, CCTV…"/><FormField label="Location" value={location} onChange={e=>setLocation(e.target.value)}/><FormField label="Manufacturer" value={manufacturer} onChange={e=>setManufacturer(e.target.value)}/><FormField label="Model" value={model} onChange={e=>setModel(e.target.value)}/><FormField label="Serial number" value={serialNumber} onChange={e=>setSerialNumber(e.target.value)}/><FormField label="Installed at" type="datetime-local" value={installedAt} onChange={e=>setInstalledAt(e.target.value)}/><FormField label="Warranty ends" type="datetime-local" value={warrantyEndsAt} onChange={e=>setWarrantyEndsAt(e.target.value)}/><FormField label="Notes" multiline value={notes} onChange={e=>setNotes(e.target.value)}/><PrimaryButton type="submit" loading={busy}>Create asset</PrimaryButton></form>
   <form onSubmit={createOrder} style={panel}><h2>Create work order</h2><SelectField label="Asset" value={assetId} onChange={e=>setAssetId(e.target.value)}><option value="">Unlinked work order</option>{assets.filter(a=>a.status!=='RETIRED').map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</SelectField><SelectField label="Work type" value={workType} onChange={e=>setWorkType(e.target.value as WorkOrder['workType'])}><option>CORRECTIVE</option><option>PREVENTIVE</option><option>INSPECTION</option></SelectField><SelectField label="Priority" value={priority} onChange={e=>setPriority(e.target.value as WorkOrder['priority'])}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></SelectField><FormField label="Title" required value={title} onChange={e=>setTitle(e.target.value)}/><FormField label="Description" multiline value={description} onChange={e=>setDescription(e.target.value)}/><FormField label="Scheduled at" type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)}/><FormField label="Due at" type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/><SelectField label="Assignee" value={assignedUserId} onChange={e=>setAssignedUserId(e.target.value)}><option value="">Unassigned</option>{assignees.map(u=><option key={u.id} value={u.id}>{u.name} · {u.phone}</option>)}</SelectField><PrimaryButton type="submit" loading={busy}>Create work order</PrimaryButton></form>
  </section>}

  <section style={grid}>
   <div style={panel}><h2>Facility assets</h2>{assets.length===0?<p>No facility assets registered.</p>:assets.map(a=><div key={a.id} style={item}><span><b>{a.code} · {a.name}</b><br/><small>{a.category} · {a.status}{a.location?` · ${a.location}`:''}</small><br/><small>{[a.manufacturer,a.model,a.serialNumber].filter(Boolean).join(' · ')||'No equipment metadata'}</small><br/><small>Warranty {fmt(a.warrantyEndsAt)}</small></span></div>)}</div>
   <div style={panel}><h2>Work orders</h2>{orders.length===0?<p>No work orders.</p>:orders.map(o=><div key={o.id} style={item}><span><b>{o.priority} · {o.title}</b><br/><small>{o.workType} · {o.status}{o.assetCode?` · ${o.assetCode} ${o.assetName??''}`:''}</small><br/><small>Scheduled {fmt(o.scheduledAt)} · due {fmt(o.dueAt)}</small><br/><small>Assignee {o.assignedUserName??'Unassigned'}</small>{o.completionNote?<><br/><small>Completion: {o.completionNote}</small></>:null}</span><span style={actions}><SecondaryButton disabled={busy} onClick={()=>void openHistory(o.id)}>History</SecondaryButton>{canManage&&(o.status==='OPEN'||o.status==='IN_PROGRESS')&&<>{o.status==='OPEN'&&<SecondaryButton disabled={busy} onClick={()=>void startOrder(o)}>Start</SecondaryButton>}<PrimaryButton disabled={busy} onClick={()=>prepareTransition(o,'COMPLETED')}>Complete</PrimaryButton><SecondaryButton disabled={busy} onClick={()=>prepareTransition(o,'CANCELLED')}>Cancel</SecondaryButton></>}</span></div>)}</div>
  </section>

  {selectedActionOrder&&canManage&&<form onSubmit={submitTransition} style={{...panel,marginTop:18}}><div style={row}><div><h2 style={{margin:0}}>{actionStatus==='COMPLETED'?'Complete work order':'Cancel work order'}</h2><p style={{margin:'6px 0 0'}}>{selectedActionOrder.priority} · {selectedActionOrder.title}</p></div><SecondaryButton type="button" onClick={()=>{setActionOrderId('');setActionNote('')}}>Close</SecondaryButton></div><FormField label={actionStatus==='COMPLETED'?'Completion note':'Cancellation note (optional)'} multiline value={actionNote} onChange={e=>setActionNote(e.target.value)} required={actionStatus==='COMPLETED'} minLength={actionStatus==='COMPLETED'?5:undefined} maxLength={5000}/><ActionBar feedback={notice}>{actionStatus==='COMPLETED'?<PrimaryButton type="submit" loading={busy}>Confirm completion</PrimaryButton>:<SecondaryButton type="submit" loading={busy}>Confirm cancellation</SecondaryButton>}</ActionBar></form>}

  {historyOrderId&&<section style={{...panel,marginTop:18}}><div style={row}><div><h2 style={{margin:0}}>Work-order history</h2><p style={{margin:'6px 0 0'}}>Append-only lifecycle evidence for the selected work order.</p></div><SecondaryButton onClick={()=>{setHistoryOrderId('');setHistory([])}}>Close</SecondaryButton></div><Timeline label="Work-order history" emptyLabel="No work-order events recorded." events={history.map(e=>({id:e.id,label:e.eventType.replaceAll('_',' '),actor:e.actorName??'Recorded actor',dateTime:e.occurredAt,timeLabel:fmt(e.occurredAt),evidence:<>{(e.fromStatus||e.toStatus)&&<div>{e.fromStatus?`${e.fromStatus} → `:''}{e.toStatus??''}</div>}{e.note&&<div>{e.note}</div>}</>}))}/></section>}
 </PageShell>
}

const panel={background:'#fff',border:'1px solid #e5e7eb',borderRadius:18,padding:20,boxShadow:'0 8px 24px rgba(15,23,42,.05)'}
const grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(360px,1fr))',gap:18,marginTop:18}
const row={display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,flexWrap:'wrap' as const}
const item={display:'flex',justifyContent:'space-between',gap:12,padding:'13px 0',borderBottom:'1px solid #eef2f7'}
const actions={display:'flex',gap:8,alignItems:'center',flexWrap:'wrap' as const,justifyContent:'flex-end'}
