'use client'

import {FormEvent,useCallback,useEffect,useState} from 'react'

type Session={accessToken:string;role:string;societyName?:string}
type PrivacyCase={id:string;subjectUserId:string;requestType:string;requestSummary:string;status:string;legalHold?:boolean;retentionReason?:string|null;assignedToUserId?:string|null;dueAt?:string|null;createdAt?:string}
type History={id:string;action?:string;status?:string;note?:string|null;occurredAt?:string;actorUserId?:string}
const base=(process.env.NEXT_PUBLIC_AARAGATE_API_BASE_URL??'http://localhost:3000').replace(/\/$/,'')
const readRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','AUDITOR'])
function getSession():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw) as Session:null}catch{return null}}
async function api<T>(s:Session,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${base}/api/v1${path}`,{...init,headers:{Accept:'application/json','Content-Type':'application/json',Authorization:`Bearer ${s.accessToken}`,...init.headers}});const text=await r.text();const body=text?JSON.parse(text):null;if(!r.ok)throw new Error(body?.message??`Request failed (${r.status})`);return body as T}
export default function PrivacyOperationsPage(){
 const s=typeof window==='undefined'?null:getSession(),allowed=!!s&&readRoles.has(s.role),canManage=s?.role==='SUPER_ADMIN'
 const[cases,setCases]=useState<PrivacyCase[]>([]),[selectedId,setSelectedId]=useState(''),[history,setHistory]=useState<History[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const[subjectUserId,setSubjectUserId]=useState(''),[requestType,setRequestType]=useState('ACCESS'),[summary,setSummary]=useState('')
 const selected=cases.find(c=>c.id===selectedId)??null
 const load=useCallback(async()=>{if(!s||!allowed)return;setLoading(true);setError('');try{const rows=await api<PrivacyCase[]>(s,'/privacy/cases');setCases(rows);setSelectedId(current=>current&&rows.some(r=>r.id===current)?current:rows[0]?.id??'')}catch(e){setError(e instanceof Error?e.message:'Privacy cases could not be loaded')}finally{setLoading(false)}},[s?.accessToken,allowed])
 const loadHistory=useCallback(async(id:string)=>{if(!s||!id)return;try{setHistory(await api<History[]>(s,`/privacy/cases/${id}/history`))}catch(e){setError(e instanceof Error?e.message:'Privacy case history could not be loaded')}},[s?.accessToken])
 useEffect(()=>{void load()},[load]);useEffect(()=>{if(selectedId)void loadHistory(selectedId)},[selectedId,loadHistory])
 const run=async(fn:()=>Promise<void>,message:string)=>{setBusy(true);setError('');setSuccess('');try{await fn();setSuccess(message);await load();if(selectedId)await loadHistory(selectedId)}catch(e){setError(e instanceof Error?e.message:'Privacy operation failed')}finally{setBusy(false)}}
 const createCase=(e:FormEvent)=>{e.preventDefault();if(!s||!canManage)return;void run(async()=>{await api(s,'/privacy/cases',{method:'POST',body:JSON.stringify({subjectUserId:subjectUserId.trim(),requestType,requestSummary:summary.trim()})});setSubjectUserId('');setSummary('')},'Privacy request case created.')}
 const setStatus=()=>{if(!s||!canManage||!selected)return;const status=prompt('New status: OPEN, IN_REVIEW, WAITING, COMPLETED, REJECTED or CANCELLED',selected.status);if(!status)return;const note=prompt('Decision / status note (optional)')??'';void run(()=>api(s,`/privacy/cases/${selected.id}/status`,{method:'PATCH',body:JSON.stringify({status:status.trim().toUpperCase(),note:note.trim()||undefined})}).then(()=>undefined),'Privacy case status updated.')}
 const toggleHold=()=>{if(!s||!canManage||!selected)return;const next=!selected.legalHold;const reason=prompt(next?'Retention/legal-hold reason':'Reason for releasing hold (optional)')??'';void run(()=>api(s,`/privacy/cases/${selected.id}/legal-hold`,{method:'PATCH',body:JSON.stringify({legalHold:next,retentionReason:reason.trim()||undefined})}).then(()=>undefined),next?'Legal hold applied.':'Legal hold released.')}
 if(!s||!allowed)return <main style={page}><h1>Privacy operations access required</h1><a href={s?.role==='AUDITOR'?'/audit':'/'}>Return</a></main>
 return <main style={page}><header style={header}><div><small>{s.societyName??'Current society'} · {s.role.replaceAll('_',' ')}</small><h1>Privacy request operations</h1><p>{canManage?'Manage auditable data-access/correction/erasure cases and retention holds.':'Read-only privacy case evidence. Decisions and destructive operations are not available.'}</p></div><a href={s.role==='AUDITOR'?'/audit':'/'}>← Back</a></header>{error&&<p style={err}>{error}</p>}{success&&<p style={ok}>{success}</p>}{canManage&&<form onSubmit={createCase} style={panel}><h2>Create privacy case</h2><div style={grid}><label style={label}>Subject user UUID<input style={input} value={subjectUserId} onChange={e=>setSubjectUserId(e.target.value)} required/></label><label style={label}>Request type<select style={input} value={requestType} onChange={e=>setRequestType(e.target.value)}>{['ACCESS','CORRECTION','ERASURE','OTHER'].map(v=><option key={v}>{v}</option>)}</select></label></div><label style={label}>Request summary<textarea style={input} value={summary} onChange={e=>setSummary(e.target.value)} required maxLength={2000}/></label><button style={primary} disabled={busy}>Create case</button></form>}<div style={layout}><section style={panel}><h2>Cases</h2>{loading?<p>Loading…</p>:cases.length===0?<p>No privacy cases.</p>:cases.map(c=><button key={c.id} onClick={()=>setSelectedId(c.id)} style={{...caseButton,...(c.id===selectedId?selected:{})}}><b>{c.requestType} · {c.status}</b><span>{c.requestSummary}</span><small>Subject {c.subjectUserId.slice(0,8)}…{c.legalHold?' · LEGAL HOLD':''}</small></button>)}</section><section style={panel}>{!selected?<p>Select a case.</p>:<><div style={header}><div><h2 style={{margin:0}}>{selected.requestType}</h2><p>{selected.requestSummary}</p></div><b>{selected.status}</b></div><p>Subject user: <code>{selected.subjectUserId}</code></p><p>Legal hold: <b>{selected.legalHold?'Yes':'No'}</b>{selected.retentionReason?` · ${selected.retentionReason}`:''}</p>{canManage&&<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button style={primary} disabled={busy} onClick={setStatus}>Update status</button><button style={secondary} disabled={busy} onClick={toggleHold}>{selected.legalHold?'Release legal hold':'Apply legal hold'}</button></div>}<h3>History</h3>{history.length===0?<p>No history entries.</p>:history.map((h,i)=><article key={h.id??String(i)} style={historyRow}><b>{h.action??h.status??'CASE_EVENT'}</b><small>{h.occurredAt?new Date(h.occurredAt).toLocaleString('en-IN'):''}</small>{h.note&&<span>{h.note}</span>}</article>)}</>}</section></div></main>
}
const page:React.CSSProperties={maxWidth:1180,margin:'0 auto',padding:'28px 22px 80px'},header:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'},panel:React.CSSProperties={marginTop:18,padding:20,border:'1px solid #dbe7ea',borderRadius:16,background:'white'},grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:12},layout:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,360px),1fr))',gap:18},label:React.CSSProperties={display:'grid',gap:6,marginTop:10,fontWeight:700},input:React.CSSProperties={padding:10,border:'1px solid #cbd5e1',borderRadius:10,font:'inherit'},primary:React.CSSProperties={marginTop:12,padding:'10px 14px',border:0,borderRadius:10,background:'#05879A',color:'white',fontWeight:800},secondary:React.CSSProperties={padding:'9px 12px',border:'1px solid #cbd5e1',borderRadius:10,background:'white',fontWeight:700},caseButton:React.CSSProperties={width:'100%',display:'grid',gap:5,textAlign:'left',padding:12,border:'1px solid #e2e8f0',borderRadius:12,background:'white',marginTop:8},selected:React.CSSProperties={background:'#ecfeff',borderColor:'#67e8f9'},historyRow:React.CSSProperties={display:'grid',gap:4,padding:'9px 0',borderBottom:'1px solid #e2e8f0'},err:React.CSSProperties={padding:12,background:'#fef2f2',color:'#991b1b',borderRadius:10},ok:React.CSSProperties={padding:12,background:'#ecfdf5',color:'#065f46',borderRadius:10}
