'use client'

import { FormEvent, useCallback, useEffect, useState } from 'react'

type Session={accessToken:string;role:string;societyName?:string}
type Amenity={id:string;code:string;name:string;description?:string|null;location?:string|null;feePaise:number;currency:string;requiresApproval:boolean;slotMinutes:number;maxConcurrentBookings:number;active:boolean}
type Booking={id:string;amenityName:string;amenityCode:string;unitNumber:string;buildingName:string;startsAt:string;endsAt:string;status:string;feePaise:number;reviewNote?:string|null}
const base=(process.env.NEXT_PUBLIC_AARAGATE_API_BASE_URL??'http://localhost:3000').replace(/\/$/,'')
function getSession():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw) as Session:null}catch{return null}}
async function api<T>(s:Session,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${base}/api/v1${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.accessToken}`,...init.headers}});const t=await r.text();const b=t?JSON.parse(t):null;if(!r.ok)throw new Error(Array.isArray(b?.message)?b.message.join(', '):b?.message??`Request failed (${r.status})`);return b as T}
const allowedRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','FACILITY_MANAGER'])

export default function AmenitiesAdminPage(){
  const[session,setSession]=useState<Session|null>(null),[amenities,setAmenities]=useState<Amenity[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const[code,setCode]=useState(''),[name,setName]=useState(''),[location,setLocation]=useState(''),[description,setDescription]=useState(''),[fee,setFee]=useState('0'),[slotMinutes,setSlotMinutes]=useState('60'),[capacity,setCapacity]=useState('1'),[requiresApproval,setRequiresApproval]=useState(false)
  const allowed=(s:Session|null)=>!!s&&allowedRoles.has(s.role)
  const load=useCallback(async(s:Session)=>{setLoading(true);setError('');try{const[a,b]=await Promise.all([api<Amenity[]>(s,'/amenities/manage'),api<Booking[]>(s,'/amenities/manage/bookings')]);setAmenities(a);setBookings(b)}catch(e){setError(e instanceof Error?e.message:'Could not load amenities')}finally{setLoading(false)}},[])
  useEffect(()=>{const s=getSession();setSession(s);if(s&&allowed(s))void load(s);else setLoading(false)},[load])

  const createAmenity=async(e:FormEvent)=>{e.preventDefault();if(!session)return;setBusy(true);setError('');try{const rupees=Number(fee),slot=Number(slotMinutes),max=Number(capacity);if(!Number.isFinite(rupees)||rupees<0)throw new Error('Fee must be zero or more');if(!Number.isInteger(slot)||slot<15)throw new Error('Slot length must be at least 15 minutes');if(!Number.isInteger(max)||max<1)throw new Error('Concurrent capacity must be at least 1');await api(session,'/amenities/manage',{method:'POST',body:JSON.stringify({code:code.trim(),name:name.trim(),location:location.trim()||undefined,description:description.trim()||undefined,feePaise:Math.round(rupees*100),requiresApproval,slotMinutes:slot,maxConcurrentBookings:max})});setCode('');setName('');setLocation('');setDescription('');setFee('0');setSlotMinutes('60');setCapacity('1');setRequiresApproval(false);await load(session)}catch(e){setError(e instanceof Error?e.message:'Could not create amenity')}finally{setBusy(false)}}
  const saveAmenity=async(a:Amenity,patch:Partial<Amenity>)=>{if(!session)return;setBusy(true);setError('');try{await api(session,`/amenities/manage/${a.id}`,{method:'PATCH',body:JSON.stringify({name:patch.name??a.name,description:patch.description??a.description??'',location:patch.location??a.location??'',feePaise:patch.feePaise??a.feePaise,requiresApproval:patch.requiresApproval??a.requiresApproval,slotMinutes:patch.slotMinutes??a.slotMinutes,maxConcurrentBookings:patch.maxConcurrentBookings??a.maxConcurrentBookings,active:patch.active??a.active})});await load(session)}catch(e){setError(e instanceof Error?e.message:'Could not update amenity')}finally{setBusy(false)}}
  const editAmenity=async(a:Amenity)=>{const nextName=prompt('Amenity name',a.name);if(nextName===null)return;const nextLocation=prompt('Location',a.location??'');if(nextLocation===null)return;const nextFee=prompt('Fee in rupees',(a.feePaise/100).toString());if(nextFee===null)return;const nextSlot=prompt('Slot length in minutes',a.slotMinutes.toString());if(nextSlot===null)return;const nextCapacity=prompt('Concurrent capacity',a.maxConcurrentBookings.toString());if(nextCapacity===null)return;const rupees=Number(nextFee),slot=Number(nextSlot),max=Number(nextCapacity);if(!nextName.trim()||!Number.isFinite(rupees)||rupees<0||!Number.isInteger(slot)||slot<15||!Number.isInteger(max)||max<1){setError('Enter a valid name, non-negative fee, slot length of at least 15 minutes and capacity of at least 1.');return}await saveAmenity(a,{name:nextName.trim(),location:nextLocation.trim(),feePaise:Math.round(rupees*100),slotMinutes:slot,maxConcurrentBookings:max})}
  const toggleAmenity=async(a:Amenity)=>{const action=a.active?'deactivate':'reactivate';if(!confirm(`${action[0].toUpperCase()}${action.slice(1)} ${a.name}?`))return;await saveAmenity(a,{active:!a.active})}
  const review=async(booking:Booking,decision:'approve'|'reject')=>{if(!session)return;const note=prompt(`${decision==='approve'?'Approve':'Reject'} ${booking.amenityName} booking for ${booking.buildingName} ${booking.unitNumber}. Optional note:`,'');if(note===null)return;setBusy(true);setError('');try{await api(session,`/amenities/manage/bookings/${booking.id}/${decision}`,{method:'PATCH',body:JSON.stringify({note:note.trim()||undefined})});await load(session)}catch(e){setError(e instanceof Error?e.message:`Could not ${decision} booking`)}finally{setBusy(false)}}

  if(loading)return <main style={{padding:32}}>Loading amenities…</main>
  if(!allowed(session))return <main style={{padding:32}}><h1>Facility management access required</h1><p>A Society Admin or Facility Manager role is required.</p><a href="/">Return to Admin</a></main>
  const pending=bookings.filter(b=>b.status==='PENDING')
  return <main style={{maxWidth:1160,margin:'0 auto',padding:'28px 22px 80px'}}>
    <header style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><small>{session?.societyName??'Current society'}</small><h1 style={{margin:'4px 0'}}>Amenities & facility bookings</h1><p style={{margin:0}}>Configure bookable facilities and review resident requests.</p></div><a href="/">← Admin console</a></header>
    {error&&<div style={errorBox}>{error}</div>}
    <section style={panel}><h2 style={{marginTop:0}}>Add amenity</h2><form onSubmit={createAmenity} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12}}>
      <label>Code<input required value={code} onChange={e=>setCode(e.target.value)} placeholder="CLUBHOUSE" style={input}/></label>
      <label>Name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Clubhouse" style={input}/></label>
      <label>Location<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Ground floor" style={input}/></label>
      <label>Fee (₹)<input type="number" min="0" step="0.01" value={fee} onChange={e=>setFee(e.target.value)} style={input}/></label>
      <label>Slot minutes<input type="number" min="15" max="1440" value={slotMinutes} onChange={e=>setSlotMinutes(e.target.value)} style={input}/></label>
      <label>Concurrent capacity<input type="number" min="1" max="100" value={capacity} onChange={e=>setCapacity(e.target.value)} style={input}/></label>
      <label style={{gridColumn:'1/-1'}}>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={2} style={{...input,resize:'vertical'}}/></label>
      <label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" checked={requiresApproval} onChange={e=>setRequiresApproval(e.target.checked)}/> Require admin approval</label>
      <div><button disabled={busy||!code.trim()||!name.trim()} style={primary}>{busy?'Saving…':'Create amenity'}</button></div>
    </form></section>
    <section style={panel}><h2 style={{marginTop:0}}>Configured amenities</h2>{amenities.length===0?<p>No amenities configured yet.</p>:<div style={{display:'grid',gap:10}}>{amenities.map(a=><article key={a.id} style={{...card,opacity:a.active?1:.62}}><div><b style={{fontSize:17}}>{a.name}</b><div><small>{a.code}{a.location?` · ${a.location}`:''} · {a.active?'Active':'Inactive'}</small></div></div><div style={{display:'flex',gap:12,alignItems:'center',flexWrap:'wrap'}}><div style={{textAlign:'right'}}><b>{a.feePaise>0?`₹${(a.feePaise/100).toFixed(a.feePaise%100===0?0:2)}`:'Free'}</b><div><small>{a.slotMinutes} min · capacity {a.maxConcurrentBookings} · {a.requiresApproval?'approval':'instant'}</small></div></div><button disabled={busy} onClick={()=>void editAmenity(a)} style={secondary}>Edit</button><button disabled={busy} onClick={()=>void toggleAmenity(a)} style={a.active?danger:primary}>{a.active?'Deactivate':'Reactivate'}</button></div></article>)}</div>}</section>
    <section style={panel}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><h2 style={{margin:'0 0 4px'}}>Pending approvals</h2><small>{pending.length} request{pending.length===1?'':'s'} awaiting review</small></div><button disabled={busy} onClick={()=>session&&void load(session)} style={secondary}>Refresh</button></div><div style={{display:'grid',gap:10,marginTop:16}}>{pending.length===0?<p>No pending amenity requests.</p>:pending.map(b=><article key={b.id} style={card}><div><b>{b.amenityName}</b><div>{b.buildingName} · Unit {b.unitNumber}</div><small>{new Date(b.startsAt).toLocaleString()} · {b.feePaise>0?`₹${(b.feePaise/100).toFixed(b.feePaise%100===0?0:2)}`:'Free'}</small></div><div style={{display:'flex',gap:8}}><button disabled={busy} onClick={()=>void review(b,'reject')} style={danger}>Reject</button><button disabled={busy} onClick={()=>void review(b,'approve')} style={primary}>Approve</button></div></article>)}</div></section>
    <section style={panel}><h2 style={{marginTop:0}}>Recent booking activity</h2>{bookings.length===0?<p>No bookings yet.</p>:<div style={{display:'grid',gap:8}}>{bookings.slice(0,20).map(b=><div key={b.id} style={{...card,padding:12}}><div><b>{b.amenityName}</b> · {b.buildingName} {b.unitNumber}<div><small>{new Date(b.startsAt).toLocaleString()}</small></div></div><b>{b.status.replaceAll('_',' ')}</b></div>)}</div>}</section>
  </main>
}
const panel:React.CSSProperties={marginTop:20,padding:20,border:'1px solid #dbe7ea',borderRadius:16,background:'white'}
const card:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',padding:14,border:'1px solid #e5e7eb',borderRadius:12,flexWrap:'wrap'}
const input:React.CSSProperties={display:'block',width:'100%',boxSizing:'border-box',marginTop:6,padding:10,border:'1px solid #cbd5e1',borderRadius:10,font: 'inherit'}
const primary:React.CSSProperties={padding:'10px 14px',borderRadius:10,border:'1px solid #05879A',background:'#05879A',color:'white',fontWeight:700,cursor:'pointer'}
const secondary:React.CSSProperties={padding:'9px 13px',borderRadius:10,border:'1px solid #94a3b8',background:'white',fontWeight:700,cursor:'pointer'}
const danger:React.CSSProperties={padding:'10px 14px',borderRadius:10,border:'1px solid #dc2626',background:'white',color:'#b91c1c',fontWeight:700,cursor:'pointer'}
const errorBox:React.CSSProperties={marginTop:18,padding:12,border:'1px solid #ef4444',borderRadius:10,background:'#fff7f7'}
