'use client'

import { FormEvent,useEffect,useMemo,useState } from 'react'

type Session={accessToken:string;role:string;societyName?:string}
type Task={id:string;category:'HOUSEKEEPING'|'STAFF';title:string;location?:string|null;scheduledAt?:string|null;dueAt?:string|null;assignedUserId?:string|null;assignedUserName?:string|null;status:'OPEN'|'IN_PROGRESS'|'COMPLETED'|'CANCELLED';completionNote?:string|null;completedAt?:string|null;createdAt:string}
const base=(process.env.NEXT_PUBLIC_AARAGATE_API_BASE_URL??'http://localhost:3000').replace(/\/$/,'')
const readRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','FACILITY_MANAGER','COMMITTEE_MEMBER'])
const manageRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','FACILITY_MANAGER'])
function getSession():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw):null}catch{return null}}
async function api<T>(s:Session,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${base}/api/v1${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.accessToken}`,...init.headers}});const text=await r.text(),body=text?JSON.parse(text):null;if(!r.ok)throw new Error(Array.isArray(body?.message)?body.message.join(', '):body?.message??`Request failed (${r.status})`);return body as T}
const fmt=(v?:string|null)=>v?new Date(v).toLocaleString('en-IN'):'—'
const iso=(v:string)=>v?new Date(v).toISOString():undefined
export default function FacilitiesOperationsPage(){
 const s=typeof window==='undefined'?null:getSession(),canRead=!!s&&readRoles.has(s.role),canManage=!!s&&manageRoles.has(s.role)
 const[tasks,setTasks]=useState<Task[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const[category,setCategory]=useState<Task['category']>('HOUSEKEEPING'),[title,setTitle]=useState(''),[location,setLocation]=useState(''),[scheduledAt,setScheduledAt]=useState(''),[dueAt,setDueAt]=useState(''),[assignedUserId,setAssignedUserId]=useState('')
 const active=useMemo(()=>tasks.filter(t=>t.status==='OPEN'||t.status==='IN_PROGRESS').length,[tasks])
 const overdue=useMemo(()=>tasks.filter(t=>(t.status==='OPEN'||t.status==='IN_PROGRESS')&&t.dueAt&&new Date(t.dueAt)<new Date()).length,[tasks])
 async function load(){if(!s||!canRead)return;setBusy(true);setError('');try{setTasks(await api<Task[]>(s,'/facilities/operations'))}catch(e){setError(e instanceof Error?e.message:'Could not load operations tasks')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 async function createTask(e:FormEvent){e.preventDefault();if(!s||!canManage)return;setBusy(true);setError('');try{await api(s,'/facilities/operations',{method:'POST',body:JSON.stringify({category,title:title.trim(),location:location.trim()||undefined,scheduledAt:iso(scheduledAt),dueAt:iso(dueAt),assignedUserId:assignedUserId.trim()||undefined})});setTitle('');setLocation('');setScheduledAt('');setDueAt('');setAssignedUserId('');await load()}catch(e){setError(e instanceof Error?e.message:'Could not create task')}finally{setBusy(false)}}
 async function transition(task:Task,status:'IN_PROGRESS'|'COMPLETED'|'CANCELLED'){if(!s||!canManage)return;const completionNote=status==='COMPLETED'?(prompt('Completion note (required):')?.trim()??''):undefined;if(status==='COMPLETED'&&(completionNote?.length??0)<5){setError('Completion note must be at least 5 characters');return}setBusy(true);setError('');try{await api(s,`/facilities/operations/${task.id}/status`,{method:'POST',body:JSON.stringify({status,completionNote})});await load()}catch(e){setError(e instanceof Error?e.message:'Could not update task')}finally{setBusy(false)}}
 if(!s||!canRead)return <main style={{padding:32}}><h1>Facilities operations access required</h1><a href="/facilities">Return to Facilities</a></main>
 return <main style={{maxWidth:1180,margin:'0 auto',padding:'28px 22px 80px'}}><header><small>{s.societyName??'Current society'} · {s.role.replaceAll('_',' ')}</small><h1>Housekeeping & staff tasks</h1><p>Schedule recurring operational work and keep completion evidence visible to facility managers.</p><a href="/facilities">← Facilities operations</a></header>{error&&<p style={errorBox}>{error}</p>}<section style={grid}><div style={panel}><h2>Operations summary</h2><div style={stats}><div><b>{tasks.length}</b><span>Total tasks</span></div><div><b>{active}</b><span>Active</span></div><div><b>{overdue}</b><span>Overdue</span></div></div></div>{canManage&&<form onSubmit={createTask} style={panel}><h2>Create task</h2><label>Category<select value={category} onChange={e=>setCategory(e.target.value as Task['category'])} style={input}><option value="HOUSEKEEPING">Housekeeping</option><option value="STAFF">Staff</option></select></label><label>Title<input required value={title} onChange={e=>setTitle(e.target.value)} style={input}/></label><label>Location<input value={location} onChange={e=>setLocation(e.target.value)} style={input} placeholder="Clubhouse, Tower A lobby…"/></label><label>Scheduled at<input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)} style={input}/></label><label>Due at<input type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)} style={input}/></label><label>Assigned user ID<input value={assignedUserId} onChange={e=>setAssignedUserId(e.target.value)} style={input} placeholder="Optional active society member UUID"/></label><button disabled={busy} style={button}>Create task</button></form>}</section><section style={panelSection}><div style={row}><h2 style={{margin:0}}>Task board</h2><button disabled={busy} onClick={()=>void load()} style={secondary}>Reload</button></div>{tasks.length===0?<p>No operational tasks yet.</p>:tasks.map(task=><div key={task.id} style={item}><span><b>{task.category} · {task.title}</b><br/><small>{task.status}{task.location?` · ${task.location}`:''}</small><br/><small>Scheduled {fmt(task.scheduledAt)} · due {fmt(task.dueAt)}</small>{task.assignedUserName||task.assignedUserId?<><br/><small>Assigned: {task.assignedUserName??task.assignedUserId}</small></>:null}{task.completionNote?<><br/><small>Completion: {task.completionNote}</small></>:null}</span>{canManage&&(task.status==='OPEN'||task.status==='IN_PROGRESS')&&<span style={actions}>{task.status==='OPEN'&&<button disabled={busy} onClick={()=>void transition(task,'IN_PROGRESS')} style={secondary}>Start</button>}<button disabled={busy} onClick={()=>void transition(task,'COMPLETED')} style={button}>Complete</button><button disabled={busy} onClick={()=>void transition(task,'CANCELLED')} style={secondary}>Cancel</button></span>}</div>)}</section></main>
}
const panel={background:'#fff',border:'1px solid #e5e7eb',borderRadius:18,padding:20,boxShadow:'0 8px 24px rgba(15,23,42,.05)'}
const panelSection={...panel,marginTop:18}
const grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(360px,1fr))',gap:18,marginTop:18}
const row={display:'flex',alignItems:'center',justifyContent:'space-between',gap:12}
const input={display:'block',width:'100%',boxSizing:'border-box' as const,padding:'10px 12px',margin:'6px 0 12px',border:'1px solid #cbd5e1',borderRadius:10,background:'#fff'}
const button={border:0,borderRadius:10,padding:'10px 14px',background:'#05879A',color:'#fff',fontWeight:700,cursor:'pointer'}
const secondary={border:'1px solid #cbd5e1',borderRadius:10,padding:'9px 12px',background:'#fff',fontWeight:700,cursor:'pointer'}
const item={display:'flex',justifyContent:'space-between',gap:12,padding:'13px 0',borderBottom:'1px solid #eef2f7'}
const actions={display:'flex',gap:8,alignItems:'center',flexWrap:'wrap' as const,justifyContent:'flex-end'}
const stats={display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10}
const errorBox={background:'#fff1f2',border:'1px solid #fecdd3',padding:12,borderRadius:10,color:'#9f1239'}
