'use client'

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { operatorConfirm } from '../../lib/operator-dialog'
import { api, type Session } from '../../lib/admin-client'

type Society={id:string;name:string;code:string;status:'ACTIVE'|'SUSPENDED';productTier:'STARTER'|'PROFESSIONAL'|'PREMIUM'|'ENTERPRISE';featureOverrides:Record<string,boolean>;_count:{memberships:number;buildings:number;gates:number}}
type AdminMembership={id:string;userId:string;active:boolean;user:{name?:string|null;phone:string;email?:string|null;status:string}}
type PortfolioSociety={societyId:string;societyName:string;societyCode:string;societyStatus:string;productTier:string;attentionLevel:'CRITICAL'|'HIGH'|'WATCH'|'NORMAL';reasons:string[];openHelpdesk:number;breachedHelpdesk:number;pendingGateApprovals:number;activeSos:number;criticalFacilityWork:number;overdueFacilityWork:number;overdueInvoices:number;activeResidents:number}
type PortfolioCommand={generatedAt:string;summary:{societies:number;active:number;critical:number;high:number;watch:number};societies:PortfolioSociety[];predictive:false;mutationPerformed:false;boundary:string}
const tiers=['STARTER','PROFESSIONAL','PREMIUM','ENTERPRISE'] as const
const features=['VISITOR_MANAGEMENT','DELIVERY_MANAGEMENT','DOMESTIC_HELP','NOTICES','HELPDESK','SOS','HOUSEHOLD_SERVICES','MAINTENANCE_BILLING','PAYMENTS','AMENITIES','GOVERNANCE_POLLS','ADVANCED_REPORTS','WHATSAPP_AUTOMATION','AI_ASSISTANT','CUSTOM_INTEGRATIONS'] as const

function getSession():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw) as Session:null}catch{return null}}

export default function PlatformPage(){
  const[session,setSession]=useState<Session|null>(null),[societies,setSocieties]=useState<Society[]>([]),[portfolio,setPortfolio]=useState<PortfolioCommand|null>(null),[selected,setSelected]=useState(''),[admins,setAdmins]=useState<AdminMembership[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const[phone,setPhone]=useState('+91'),[name,setName]=useState('')
  const current=useMemo(()=>societies.find(s=>s.id===selected),[societies,selected])
  const currentAttention=useMemo(()=>portfolio?.societies.find(s=>s.societyId===selected)??null,[portfolio,selected])
  const load=useCallback(async(s:Session)=>{setLoading(true);setError('');try{const[rows,command]=await Promise.all([api<Society[]>('/platform/societies',{},s),api<PortfolioCommand>('/platform/analytics/portfolio-command-centre',{},s)]);setSocieties(rows);setPortfolio(command);setSelected(v=>v||rows[0]?.id||'')}catch(e){setError(e instanceof Error?e.message:'Could not load platform societies')}finally{setLoading(false)}},[])
  const loadAdmins=useCallback(async(s:Session,societyId:string)=>{if(!societyId){setAdmins([]);return}try{setAdmins(await api<AdminMembership[]>(`/platform/societies/${societyId}/admins`,{},s))}catch(e){setError(e instanceof Error?e.message:'Could not load society admins')}},[])
  useEffect(()=>{const s=getSession();setSession(s);if(s?.role==='SUPER_ADMIN')void load(s);else setLoading(false)},[load])
  useEffect(()=>{if(session?.role==='SUPER_ADMIN'&&selected)void loadAdmins(session,selected)},[session,selected,loadAdmins])
  const mutate=async(fn:()=>Promise<unknown>)=>{if(!session)return;setBusy(true);setError('');try{await fn();await load(session);if(selected)await loadAdmins(session,selected)}catch(e){setError(e instanceof Error?e.message:'Platform update failed')}finally{setBusy(false)}}
  if(loading)return <main style={{padding:32}}>Loading platform operations…</main>
  if(!session||session.role!=='SUPER_ADMIN')return <main style={{padding:32}}><h1>Platform access required</h1><p>This surface is restricted to Super Admin.</p><a href="/">Return to Admin</a></main>
  const changeTier=(tier:Society['productTier'])=>current&&mutate(()=>api(`/platform/societies/${current.id}/entitlements`,{method:'PATCH',body:JSON.stringify({productTier:tier})},session))
  const setOverride=(feature:string,value:'INHERIT'|'ON'|'OFF')=>{if(!current)return;const overrides={...(current.featureOverrides??{})};if(value==='INHERIT')delete overrides[feature];else overrides[feature]=value==='ON';void mutate(()=>api(`/platform/societies/${current.id}/entitlements`,{method:'PATCH',body:JSON.stringify({featureOverrides:overrides})},session))}
  const toggleStatus=()=>current&&mutate(()=>api(`/platform/societies/${current.id}/status`,{method:'PATCH',body:JSON.stringify({status:current.status==='ACTIVE'?'SUSPENDED':'ACTIVE'})},session))
  const provision=(e:FormEvent)=>{e.preventDefault();if(!current)return;void mutate(async()=>{await api(`/platform/societies/${current.id}/admins/provision`,{method:'POST',body:JSON.stringify({phone:phone.trim(),name:name.trim()})},session);setPhone('+91');setName('')})}
  const deactivate=async(userId:string)=>current&&await operatorConfirm('Deactivate this Society Admin and revoke active sessions?')&&mutate(()=>api(`/platform/societies/${current.id}/admins/${userId}/deactivate`,{method:'PATCH',body:'{}'},session))
  return <main style={{maxWidth:1180,margin:'0 auto',padding:'28px 22px 80px'}}>
    <div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><small>SUPER ADMIN</small><h1 style={{margin:'4px 0'}}>Aaraagate platform</h1><p style={{margin:0}}>Society lifecycle, SaaS plans, feature overrides and Society Admin provisioning.</p></div><a href="/">← Admin console</a></div>
    {error&&<div style={{marginTop:18,padding:12,border:'1px solid #ef4444',borderRadius:10}}>{error}</div>}
    {portfolio&&<section style={panel}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap',alignItems:'baseline'}}><div><h2 style={{margin:'0 0 4px'}}>Portfolio command centre</h2><small>Deterministic current-state attention · no predictive score</small></div><small>{new Date(portfolio.generatedAt).toLocaleString('en-IN')}</small></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(140px,1fr))',gap:10,marginTop:16}}><Metric label="Societies" value={portfolio.summary.societies}/><Metric label="Critical" value={portfolio.summary.critical}/><Metric label="High" value={portfolio.summary.high}/><Metric label="Watch" value={portfolio.summary.watch}/></div><div style={{display:'grid',gap:8,marginTop:16}}>{portfolio.societies.map(row=><button key={row.societyId} onClick={()=>setSelected(row.societyId)} style={{...button,textAlign:'left',display:'grid',gridTemplateColumns:'minmax(180px,1fr) auto',gap:12,alignItems:'center',borderColor:row.attentionLevel==='CRITICAL'?'#dc2626':row.attentionLevel==='HIGH'?'#d97706':'#cbd5e1'}}><span><b>{row.societyName}</b><small style={{display:'block',marginTop:3}}>{row.openHelpdesk} open helpdesk · {row.pendingGateApprovals} gate pending · {row.overdueInvoices} overdue invoices</small>{row.reasons.length>0&&<small style={{display:'block',marginTop:3}}>Why: {row.reasons.map(humanReason).join(' · ')}</small>}</span><strong>{row.attentionLevel}</strong></button>)}</div><p style={{marginBottom:0}}><small>{portfolio.boundary}</small></p></section>}
    <section style={{marginTop:24,padding:20,border:'1px solid #dbe7ea',borderRadius:16,background:'white'}}><label style={{display:'grid',gap:8,maxWidth:560}}>Society<select value={selected} onChange={e=>setSelected(e.target.value)} style={{padding:12,borderRadius:10}}>{societies.map(s=><option key={s.id} value={s.id}>{s.name} · {s.code}</option>)}</select></label>{current&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,marginTop:18}}><Metric label="Status" value={current.status}/><Metric label="Plan" value={current.productTier}/><Metric label="Members" value={current._count.memberships}/><Metric label="Buildings" value={current._count.buildings}/><Metric label="Gates" value={current._count.gates}/></div>}{currentAttention&&currentAttention.reasons.length>0&&<div style={{marginTop:16,paddingTop:14,borderTop:'1px solid #e5e7eb'}}><b>Attention evidence</b><ul>{currentAttention.reasons.map(reason=><li key={reason}>{humanReason(reason)} — {reasonGuidance(reason)}</li>)}</ul><small>Open the owning society workflow only after switching the active society context. This platform surface does not mutate tenant operations.</small></div>}</section>
    {current&&<><section style={panel}><h2>Plan & entitlement controls</h2><div style={{display:'flex',gap:10,flexWrap:'wrap',alignItems:'end'}}><label style={{display:'grid',gap:6}}>Product tier<select disabled={busy} value={current.productTier} onChange={e=>void changeTier(e.target.value as Society['productTier'])} style={{padding:10,borderRadius:10}}>{tiers.map(t=><option key={t}>{t}</option>)}</select></label><button disabled={busy} onClick={toggleStatus} style={button}>{current.status==='ACTIVE'?'Suspend society':'Reactivate society'}</button></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:10,marginTop:18}}>{features.map(feature=>{const inherited=current.featureOverrides?.[feature]===undefined;const value=inherited?'INHERIT':current.featureOverrides[feature]?'ON':'OFF';return <label key={feature} style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',padding:10,border:'1px solid #e5e7eb',borderRadius:10}}><span>{feature.replaceAll('_',' ')}</span><select disabled={busy} value={value} onChange={e=>setOverride(feature,e.target.value as 'INHERIT'|'ON'|'OFF')}><option value="INHERIT">Inherit tier</option><option value="ON">Force on</option><option value="OFF">Force off</option></select></label>})}</div></section>
    <section style={panel}><h2>Society administrators</h2><form onSubmit={provision} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10,alignItems:'end'}}><label style={{display:'grid',gap:6}}>Name<input value={name} onChange={e=>setName(e.target.value)} required style={input}/></label><label style={{display:'grid',gap:6}}>Mobile<input value={phone} onChange={e=>setPhone(e.target.value)} required style={input}/></label><button disabled={busy} style={primary}>{busy?'Saving…':'Provision Society Admin'}</button></form><div style={{marginTop:16,display:'grid',gap:10}}>{admins.length===0?<p>No active Society Admins.</p>:admins.map(a=><article key={a.id} style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',padding:12,border:'1px solid #e5e7eb',borderRadius:12}}><div><b>{a.user.name||'Unnamed user'}</b><div>{a.user.phone}{a.user.email?` · ${a.user.email}`:''}</div></div><button disabled={busy} onClick={()=>deactivate(a.userId)} style={button}>Deactivate</button></article>)}</div></section></>}
  </main>
}

const panel:React.CSSProperties={marginTop:20,padding:20,border:'1px solid #dbe7ea',borderRadius:16,background:'white'}
const input:React.CSSProperties={padding:11,border:'1px solid #cbd5e1',borderRadius:10}
const button:React.CSSProperties={padding:'10px 14px',borderRadius:10,border:'1px solid #cbd5e1',background:'white',fontWeight:700}
const primary:React.CSSProperties={...button,background:'#05879A',color:'white',borderColor:'#05879A'}
function humanReason(value:string){return value.replaceAll('_',' ').toLowerCase().replace(/^./,c=>c.toUpperCase())}
function reasonGuidance(reason:string){switch(reason){case 'ACTIVE_SOS':return 'Review Emergency Operations immediately.';case 'CRITICAL_FACILITY_WORK':case 'OVERDUE_FACILITY_WORK':return 'Review Facilities work orders and ownership.';case 'HELPDESK_SLA_BREACH':return 'Review Helpdesk SLA recovery and assignment.';case 'OVERDUE_MAINTENANCE':return 'Review Finance receivables and collection exceptions.';case 'PENDING_GATE_APPROVALS':return 'Review Gate approval queue and occupant authority.';default:return 'Review the owning operational domain.'}}
function Metric({label,value}:{label:string;value:string|number}){return <div style={{padding:12,border:'1px solid #e5e7eb',borderRadius:12}}><small>{label}</small><div style={{fontSize:22,fontWeight:800,marginTop:4}}>{value}</div></div>}
