'use client'

import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react'

type Session={accessToken:string;role:string;societyName?:string}
type FinancePo={id:string;requestId:string;poNumber:string;amountPaise:string;status:string;issuedAt:string;requestNumber:string;requestTitle:string;vendorCode:string;vendorName:string;expenseId?:string|null;expenseNumber?:string|null;expenseStatus?:string|null;linkedAt?:string|null}
type Account={id:string;code:string;name:string;type:string;active:boolean}
type Fund={id:string;code:string;name:string;netPaise:string}

const base=(process.env.NEXT_PUBLIC_AARAGATE_API_BASE_URL??'http://localhost:3000').replace(/\/$/,'')
const readRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','COMMITTEE_MEMBER','ACCOUNTANT','AUDITOR'])
const manageRoles=new Set(['SUPER_ADMIN','ACCOUNTANT'])
function session():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw) as Session:null}catch{return null}}
async function api<T>(s:Session,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${base}/api/v1${path}`,{...init,headers:{Accept:'application/json','Content-Type':'application/json',Authorization:`Bearer ${s.accessToken}`,...init.headers}});const text=await r.text();const body=text?JSON.parse(text):null;if(!r.ok)throw new Error(body?.message??`Request failed (${r.status})`);return body as T}
const money=(v:string|number)=>`₹${(Number(v)/100).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`

export default function ProcurementFinancePage(){
 const s=typeof window==='undefined'?null:session(),allowed=!!s&&readRoles.has(s.role),canManage=!!s&&manageRoles.has(s.role)
 const[pos,setPos]=useState<FinancePo[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[funds,setFunds]=useState<Fund[]>([])
 const[selectedId,setSelectedId]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const[expenseNumber,setExpenseNumber]=useState(''),[expenseDate,setExpenseDate]=useState(new Date().toISOString().slice(0,10)),[dueDate,setDueDate]=useState(''),[invoiceReference,setInvoiceReference]=useState(''),[description,setDescription]=useState(''),[expenseAccountId,setExpenseAccountId]=useState(''),[fundId,setFundId]=useState('')
 const selected=useMemo(()=>pos.find(p=>p.id===selectedId)??null,[pos,selectedId])
 const expenseAccounts=useMemo(()=>accounts.filter(a=>a.active&&a.type==='EXPENSE'),[accounts])
 const load=useCallback(async()=>{if(!s||!allowed)return;setLoading(true);setError('');try{const[p,a,f]=await Promise.all([api<FinancePo[]>(s,'/vendors/procurement/accounting/purchase-orders'),api<Account[]>(s,'/accounting/accounts'),api<Fund[]>(s,'/accounting/finance-operations/fund-utilization')]);setPos(p);setAccounts(a);setFunds(f);setSelectedId(current=>current&&p.some(x=>x.id===current)?current:(p.find(x=>!x.expenseId)?.id??p[0]?.id??''))}catch(e){setError(e instanceof Error?e.message:'Procurement finance handoff could not be loaded')}finally{setLoading(false)}},[s?.accessToken,allowed])
 useEffect(()=>{void load()},[load])
 useEffect(()=>{if(selected){setInvoiceReference(selected.poNumber);setDescription(`Purchase order ${selected.poNumber} · ${selected.vendorName}`) }},[selectedId])
 const createExpense=(e:FormEvent)=>{e.preventDefault();if(!s||!canManage||!selected||selected.expenseId)return;setBusy(true);setError('');setSuccess('');void api(s,`/vendors/procurement/accounting/purchase-orders/${selected.id}/expense-draft`,{method:'POST',body:JSON.stringify({expenseNumber:expenseNumber.trim(),expenseDate,dueDate:dueDate||undefined,description:description.trim()||undefined,expenseAccountId,fundId:fundId||undefined,invoiceReference:invoiceReference.trim()||undefined})}).then(()=>{setSuccess('Accounting expense draft created from purchase order.');setExpenseNumber('');setDueDate('');setFundId('');return load()}).catch(e=>setError(e instanceof Error?e.message:'Expense draft could not be created')).finally(()=>setBusy(false))}
 if(!s||!allowed)return <main style={page}><h1>Finance access required</h1><a href="/">Return</a></main>
 return <main style={page}><header style={header}><div><small>{s.societyName??'Current society'} · {s.role.replaceAll('_',' ')}</small><h1>Procurement accounting handoff</h1><p>Review issued purchase orders and create the existing accounting expense draft without granting vendor-management access to finance roles.</p></div><a href="/finance/operations">Finance operations →</a></header>
 {error&&<p style={err}>{error}</p>}{success&&<p style={ok}>{success}</p>}
 <section style={panel}><div style={metrics}><div><small>Issued POs</small><b>{pos.length}</b></div><div><small>Awaiting accounting</small><b>{pos.filter(p=>!p.expenseId).length}</b></div><div><small>Linked</small><b>{pos.filter(p=>!!p.expenseId).length}</b></div></div></section>
 <section style={panel}><h2>Purchase orders</h2>{loading?<p>Loading…</p>:pos.length===0?<p>No issued purchase orders.</p>:<div style={list}>{pos.map(p=><article key={p.id} style={{...row,background:p.id===selectedId?'#f0fbfd':'white'}}><div style={stack}><b>{p.poNumber} · {p.vendorName}</b><span>{p.requestNumber} · {p.requestTitle}</span><small>{money(p.amountPaise)} · issued {new Date(p.issuedAt).toLocaleString('en-IN')}</small><small>{p.expenseId?`Linked to ${p.expenseNumber} · ${p.expenseStatus}`:'Awaiting accounting expense draft'}</small></div><button style={secondary} onClick={()=>setSelectedId(p.id)}>{p.id===selectedId?'Selected':'Review'}</button></article>)}</div>}</section>
 {selected&&<section style={panel}><h2>{selected.poNumber} finance evidence</h2><div style={stack}><span><b>Vendor:</b> {selected.vendorCode} · {selected.vendorName}</span><span><b>Procurement request:</b> {selected.requestNumber} · {selected.requestTitle}</span><span><b>PO amount:</b> {money(selected.amountPaise)}</span>{selected.expenseId&&<span><b>Accounting link:</b> {selected.expenseNumber} · {selected.expenseStatus} · linked {selected.linkedAt?new Date(selected.linkedAt).toLocaleString('en-IN'):'—'}</span>}</div>
 {!selected.expenseId&&canManage&&<form onSubmit={createExpense} style={form}><h3>Create expense draft</h3><p style={muted}>This creates a DRAFT SocietyExpense for the exact PO amount. Existing finance approval/posting controls remain unchanged.</p><label style={label}>Expense number<input style={input} value={expenseNumber} onChange={e=>setExpenseNumber(e.target.value)} required maxLength={64}/></label><div style={grid}><label style={label}>Expense date<input style={input} type="date" value={expenseDate} onChange={e=>setExpenseDate(e.target.value)} required/></label><label style={label}>Due date<input style={input} type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label></div><label style={label}>Expense account<select style={input} value={expenseAccountId} onChange={e=>setExpenseAccountId(e.target.value)} required><option value="">Select expense account</option>{expenseAccounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label><label style={label}>Fund (optional)<select style={input} value={fundId} onChange={e=>setFundId(e.target.value)}><option value="">No fund</option>{funds.map(f=><option key={f.id} value={f.id}>{f.code} · {f.name}</option>)}</select></label><label style={label}>Invoice / reference<input style={input} value={invoiceReference} onChange={e=>setInvoiceReference(e.target.value)} maxLength={160}/></label><label style={label}>Description<textarea style={input} value={description} onChange={e=>setDescription(e.target.value)} maxLength={2000}/></label><button style={primary} disabled={busy||!expenseAccountId}>{busy?'Creating…':'Create expense draft'}</button></form>}
 {!selected.expenseId&&!canManage&&<p style={muted}>Read only. FINANCE_MANAGE permission is required to create the accounting draft.</p>}</section>}
 </main>
}
const page:React.CSSProperties={maxWidth:1100,margin:'0 auto',padding:'28px 22px 80px'},header:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'},panel:React.CSSProperties={marginTop:18,padding:20,border:'1px solid #dbe7ea',borderRadius:16,background:'white'},metrics:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:12},list:React.CSSProperties={display:'grid',gap:10},row:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',padding:12,border:'1px solid #e2e8f0',borderRadius:12},stack:React.CSSProperties={display:'grid',gap:4},form:React.CSSProperties={marginTop:18,paddingTop:16,borderTop:'1px solid #e2e8f0'},grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12},label:React.CSSProperties={display:'grid',gap:6,marginTop:10,fontWeight:700},input:React.CSSProperties={padding:10,border:'1px solid #cbd5e1',borderRadius:10,font:'inherit'},primary:React.CSSProperties={marginTop:12,padding:'10px 14px',border:0,borderRadius:10,background:'#05879A',color:'white',fontWeight:800},secondary:React.CSSProperties={padding:'9px 12px',border:'1px solid #cbd5e1',borderRadius:10,background:'white',fontWeight:700},muted:React.CSSProperties={color:'#475569'},err:React.CSSProperties={padding:12,background:'#fef2f2',color:'#991b1b',borderRadius:10},ok:React.CSSProperties={padding:12,background:'#ecfdf5',color:'#065f46',borderRadius:10}
