'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'

type Session={accessToken:string;role:string;societyName?:string}
type ProviderLink={status:'PENDING'|'APPROVED'|'REJECTED'|'SUSPENDED';commissionBps:number}
type Provider={id:string;businessName:string;description?:string|null;verification:string;societies:ProviderLink[]}
type Offering={id:string;name:string;active:boolean;pricePaise:number;durationMinutes?:number|null;provider:{id:string;businessName:string;ratingAverage?:number|null;ratingCount?:number;completedJobs?:number};category:{name:string}}
type Catalog={providers:Provider[];offerings:Offering[];categories:{id:string;name:string}[]}
const base=(process.env.NEXT_PUBLIC_AARAGATE_API_BASE_URL??'http://localhost:3000').replace(/\/$/,'')
function session():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw) as Session:null}catch{return null}}
async function api<T>(s:Session,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${base}/api/v1${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.accessToken}`,...init.headers}});const text=await r.text();const body=text?JSON.parse(text):null;if(!r.ok)throw new Error(body?.message??`Request failed (${r.status})`);return body as T}

export default function MarketplaceControlPage(){
  const[s,setS]=useState<Session|null>(null),[catalog,setCatalog]=useState<Catalog>({providers:[],offerings:[],categories:[]}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[query,setQuery]=useState('')
  const allowed=(x:Session|null)=>!!x&&['SUPER_ADMIN','SOCIETY_ADMIN','FACILITY_MANAGER'].includes(x.role)
  const load=useCallback(async(x:Session)=>{setLoading(true);setError('');try{setCatalog(await api<Catalog>(x,'/services-marketplace/admin/catalog'))}catch(e){setError(e instanceof Error?e.message:'Marketplace controls could not be loaded')}finally{setLoading(false)}},[])
  useEffect(()=>{const x=session();setS(x);if(x&&allowed(x))void load(x);else setLoading(false)},[load])
  const providers=useMemo(()=>{const q=query.trim().toLowerCase();return q?catalog.providers.filter(p=>[p.businessName,p.verification,p.societies[0]?.status??''].join(' ').toLowerCase().includes(q)):catalog.providers},[catalog.providers,query])
  const setStatus=async(p:Provider,status:ProviderLink['status'])=>{if(!s)return;let commissionBps:number|undefined;if(status==='APPROVED'){const entered=prompt(`Commission % for ${p.businessName}`,String((p.societies[0]?.commissionBps??1000)/100));if(entered===null)return;const n=Number(entered);if(!Number.isFinite(n)||n<0||n>100){setError('Commission must be between 0 and 100%');return}commissionBps=Math.round(n*100)}if(!confirm(`${status.toLowerCase()} ${p.businessName} for this society?`))return;setBusy(p.id);setError('');try{await api(s,`/services-marketplace/admin/providers/${p.id}/status`,{method:'PATCH',body:JSON.stringify({status,commissionBps})});await load(s)}catch(e){setError(e instanceof Error?e.message:'Provider status could not be updated')}finally{setBusy('')}}
  if(loading)return <main style={{padding:32}}>Loading marketplace controls…</main>
  if(!allowed(s))return <main style={{padding:32}}><h1>Marketplace operations access required</h1><a href="/">Return to Admin</a></main>
  return <main style={{maxWidth:1120,margin:'0 auto',padding:'28px 22px 80px'}}><header style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><small>{s?.societyName??'Current society'}</small><h1 style={{margin:'4px 0'}}>Marketplace provider controls</h1><p style={{margin:0}}>Approve, reject or suspend providers only for this society. Platform verification remains a separate Super Admin control.</p></div><a href="/">← Admin console</a></header>{error&&<div style={errorBox}>{error}</div>}<section style={panel}><input aria-label="Search providers" placeholder="Search provider or status" value={query} onChange={e=>setQuery(e.target.value)} style={{...input,maxWidth:420,width:'100%'}}/><div style={{display:'grid',gap:10,marginTop:16}}>{providers.length===0?<p>No matching providers.</p>:providers.map(p=>{const link=p.societies[0];return <article key={p.id} style={card}><div><b>{p.businessName}</b>{p.description&&<div>{p.description}</div>}<small>Platform: {p.verification} · Society: {link?.status??'NOT LINKED'}{link?.status==='APPROVED'?` · ${link.commissionBps/100}% commission`:''}</small></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{p.verification==='VERIFIED'&&link?.status!=='APPROVED'&&<button disabled={!!busy} onClick={()=>void setStatus(p,'APPROVED')} style={primary}>Approve</button>}{link&&link.status!=='REJECTED'&&<button disabled={!!busy} onClick={()=>void setStatus(p,'REJECTED')} style={button}>Reject</button>}{link&&link.status==='APPROVED'&&<button disabled={!!busy} onClick={()=>void setStatus(p,'SUSPENDED')} style={button}>Suspend</button>}{link&&['REJECTED','SUSPENDED'].includes(link.status)&&p.verification==='VERIFIED'&&<button disabled={!!busy} onClick={()=>void setStatus(p,'APPROVED')} style={primary}>Re-approve</button>}</div></article>})}</div></section><section style={panel}><h2>Offerings</h2><p>Offering activation is a platform-catalog action. Current society users can see the resulting live catalog here.</p><div style={{display:'grid',gap:8}}>{catalog.offerings.map(o=><article key={o.id} style={card}><div><b>{o.name}</b><div>{o.provider.businessName} · {o.category.name}</div><small>₹{(o.pricePaise/100).toLocaleString('en-IN')}{o.durationMinutes?` · ${o.durationMinutes} min`:''}{o.provider.ratingAverage?` · ${o.provider.ratingAverage.toFixed(1)}★ (${o.provider.ratingCount??0})`:''}{o.provider.completedJobs!==undefined?` · ${o.provider.completedJobs} completed`:''}</small></div><strong>{o.active?'ACTIVE':'INACTIVE'}</strong></article>)}</div></section></main>
}
const panel:React.CSSProperties={marginTop:20,padding:20,border:'1px solid #dbe7ea',borderRadius:16,background:'white'}
const card:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',padding:14,border:'1px solid #e5e7eb',borderRadius:12,flexWrap:'wrap'}
const input:React.CSSProperties={padding:11,border:'1px solid #cbd5e1',borderRadius:10}
const button:React.CSSProperties={padding:'9px 12px',borderRadius:10,border:'1px solid #cbd5e1',background:'white',fontWeight:700}
const primary:React.CSSProperties={...button,background:'#05879A',color:'white',borderColor:'#05879A'}
const errorBox:React.CSSProperties={marginTop:18,padding:12,border:'1px solid #ef4444',borderRadius:10}
