'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { operatorConfirm, operatorPrompt } from '../../../lib/operator-dialog'
import { api, type Session } from '../../../lib/admin-client'

type SocietyLink={societyId:string;status:string;commissionBps:number;society:{name:string;code:string}}
type Provider={id:string;businessName:string;contactName?:string|null;phone:string;email?:string|null;description?:string|null;verification:'PENDING'|'VERIFIED'|'REJECTED'|'SUSPENDED';active:boolean;createdAt:string;societies:SocietyLink[]}
type ProviderApplication={id:string;businessName:string;contactName?:string|null;phone:string;email?:string|null;status:string;evidenceRefs?:string[];reviewNote?:string|null;createdAt:string;applicantName?:string|null;applicantPhone?:string|null}
type ServiceDispute={id:string;bookingId:string;providerId:string;providerName:string;offeringName:string;reasonCode:string;detail:string;status:string;resolutionNote?:string|null;createdAt:string}
function getSession():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw) as Session:null}catch{return null}}

export default function PlatformProvidersPage(){
  const[s,setS]=useState<Session|null>(null),[providers,setProviders]=useState<Provider[]>([]),[applications,setApplications]=useState<ProviderApplication[]>([]),[disputes,setDisputes]=useState<ServiceDispute[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[query,setQuery]=useState('')
  const load=useCallback(async(x:Session)=>{setLoading(true);setError('');try{const[p,a,d]=await Promise.all([api<Provider[]>('/platform/services/providers',{},x),api<ProviderApplication[]>('/platform/services/provider-applications?status=SUBMITTED',{},x),api<ServiceDispute[]>('/platform/services/disputes?status=OPEN',{},x)]);setProviders(p);setApplications(a);setDisputes(d)}catch(e){setError(e instanceof Error?e.message:'Provider operations could not be loaded')}finally{setLoading(false)}},[])
  useEffect(()=>{const x=getSession();setS(x);if(x?.role==='SUPER_ADMIN')void load(x);else setLoading(false)},[load])
  const visible=useMemo(()=>{const q=query.trim().toLowerCase();return q?providers.filter(p=>[p.businessName,p.phone,p.email??'',p.verification,...p.societies.map(x=>x.society.name)].join(' ').toLowerCase().includes(q)):providers},[providers,query])
  const setVerification=async(p:Provider,verification:Provider['verification'])=>{if(!s)return;if(!await operatorConfirm(`${verification.toLowerCase()} ${p.businessName} at platform level? This affects availability across societies.`))return;setBusy(p.id);setError('');try{await api(`/platform/services/providers/${p.id}/verification`,{method:'PATCH',body:JSON.stringify({verification})},s);await load(s)}catch(e){setError(e instanceof Error?e.message:'Provider verification could not be updated')}finally{setBusy('')}}
  const reviewApplication=async(a:ProviderApplication,decision:'APPROVE'|'REJECT')=>{if(!s)return;const note=await operatorPrompt(`${decision==='APPROVE'?'Approve':'Reject'} ${a.businessName}. Review note`)??'';if(note.trim().length<3)return;setBusy(a.id);setError('');try{await api(`/platform/services/provider-applications/${a.id}/review`,{method:'POST',body:JSON.stringify({decision,note:note.trim()})},s);await load(s)}catch(e){setError(e instanceof Error?e.message:'Provider application could not be reviewed')}finally{setBusy('')}}
  const resolveDispute=async(d:ServiceDispute,status:'RESOLVED'|'DISMISSED')=>{if(!s)return;const resolutionNote=await operatorPrompt(`${status==='RESOLVED'?'Resolve':'Dismiss'} dispute for ${d.offeringName}. Resolution note`)??'';if(resolutionNote.trim().length<5)return;setBusy(d.id);setError('');try{await api(`/platform/services/disputes/${d.id}/resolve`,{method:'POST',body:JSON.stringify({status,resolutionNote:resolutionNote.trim()})},s);await load(s)}catch(e){setError(e instanceof Error?e.message:'Dispute could not be resolved')}finally{setBusy('')}}
  if(loading)return <main style={{padding:32}}>Loading platform providers…</main>
  if(!s||s.role!=='SUPER_ADMIN')return <main style={{padding:32}}><h1>Platform access required</h1><a href="/">Return to Admin</a></main>
  return <main style={{maxWidth:1160,margin:'0 auto',padding:'28px 22px 80px'}}><header style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><small>SUPER ADMIN</small><h1 style={{margin:'4px 0'}}>Provider verification</h1><p style={{margin:0}}>Global provider verification is independent from society approval, earned trust and commercial placement.</p></div><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><a href="/platform/provider-trust">Provider trust review</a><a href="/platform">Platform societies</a><a href="/">Admin console</a></div></header>{error&&<div style={errorBox}>{error}</div>}<section style={panel}><input aria-label="Search providers" placeholder="Search provider, mobile, society or status" value={query} onChange={e=>setQuery(e.target.value)} style={{...input,width:'100%',maxWidth:480}}/><div style={{display:'grid',gap:10,marginTop:16}}>{visible.length===0?<p>No matching providers.</p>:visible.map(p=><article key={p.id} style={card}><div style={{minWidth:260,flex:'1 1 420px'}}><b style={{fontSize:17}}>{p.businessName}</b><div>{[p.contactName,p.phone,p.email].filter(Boolean).join(' · ')}</div>{p.description&&<div>{p.description}</div>}<small>{p.verification} · {p.active?'ACTIVE':'INACTIVE'} · submitted {new Date(p.createdAt).toLocaleDateString('en-IN')}</small>{p.societies.length>0&&<div style={{marginTop:6}}><small>Societies: {p.societies.map(x=>`${x.society.name} (${x.status})`).join(', ')}</small></div>}</div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{p.verification!=='VERIFIED'&&<button disabled={!!busy} onClick={()=>void setVerification(p,'VERIFIED')} style={primary}>Verify</button>}{p.verification!=='REJECTED'&&<button disabled={!!busy} onClick={()=>void setVerification(p,'REJECTED')} style={button}>Reject</button>}{p.verification!=='SUSPENDED'&&<button disabled={!!busy} onClick={()=>void setVerification(p,'SUSPENDED')} style={button}>Suspend</button>}{['REJECTED','SUSPENDED'].includes(p.verification)&&<button disabled={!!busy} onClick={()=>void setVerification(p,'VERIFIED')} style={primary}>Re-verify</button>}</div></article>)}</div></section>
    <section style={panel}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'baseline',flexWrap:'wrap'}}><div><h2 style={{margin:'0 0 4px'}}>Provider onboarding review</h2><small>Application evidence is reference metadata only; approval does not claim live KYC certification.</small></div><b>{applications.length} submitted</b></div><div style={{display:'grid',gap:10,marginTop:16}}>{applications.length===0?<p>No submitted provider applications.</p>:applications.map(a=><article key={a.id} style={card}><div style={{minWidth:260,flex:'1 1 420px'}}><b>{a.businessName}</b><div>{[a.contactName,a.phone,a.email].filter(Boolean).join(' · ')}</div><small>Applicant {a.applicantName??a.applicantPhone??'Registered user'} · submitted {new Date(a.createdAt).toLocaleDateString('en-IN')}</small>{Array.isArray(a.evidenceRefs)&&a.evidenceRefs.length>0&&<div><small>Evidence refs: {a.evidenceRefs.slice(0,5).join(', ')}</small></div>}</div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button disabled={!!busy} style={button} onClick={()=>void reviewApplication(a,'REJECT')}>Reject</button><button disabled={!!busy} style={primary} onClick={()=>void reviewApplication(a,'APPROVE')}>Approve application</button></div></article>)}</div></section>
    <section style={panel}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'baseline',flexWrap:'wrap'}}><div><h2 style={{margin:'0 0 4px'}}>Open service disputes</h2><small>Resolution records the operational disposition; it does not silently mutate payment, settlement or booking state.</small></div><b>{disputes.length} open</b></div><div style={{display:'grid',gap:10,marginTop:16}}>{disputes.length===0?<p>No open service disputes.</p>:disputes.map(d=><article key={d.id} style={card}><div style={{minWidth:260,flex:'1 1 420px'}}><b>{d.offeringName} · {d.providerName}</b><div>{d.reasonCode.replaceAll('_',' ')}</div><p style={{margin:'6px 0'}}>{d.detail}</p><small>Opened {new Date(d.createdAt).toLocaleString('en-IN')}</small></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button disabled={!!busy} style={button} onClick={()=>void resolveDispute(d,'DISMISSED')}>Dismiss</button><button disabled={!!busy} style={primary} onClick={()=>void resolveDispute(d,'RESOLVED')}>Resolve</button></div></article>)}</div></section>
  </main>
}
const panel:React.CSSProperties={marginTop:20,padding:20,border:'1px solid #dbe7ea',borderRadius:16,background:'white'}
const card:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',padding:14,border:'1px solid #e5e7eb',borderRadius:12,flexWrap:'wrap'}
const input:React.CSSProperties={padding:11,border:'1px solid #cbd5e1',borderRadius:10}
const button:React.CSSProperties={padding:'9px 12px',borderRadius:10,border:'1px solid #cbd5e1',background:'white',fontWeight:700}
const primary:React.CSSProperties={...button,background:'#05879A',color:'white',borderColor:'#05879A'}
const errorBox:React.CSSProperties={marginTop:18,padding:12,border:'1px solid #ef4444',borderRadius:10}
