'use client'

import { FormEvent, useCallback, useEffect, useState } from 'react'
import { ActionBar, EmptyState, ErrorState, EvidenceGrid, FormField, PageHeader, PageShell, PrimaryButton, ReadinessPanel, SecondaryButton, SelectField, StatusPill } from '../../../components/admin-ui'
import './exports.css'

type Session={accessToken:string;role:string;societyName?:string}
type ExportJob={id:string;contractVersion:string;format:'CSV'|'JSONL';fromDate:string;toDate:string;status:string;recordCount:number|null;artifactKey:string|null;errorCode:string|null;createdAt:string;completedAt:string|null}
type Delivery={id:string;exportJobId:string;provider:string;status:string;attemptCount:number;lastAttemptAt:string|null;nextAttemptAt:string|null;providerReceiptId:string|null;failureCode:string|null;failureMessage:string|null;createdAt:string;updatedAt:string;completedAt:string|null}
type DeliveryMetrics={totals:{totalCount:number;pendingCount:number;deliveredCount:number;failedCount:number;retryExhaustedCount:number;oldestPendingAt:string|null;terminalSuccessRatePct:number|null};providers:Array<{provider:string;totalCount:number;pendingCount:number;deliveredCount:number;failedCount:number;oldestPendingAt:string|null;terminalSuccessRatePct:number|null}>}
type Readiness={provider:string;bridgeConfigured:boolean;apiKeyConfigured:boolean;autoDeliveryEnabled:boolean;state:'NOT_CONFIGURED'|'READY_DISABLED'|'ACTIVE';networkCheckPerformed:false}
type DeliveryAction={id:string;deliveryId:string;actorUserId:string;action:'MANUAL_RETRY';fromStatus:'FAILED'|'UNKNOWN';previousAttemptCount:number;occurredAt:string}

const base=(process.env.NEXT_PUBLIC_AARAGATE_API_BASE_URL??'http://localhost:3000').replace(/\/$/,'')
const readRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','COMMITTEE_MEMBER','ACCOUNTANT'])
const manageRoles=new Set(['SUPER_ADMIN','ACCOUNTANT'])
const contractVersion='aaraagate.accounting.journal.v1'
const dateValue=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
const today=()=>dateValue(new Date())
function presetRange(kind:'THIS_MONTH'|'LAST_MONTH'|'FINANCIAL_YEAR'){
  const now=new Date()
  if(kind==='THIS_MONTH')return {from:dateValue(new Date(now.getFullYear(),now.getMonth(),1)),to:dateValue(new Date(now.getFullYear(),now.getMonth()+1,0))}
  if(kind==='LAST_MONTH')return {from:dateValue(new Date(now.getFullYear(),now.getMonth()-1,1)),to:dateValue(new Date(now.getFullYear(),now.getMonth(),0))}
  const startYear=now.getMonth()>=3?now.getFullYear():now.getFullYear()-1
  return {from:dateValue(new Date(startYear,3,1)),to:dateValue(new Date(startYear+1,2,31))}
}
function session():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw) as Session:null}catch{return null}}
async function api<T>(s:Session,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${base}/api/v1${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.accessToken}`,...init.headers}});const text=await r.text();const body=text?JSON.parse(text):null;if(!r.ok)throw new Error(Array.isArray(body?.message)?body.message.join(', '):body?.message??`Request failed (${r.status})`);return body as T}
async function downloadArtifact(s:Session,job:ExportJob){const r=await fetch(`${base}/api/v1/accounting/exports/${job.id}/artifact`,{headers:{Authorization:`Bearer ${s.accessToken}`}});if(!r.ok){const text=await r.text();let message=`Download failed (${r.status})`;try{const body=text?JSON.parse(text):null;message=Array.isArray(body?.message)?body.message.join(', '):body?.message??message}catch{}throw new Error(message)}const blob=await r.blob();const disposition=r.headers.get('content-disposition')??'';const match=disposition.match(/filename="?([^";]+)"?/i);const filename=match?.[1]??`aaraagate-accounting-${job.id}.${job.format==='CSV'?'csv':'jsonl'}`;const href=URL.createObjectURL(blob);try{const link=document.createElement('a');link.href=href;link.download=filename;document.body.appendChild(link);link.click();link.remove()}finally{URL.revokeObjectURL(href)}}
async function downloadEvidence(s:Session,delivery:Delivery){const evidence=await api<unknown>(s,`/accounting/connector-deliveries/${delivery.id}/evidence`);const blob=new Blob([JSON.stringify(evidence,null,2)+'\n'],{type:'application/json'});const href=URL.createObjectURL(blob);try{const link=document.createElement('a');link.href=href;link.download=`aaraagate-accounting-connector-evidence-${delivery.id}.json`;document.body.appendChild(link);link.click();link.remove()}finally{URL.revokeObjectURL(href)}}
function age(value:string|null){if(!value)return '—';const ms=Date.now()-new Date(value).getTime();const hours=Math.max(0,Math.floor(ms/3_600_000));return hours<24?`${hours}h`:`${Math.floor(hours/24)}d ${hours%24}h`}

export default function AccountingExportsPage(){
  const[s,setS]=useState<Session|null>(null),[jobs,setJobs]=useState<ExportJob[]>([]),[deliveries,setDeliveries]=useState<Delivery[]>([]),[metrics,setMetrics]=useState<DeliveryMetrics|null>(null),[readiness,setReadiness]=useState<Readiness|null>(null),[actions,setActions]=useState<DeliveryAction[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[downloadingId,setDownloadingId]=useState<string|null>(null),[evidenceDownloadingId,setEvidenceDownloadingId]=useState<string|null>(null),[retryingId,setRetryingId]=useState<string|null>(null),[error,setError]=useState('')
  const[fromDate,setFromDate]=useState(today()),[toDate,setToDate]=useState(today()),[format,setFormat]=useState<'CSV'|'JSONL'>('CSV')
  const canRead=!!s&&readRoles.has(s.role),canManage=!!s&&manageRoles.has(s.role)
  const load=useCallback(async(x:Session)=>{setLoading(true);setError('');try{const[j,d,m,r,a]=await Promise.all([api<ExportJob[]>(x,'/accounting/exports'),api<Delivery[]>(x,'/accounting/connector-deliveries'),api<DeliveryMetrics>(x,'/accounting/connector-deliveries/metrics'),api<Readiness>(x,'/accounting/connector-deliveries/readiness'),api<DeliveryAction[]>(x,'/accounting/connector-deliveries/actions')]);setJobs(j);setDeliveries(d);setMetrics(m);setReadiness(r);setActions(a)}catch(err){setError(err instanceof Error?err.message:'Could not load accounting exports')}finally{setLoading(false)}},[])
  useEffect(()=>{const x=session();setS(x);if(x&&readRoles.has(x.role))void load(x);else setLoading(false)},[load])

  function applyPreset(kind:'THIS_MONTH'|'LAST_MONTH'|'FINANCIAL_YEAR'){const range=presetRange(kind);setFromDate(range.from);setToDate(range.to)}
  async function createExport(e:FormEvent){e.preventDefault();if(!s||!canRead)return;setBusy(true);setError('');try{await api<ExportJob>(s,'/accounting/exports',{method:'POST',body:JSON.stringify({idempotencyKey:`admin-${Date.now()}`,contractVersion,format,fromDate,toDate})});await load(s)}catch(err){setError(err instanceof Error?err.message:'Could not create accounting export')}finally{setBusy(false)}}
  async function download(job:ExportJob){if(!s||job.status!=='COMPLETED'||!job.artifactKey)return;setDownloadingId(job.id);setError('');try{await downloadArtifact(s,job)}catch(err){setError(err instanceof Error?err.message:'Could not download accounting export')}finally{setDownloadingId(null)}}
  async function evidence(delivery:Delivery){if(!s)return;setEvidenceDownloadingId(delivery.id);setError('');try{await downloadEvidence(s,delivery)}catch(err){setError(err instanceof Error?err.message:'Could not download reconciliation evidence')}finally{setEvidenceDownloadingId(null)}}
  async function retry(delivery:Delivery){if(!s||!canManage||!['FAILED','UNKNOWN'].includes(delivery.status))return;setRetryingId(delivery.id);setError('');try{await api<Delivery>(s,`/accounting/connector-deliveries/${delivery.id}/retry`,{method:'POST'});await load(s)}catch(err){setError(err instanceof Error?err.message:'Could not retry connector delivery')}finally{setRetryingId(null)}}
  const deliveryByExport=new Map(deliveries.map(d=>[d.exportJobId,d]))

  if(loading)return <PageShell><PageHeader title="Accounting exports" description="Loading export and connector evidence…"/></PageShell>
  if(!canRead)return <PageShell><PageHeader title="Finance access required" actions={<a href="/finance">Return to Finance</a>}/></PageShell>

  return <PageShell>
    <PageHeader context={`${s?.societyName??'Current society'} · ${s?.role.replaceAll('_',' ')}`} title="Accounting exports" description="Create provider-neutral exports and review downstream connector delivery evidence." actions={<a href="/finance">← Finance workspace</a>}/>
    {error&&<ErrorState title="Accounting export operation failed" description={error}/>}
    <ActionBar label="Accounting export actions"><SecondaryButton loading={loading} disabled={busy||!!downloadingId||!!evidenceDownloadingId||!!retryingId} onClick={()=>s&&void load(s)}>Refresh</SecondaryButton></ActionBar>
    {readiness&&<ReadinessPanel title="Connector readiness" state="ready" status={{label:readiness.state.replaceAll('_',' '),tone:readiness.state==='ACTIVE'?'success':readiness.state==='NOT_CONFIGURED'?'danger':'warning'}} boundary="This is a configuration-only check. Aaraagate does not expose the connector URL or credential, and this screen does not make a network call to the provider." checks={<EvidenceGrid items={[{id:'provider',label:'Provider',value:readiness.provider},{id:'bridge',label:'Bridge configured',value:readiness.bridgeConfigured?'Yes':'No'},{id:'api-key',label:'API key configured',value:readiness.apiKeyConfigured?'Yes':'No'},{id:'auto-delivery',label:'Auto delivery',value:readiness.autoDeliveryEnabled?'Enabled':'Disabled'}]}/>}/>} 
    {metrics&&<section style={panel}><div style={sectionHeader}><h2>Connector health</h2><small>Tenant-scoped delivery evidence</small></div><EvidenceGrid items={[{id:'pending',label:'Pending',value:metrics.totals.pendingCount},{id:'failed',label:'Failed',value:metrics.totals.failedCount},{id:'retry-exhausted',label:'Retry exhausted',value:metrics.totals.retryExhaustedCount},{id:'delivered',label:'Delivered',value:metrics.totals.deliveredCount},{id:'success',label:'Terminal success',value:metrics.totals.terminalSuccessRatePct===null?'—':`${metrics.totals.terminalSuccessRatePct}%`},{id:'oldest',label:'Oldest pending',value:age(metrics.totals.oldestPendingAt)}]}/>{metrics.providers.length>0&&<div style={{overflowX:'auto',marginTop:16}}><table style={table}><thead><tr><th>Provider</th><th>Pending</th><th>Delivered</th><th>Failed</th><th>Success</th><th>Oldest pending</th></tr></thead><tbody>{metrics.providers.map(p=><tr key={p.provider}><td><b>{p.provider}</b></td><td>{p.pendingCount}</td><td>{p.deliveredCount}</td><td>{p.failedCount}</td><td>{p.terminalSuccessRatePct===null?'—':`${p.terminalSuccessRatePct}%`}</td><td>{age(p.oldestPendingAt)}</td></tr>)}</tbody></table></div>}</section>}
    <section style={panel}><h2>New export job</h2><ActionBar label="Date presets"><SecondaryButton type="button" onClick={()=>applyPreset('THIS_MONTH')}>This month</SecondaryButton><SecondaryButton type="button" onClick={()=>applyPreset('LAST_MONTH')}>Last month</SecondaryButton><SecondaryButton type="button" onClick={()=>applyPreset('FINANCIAL_YEAR')}>Indian FY</SecondaryButton></ActionBar><form onSubmit={createExport} style={grid}><FormField label="From" type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)} required/><FormField label="To" type="date" value={toDate} onChange={e=>setToDate(e.target.value)} required/><SelectField label="Format" value={format} onChange={e=>setFormat(e.target.value as 'CSV'|'JSONL')}><option value="CSV">CSV</option><option value="JSONL">JSONL</option></SelectField><FormField label="Contract" value={contractVersion} readOnly/><PrimaryButton type="submit" loading={busy} disabled={!!downloadingId||!!evidenceDownloadingId||!!retryingId}>Queue export</PrimaryButton></form><p style={{marginBottom:0,color:'#475569'}}>Exports are limited to a maximum 366-day range. Artifact downloads remain authenticated. Connector delivery is shown only when the server-side integration is explicitly enabled.</p></section>
    <section style={panel}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><h2 style={{margin:0}}>Recent jobs</h2><small>{jobs.length} shown</small></div>{jobs.length===0?<EmptyState title="No accounting export jobs yet"/>:<div style={{overflowX:'auto',marginTop:12}}><table style={table}><thead><tr><th>Created</th><th>Range</th><th>Format</th><th>Export</th><th>Records</th><th>Connector delivery</th><th>Artifact</th></tr></thead><tbody>{jobs.map(j=>{const d=deliveryByExport.get(j.id);return <tr key={j.id}><td><b>{new Date(j.createdAt).toLocaleString('en-IN')}</b><br/><small>{j.id}</small></td><td>{new Date(j.fromDate).toLocaleDateString('en-IN')} – {new Date(j.toDate).toLocaleDateString('en-IN')}</td><td>{j.format}</td><td><StatusPill label={j.status} tone={j.status==='COMPLETED'?'success':j.status==='FAILED'?'danger':'info'}/>{j.errorCode&&<><br/><small>{j.errorCode}</small></>}</td><td>{j.recordCount??'—'}</td><td>{d?<><StatusPill label={d.status} tone={d.status==='DELIVERED'?'success':d.status==='FAILED'?'danger':'info'}/><br/><small>{d.provider} · attempt {d.attemptCount}</small>{d.providerReceiptId&&<><br/><small>Receipt: {d.providerReceiptId}</small></>}{d.failureCode&&<><br/><small>{d.failureCode}</small></>}<br/><SecondaryButton disabled={evidenceDownloadingId===d.id} onClick={()=>void evidence(d)}>{evidenceDownloadingId===d.id?'Preparing…':'Evidence JSON'}</SecondaryButton>{canManage&&['FAILED','UNKNOWN'].includes(d.status)&&<><br/><SecondaryButton disabled={retryingId===d.id} onClick={()=>void retry(d)}>{retryingId===d.id?'Queuing…':'Retry delivery'}</SecondaryButton></>}</>:<small>Not queued</small>}</td><td>{j.status==='COMPLETED'&&j.artifactKey?<SecondaryButton disabled={downloadingId===j.id} onClick={()=>void download(j)}>{downloadingId===j.id?'Downloading…':`Download ${j.format}`}</SecondaryButton>:j.status==='FAILED'?<small>Generation failed</small>:<small>Not ready</small>}</td></tr>})}</tbody></table></div>}</section>
    <section style={panel}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><h2 style={{margin:0}}>Manual retry history</h2><small>{actions.length} shown</small></div>{actions.length===0?<EmptyState title="No manual connector retries recorded"/>:<div style={{overflowX:'auto',marginTop:12}}><table style={table}><thead><tr><th>Time</th><th>Delivery</th><th>Action</th><th>Prior state</th><th>Prior attempts</th><th>Actor</th></tr></thead><tbody>{actions.map(a=><tr key={a.id}><td>{new Date(a.occurredAt).toLocaleString('en-IN')}</td><td><small>{a.deliveryId}</small></td><td>{a.action.replaceAll('_',' ')}</td><td>{a.fromStatus}</td><td>{a.previousAttemptCount}</td><td><small>{a.actorUserId}</small></td></tr>)}</tbody></table></div>}</section>
  </PageShell>
}

const panel:React.CSSProperties={marginTop:20,padding:20,border:'1px solid #dbe7ea',borderRadius:16,background:'white'}
const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,alignItems:'end'}
const table:React.CSSProperties={width:'100%',borderCollapse:'collapse'}

const sectionHeader:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}
