'use client'

import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react'

type Session={accessToken:string;role:string;societyName?:string}
type Vendor={id:string;code:string;name:string;status:string}
type Contract={id:string;vendorId:string;vendorCode:string;vendorName:string;contractNumber:string;title:string;contractType:string;startsOn:string;endsOn:string;renewalNoticeDays:number;slaReference?:string|null;documentReference?:string|null;status:string;lifecycleState:string;notes?:string|null;updatedAt?:string}
const base=(process.env.NEXT_PUBLIC_AARAGATE_API_BASE_URL??'http://localhost:3000').replace(/\/$/,'')
const readRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','COMMITTEE_MEMBER','FACILITY_MANAGER','AUDITOR'])
const manageRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','FACILITY_MANAGER'])
function session():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw) as Session:null}catch{return null}}
async function api<T>(s:Session,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${base}/api/v1${path}`,{...init,headers:{Accept:'application/json','Content-Type':'application/json',Authorization:`Bearer ${s.accessToken}`,...init.headers}});const text=await r.text();const body=text?JSON.parse(text):null;if(!r.ok)throw new Error(body?.message??`Request failed (${r.status})`);return body as T}

export default function VendorContractsPage(){
 const s=typeof window==='undefined'?null:session(),allowed=!!s&&readRoles.has(s.role),canManage=!!s&&manageRoles.has(s.role)
 const[vendors,setVendors]=useState<Vendor[]>([]),[contracts,setContracts]=useState<Contract[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const[vendorId,setVendorId]=useState(''),[contractNumber,setContractNumber]=useState(''),[title,setTitle]=useState(''),[contractType,setContractType]=useState('SERVICE_AGREEMENT'),[startsOn,setStartsOn]=useState(''),[endsOn,setEndsOn]=useState(''),[renewalNoticeDays,setRenewalNoticeDays]=useState('30'),[slaReference,setSlaReference]=useState(''),[documentReference,setDocumentReference]=useState(''),[notes,setNotes]=useState('')
 const activeVendors=useMemo(()=>vendors.filter(v=>v.status==='ACTIVE'),[vendors])
 const load=useCallback(async()=>{if(!s||!allowed)return;setLoading(true);setError('');try{const[v,c]=await Promise.all([api<Vendor[]>(s,'/society-vendors'),api<Contract[]>(s,'/society-vendors/contracts')]);setVendors(v);setContracts(c)}catch(e){setError(e instanceof Error?e.message:'Vendor contracts could not be loaded')}finally{setLoading(false)}},[s?.accessToken,allowed])
 useEffect(()=>{void load()},[load])
 const run=async(fn:()=>Promise<void>,message:string)=>{setBusy(true);setError('');setSuccess('');try{await fn();setSuccess(message);await load()}catch(e){setError(e instanceof Error?e.message:'Operation failed')}finally{setBusy(false)}}
 const create=(e:FormEvent)=>{e.preventDefault();if(!s||!canManage)return;void run(async()=>{await api(s,'/society-vendors/contracts',{method:'POST',body:JSON.stringify({vendorId,contractNumber:contractNumber.trim(),title:title.trim(),contractType,startsOn,endsOn,renewalNoticeDays:Number(renewalNoticeDays),slaReference:slaReference.trim()||undefined,documentReference:documentReference.trim()||undefined,notes:notes.trim()||undefined})});setContractNumber('');setTitle('');setStartsOn('');setEndsOn('');setSlaReference('');setDocumentReference('');setNotes('')},'Vendor contract recorded.')}
 const status=(id:string,value:'ACTIVE'|'EXPIRED'|'TERMINATED')=>{if(!s||!canManage)return;void run(()=>api(s,`/society-vendors/contracts/${id}/status`,{method:'PATCH',body:JSON.stringify({status:value})}).then(()=>undefined),'Contract status updated.')}
 if(!s||!allowed)return <main style={page}><h1>Society vendor access required</h1><a href="/society-vendors">Return</a></main>
 return <main style={page}><header style={header}><div><small>{s.societyName??'Current society'} · {s.role.replaceAll('_',' ')}</small><h1>Vendor contracts & SLA evidence</h1><p>Descriptive contract dates, SLA references and expiry readiness. This view does not determine legal validity or renewal obligations.</p></div><a href="/society-vendors">← Procurement</a></header>{error&&<p style={err}>{error}</p>}{success&&<p style={ok}>{success}</p>}
 {canManage&&<form onSubmit={create} style={panel}><h2>Record vendor contract</h2><div style={grid}><label style={label}>Active vendor<select style={input} value={vendorId} onChange={e=>setVendorId(e.target.value)} required><option value="">Select vendor</option>{activeVendors.map(v=><option key={v.id} value={v.id}>{v.code} · {v.name}</option>)}</select></label><label style={label}>Contract number<input style={input} value={contractNumber} onChange={e=>setContractNumber(e.target.value)} required maxLength={120}/></label><label style={label}>Title<input style={input} value={title} onChange={e=>setTitle(e.target.value)} required maxLength={240}/></label><label style={label}>Type<select style={input} value={contractType} onChange={e=>setContractType(e.target.value)}><option value="SERVICE_AGREEMENT">Service agreement</option><option value="AMC">AMC</option><option value="SUPPLY">Supply</option><option value="OTHER">Other</option></select></label><label style={label}>Starts on<input style={input} type="date" value={startsOn} onChange={e=>setStartsOn(e.target.value)} required/></label><label style={label}>Ends on<input style={input} type="date" value={endsOn} onChange={e=>setEndsOn(e.target.value)} required/></label><label style={label}>Renewal notice days<input style={input} type="number" min="0" max="3650" value={renewalNoticeDays} onChange={e=>setRenewalNoticeDays(e.target.value)} required/></label><label style={label}>SLA reference<input style={input} value={slaReference} onChange={e=>setSlaReference(e.target.value)} maxLength={1000}/></label><label style={label}>Document reference<input style={input} value={documentReference} onChange={e=>setDocumentReference(e.target.value)} maxLength={1000}/></label></div><label style={label}>Notes<textarea style={input} value={notes} onChange={e=>setNotes(e.target.value)} maxLength={2000}/></label><button style={primary} disabled={busy||activeVendors.length===0}>Record contract</button></form>}
 <section style={panel}><h2>Contract lifecycle evidence</h2>{loading?<p>Loading…</p>:contracts.length===0?<p>No vendor contracts recorded.</p>:<div style={list}>{contracts.map(c=><article key={c.id} style={row}><div style={stack}><b>{c.contractNumber} · {c.title}</b><span>{c.vendorCode} · {c.vendorName} · {c.contractType.replaceAll('_',' ')}</span><small>{c.startsOn} → {c.endsOn} · {c.lifecycleState.replaceAll('_',' ')} · status {c.status}</small><small>Renewal notice: {c.renewalNoticeDays} days{c.slaReference?` · SLA: ${c.slaReference}`:''}</small>{c.documentReference&&<small>Document: {c.documentReference}</small>}{c.notes&&<small>{c.notes}</small>}</div>{canManage&&<div style={actions}>{c.status!=='ACTIVE'&&<button style={secondary} disabled={busy} onClick={()=>status(c.id,'ACTIVE')}>Mark active</button>}{c.status==='ACTIVE'&&<button style={secondary} disabled={busy} onClick={()=>status(c.id,'EXPIRED')}>Mark expired</button>}{c.status!=='TERMINATED'&&<button style={secondary} disabled={busy} onClick={()=>status(c.id,'TERMINATED')}>Terminate</button>}</div>}</article>)}</div>}</section>
 </main>
}
const page:React.CSSProperties={maxWidth:1100,margin:'0 auto',padding:'28px 22px 80px'},header:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'},panel:React.CSSProperties={marginTop:18,padding:20,border:'1px solid #dbe7ea',borderRadius:16,background:'white'},grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12},label:React.CSSProperties={display:'grid',gap:6,marginTop:10,fontWeight:700},input:React.CSSProperties={padding:10,border:'1px solid #cbd5e1',borderRadius:10,font:'inherit'},primary:React.CSSProperties={marginTop:12,padding:'10px 14px',border:0,borderRadius:10,background:'#05879A',color:'white',fontWeight:800},secondary:React.CSSProperties={padding:'9px 12px',border:'1px solid #cbd5e1',borderRadius:10,background:'white',fontWeight:700},list:React.CSSProperties={display:'grid',gap:10},row:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',padding:12,border:'1px solid #e2e8f0',borderRadius:12},stack:React.CSSProperties={display:'grid',gap:4},actions:React.CSSProperties={display:'flex',gap:8,flexWrap:'wrap'},err:React.CSSProperties={padding:12,background:'#fef2f2',color:'#991b1b',borderRadius:10},ok:React.CSSProperties={padding:12,background:'#ecfdf5',color:'#065f46',borderRadius:10}
