name: aaraagate_resident
description: aaraagate Resident mobile application.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.3.1

flutter:
  uses-material-design: true
