'use client'

import { useEffect,useMemo,useState } from 'react'

type Session={accessToken:string;role:string;societyName?:string}
type Alert={id:string;alertType:'WORK_ORDER_OVERDUE'|'CONTRACT_EXPIRING'|'CONTRACT_EXPIRED';sourceType:string;sourceId:string;severity:'INFO'|'WARNING'|'CRITICAL';title:string;message:string;dueAt?:string|null;status:'OPEN'|'ACKNOWLEDGED'|'RESOLVED';acknowledgedAt?:string|null;acknowledgedByUserId?:string|null;createdAt:string;updatedAt:string}
const base=(process.env.NEXT_PUBLIC_AARAGATE_API_BASE_URL??'http://localhost:3000').replace(/\/$/,'')
const readRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','FACILITY_MANAGER','COMMITTEE_MEMBER'])
const manageRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','FACILITY_MANAGER'])
function getSession():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw):null}catch{return null}}
async function api<T>(s:Session,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${base}/api/v1${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.accessToken}`,...init.headers}});const text=await r.text(),body=text?JSON.parse(text):null;if(!r.ok)throw new Error(Array.isArray(body?.message)?body.message.join(', '):body?.message??`Request failed (${r.status})`);return body as T}
const fmt=(v?:string|null)=>v?new Date(v).toLocaleString('en-IN'):'—'
export default function FacilitiesAlertsPage(){
 const s=typeof window==='undefined'?null:getSession(),canRead=!!s&&readRoles.has(s.role),canManage=!!s&&manageRoles.has(s.role)
 const[alerts,setAlerts]=useState<Alert[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(''),[filter,setFilter]=useState<'ALL'|'OPEN'|'ACKNOWLEDGED'|'RESOLVED'>('ALL')
 const summary=useMemo(()=>({open:alerts.filter(a=>a.status==='OPEN').length,critical:alerts.filter(a=>a.status!=='RESOLVED'&&a.severity==='CRITICAL').length,warning:alerts.filter(a=>a.status!=='RESOLVED'&&a.severity==='WARNING').length,resolved:alerts.filter(a=>a.status==='RESOLVED').length}),[alerts])
 const visible=useMemo(()=>filter==='ALL'?alerts:alerts.filter(a=>a.status===filter),[alerts,filter])
 async function load(){if(!s||!canRead)return;setBusy(true);setError('');try{setAlerts(await api<Alert[]>(s,'/facilities/alerts'))}catch(e){setError(e instanceof Error?e.message:'Could not load facilities alerts')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 async function generate(){if(!s||!canManage)return;setBusy(true);setError('');setResult('');try{const r=await api<{eligible:number;generated:number}>(s,'/facilities/alerts/generate',{method:'POST',body:JSON.stringify({windowDays:30})});setResult(`Scan complete: ${r.eligible} eligible, ${r.generated} new alert${r.generated===1?'':'s'}.`);await load()}catch(e){setError(e instanceof Error?e.message:'Could not generate alerts')}finally{setBusy(false)}}
 async function setStatus(id:string,status:'ACKNOWLEDGED'|'RESOLVED'){if(!s||!canManage)return;setBusy(true);setError('');try{await api(s,`/facilities/alerts/${id}/status`,{method:'POST',body:JSON.stringify({status})});await load()}catch(e){setError(e instanceof Error?e.message:'Could not update alert')}finally{setBusy(false)}}
 if(!s||!canRead)return <main style={{padding:32}}><h1>Facilities access required</h1><a href="/">Return to Admin</a></main>
 return <main style={{maxWidth:1180,margin:'0 auto',padding:'28px 22px 80px'}}><header><small>{s.societyName??'Current society'} · {s.role.replaceAll('_',' ')}</small><h1>Facilities alert inbox</h1><p>Track overdue maintenance and AMC, warranty or service-contract expiry risks.</p><p><a href="/facilities">← Facilities operations</a> · <a href="/facilities/contracts">AMC & evidence</a></p></header>{error&&<p style={errorBox}>{error}</p>}{result&&<p style={successBox}>{result}</p>}<section style={panel}><div style={stats}><div><b>{summary.open}</b><span>Open</span></div><div><b>{summary.critical}</b><span>Critical</span></div><div><b>{summary.warning}</b><span>Warnings</span></div><div><b>{summary.resolved}</b><span>Resolved</span></div></div><div style={{...row,marginTop:18,flexWrap:'wrap'}}><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{(['ALL','OPEN','ACKNOWLEDGED','RESOLVED'] as const).map(v=><button key={v} onClick={()=>setFilter(v)} style={filter===v?button:secondary}>{v.replaceAll('_',' ')}</button>)}</div><div style={{display:'flex',gap:8}}><button disabled={busy} onClick={()=>void load()} style={secondary}>Refresh</button>{canManage&&<button disabled={busy} onClick={()=>void generate()} style={button}>Scan now</button>}</div></div></section><section style={{...panel,marginTop:18}}><h2>Operational alerts</h2>{visible.length===0?<p>No alerts in this view.</p>:visible.map(a=><article key={a.id} style={item}><div><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><strong>{a.title}</strong><span style={badge(a.severity)}>{a.severity}</span><span style={statusBadge(a.status)}>{a.status}</span></div><p style={{margin:'8px 0'}}>{a.message}</p><small>{a.alertType.replaceAll('_',' ')} · Due {fmt(a.dueAt)} · Created {fmt(a.createdAt)}</small>{a.acknowledgedAt?<><br/><small>Acknowledged {fmt(a.acknowledgedAt)}</small></>:null}</div>{canManage&&a.status!=='RESOLVED'&&<div style={actions}>{a.status==='OPEN'&&<button disabled={busy} onClick={()=>void setStatus(a.id,'ACKNOWLEDGED')} style={secondary}>Acknowledge</button>}<button disabled={busy} onClick={()=>void setStatus(a.id,'RESOLVED')} style={button}>Resolve</button></div>}</article>)}</section></main>
}
const panel={background:'#fff',border:'1px solid #e5e7eb',borderRadius:18,padding:20,boxShadow:'0 8px 24px rgba(15,23,42,.05)'}
const row={display:'flex',alignItems:'center',justifyContent:'space-between',gap:12}
const stats={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(120px,1fr))',gap:12}
const item={display:'flex',justifyContent:'space-between',gap:16,padding:'16px 0',borderBottom:'1px solid #eef2f7',alignItems:'flex-start'}
const actions={display:'flex',gap:8,flexWrap:'wrap' as const,justifyContent:'flex-end'}
const button={border:0,borderRadius:10,padding:'10px 14px',background:'#05879A',color:'#fff',fontWeight:700,cursor:'pointer'}
const secondary={border:'1px solid #cbd5e1',borderRadius:10,padding:'9px 12px',background:'#fff',fontWeight:700,cursor:'pointer'}
const errorBox={background:'#fff1f2',border:'1px solid #fecdd3',padding:12,borderRadius:10,color:'#9f1239'}
const successBox={background:'#ecfdf5',border:'1px solid #a7f3d0',padding:12,borderRadius:10,color:'#065f46'}
const badge=(severity:Alert['severity'])=>({display:'inline-block',padding:'4px 8px',borderRadius:999,fontSize:12,fontWeight:800,background:severity==='CRITICAL'?'#fee2e2':severity==='WARNING'?'#fef3c7':'#e0f2fe',color:severity==='CRITICAL'?'#991b1b':severity==='WARNING'?'#92400e':'#075985'})
const statusBadge=(status:Alert['status'])=>({display:'inline-block',padding:'4px 8px',borderRadius:999,fontSize:12,fontWeight:700,background:status==='RESOLVED'?'#dcfce7':status==='ACKNOWLEDGED'?'#e0e7ff':'#f1f5f9',color:status==='RESOLVED'?'#166534':status==='ACKNOWLEDGED'?'#3730a3':'#334155'})
