export enum AppRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  SOCIETY_ADMIN = 'SOCIETY_ADMIN',
  COMMITTEE_MEMBER = 'COMMITTEE_MEMBER',
  FACILITY_MANAGER = 'FACILITY_MANAGER',
  ACCOUNTANT = 'ACCOUNTANT',
  OWNER = 'OWNER',
  TENANT = 'TENANT',
  FAMILY_MEMBER = 'FAMILY_MEMBER',
  SECURITY_SUPERVISOR = 'SECURITY_SUPERVISOR',
  SECURITY_GUARD = 'SECURITY_GUARD',
  STAFF = 'STAFF',
  VENDOR = 'VENDOR',
}

export interface AuthPrincipal {
  userId: string;
  societyId?: string;
  roles: AppRole[];
}
