import { AppRole } from './auth.types';

export enum AppPermission {
  VISITOR_READ_OWN = 'VISITOR_READ_OWN',
  VISITOR_MANAGE_OWN = 'VISITOR_MANAGE_OWN',
  GATE_VISITOR_VERIFY = 'GATE_VISITOR_VERIFY',
  GATE_VISITOR_CHECK_IN_OUT = 'GATE_VISITOR_CHECK_IN_OUT',
  ACCESS_READ_OWN = 'ACCESS_READ_OWN',
  ACCESS_MANAGE_OWN = 'ACCESS_MANAGE_OWN',
  GATE_READ = 'GATE_READ',
  GATE_ACCESS_PROCESS = 'GATE_ACCESS_PROCESS',
  HOUSEHOLD_READ_OWN = 'HOUSEHOLD_READ_OWN',
  HOUSEHOLD_MANAGE_OWN = 'HOUSEHOLD_MANAGE_OWN',
  WORKFORCE_READ_OWN = 'WORKFORCE_READ_OWN',
  WORKFORCE_MANAGE_OWN = 'WORKFORCE_MANAGE_OWN',
  WORKFORCE_REVIEW = 'WORKFORCE_REVIEW',
  HELPDESK_READ_OWN = 'HELPDESK_READ_OWN',
  HELPDESK_MANAGE_OWN = 'HELPDESK_MANAGE_OWN',
  HELPDESK_REVIEW = 'HELPDESK_REVIEW',
  NOTICE_READ = 'NOTICE_READ',
  NOTICE_MANAGE = 'NOTICE_MANAGE',
  SOS_TRIGGER = 'SOS_TRIGGER',
  SOS_READ_OWN = 'SOS_READ_OWN',
  SOS_RESPOND = 'SOS_RESPOND',
  SOCIETY_CONFIGURATION_READ = 'SOCIETY_CONFIGURATION_READ',
  SOCIETY_CONFIGURATION_MANAGE = 'SOCIETY_CONFIGURATION_MANAGE',
  SERVICES_MARKETPLACE_USE = 'SERVICES_MARKETPLACE_USE',
  SERVICES_PROVIDER_MANAGE = 'SERVICES_PROVIDER_MANAGE',
  PLATFORM_PROVIDER_VERIFY = 'PLATFORM_PROVIDER_VERIFY',
  REPORTS_READ = 'REPORTS_READ',
  AUDIT_READ = 'AUDIT_READ',
  BILLING_READ_OWN = 'BILLING_READ_OWN',
  BILLING_MANAGE = 'BILLING_MANAGE',
  PAYMENT_CREATE_OWN = 'PAYMENT_CREATE_OWN',
  PAYMENT_RECONCILE = 'PAYMENT_RECONCILE',
}

export const ROLE_PERMISSIONS: Readonly<Record<AppRole, readonly AppPermission[]>> = {
  [AppRole.SUPER_ADMIN]: Object.values(AppPermission),
  [AppRole.SOCIETY_ADMIN]: [
    AppPermission.SOCIETY_CONFIGURATION_READ,
    AppPermission.SOCIETY_CONFIGURATION_MANAGE,
    AppPermission.GATE_READ,
    AppPermission.WORKFORCE_REVIEW,
    AppPermission.HELPDESK_REVIEW,
    AppPermission.NOTICE_READ,
    AppPermission.NOTICE_MANAGE,
    AppPermission.SOS_RESPOND,
    AppPermission.REPORTS_READ,
    AppPermission.AUDIT_READ,
    AppPermission.SERVICES_PROVIDER_MANAGE,
    AppPermission.BILLING_MANAGE,
    AppPermission.PAYMENT_RECONCILE,
  ],
  [AppRole.COMMITTEE_MEMBER]: [
    AppPermission.SOCIETY_CONFIGURATION_READ,
    AppPermission.GATE_READ,
    AppPermission.HELPDESK_REVIEW,
    AppPermission.NOTICE_READ,
    AppPermission.NOTICE_MANAGE,
    AppPermission.SOS_RESPOND,
    AppPermission.REPORTS_READ,
    AppPermission.AUDIT_READ,
  ],
  [AppRole.FACILITY_MANAGER]: [
    AppPermission.SOCIETY_CONFIGURATION_READ,
    AppPermission.GATE_READ,
    AppPermission.WORKFORCE_REVIEW,
    AppPermission.HELPDESK_REVIEW,
    AppPermission.NOTICE_READ,
    AppPermission.NOTICE_MANAGE,
    AppPermission.SOS_RESPOND,
    AppPermission.REPORTS_READ,
    AppPermission.SERVICES_PROVIDER_MANAGE,
  ],
  [AppRole.ACCOUNTANT]: [AppPermission.REPORTS_READ, AppPermission.BILLING_MANAGE, AppPermission.PAYMENT_RECONCILE],
  [AppRole.OWNER]: [
    AppPermission.VISITOR_READ_OWN,
    AppPermission.VISITOR_MANAGE_OWN,
    AppPermission.ACCESS_READ_OWN,
    AppPermission.ACCESS_MANAGE_OWN,
    AppPermission.HOUSEHOLD_READ_OWN,
    AppPermission.HOUSEHOLD_MANAGE_OWN,
    AppPermission.WORKFORCE_READ_OWN,
    AppPermission.WORKFORCE_MANAGE_OWN,
    AppPermission.HELPDESK_READ_OWN,
    AppPermission.HELPDESK_MANAGE_OWN,
    AppPermission.NOTICE_READ,
    AppPermission.SOS_TRIGGER,
    AppPermission.SOS_READ_OWN,
    AppPermission.SERVICES_MARKETPLACE_USE,
    AppPermission.BILLING_READ_OWN,
    AppPermission.PAYMENT_CREATE_OWN,
  ],
  [AppRole.TENANT]: [
    AppPermission.VISITOR_READ_OWN,
    AppPermission.VISITOR_MANAGE_OWN,
    AppPermission.ACCESS_READ_OWN,
    AppPermission.ACCESS_MANAGE_OWN,
    AppPermission.HOUSEHOLD_READ_OWN,
    AppPermission.HOUSEHOLD_MANAGE_OWN,
    AppPermission.WORKFORCE_READ_OWN,
    AppPermission.WORKFORCE_MANAGE_OWN,
    AppPermission.HELPDESK_READ_OWN,
    AppPermission.HELPDESK_MANAGE_OWN,
    AppPermission.NOTICE_READ,
    AppPermission.SOS_TRIGGER,
    AppPermission.SOS_READ_OWN,
    AppPermission.SERVICES_MARKETPLACE_USE,
    AppPermission.BILLING_READ_OWN,
    AppPermission.PAYMENT_CREATE_OWN,
  ],
  [AppRole.FAMILY_MEMBER]: [
    AppPermission.VISITOR_READ_OWN,
    AppPermission.VISITOR_MANAGE_OWN,
    AppPermission.ACCESS_READ_OWN,
    AppPermission.ACCESS_MANAGE_OWN,
    AppPermission.HOUSEHOLD_READ_OWN,
    AppPermission.WORKFORCE_READ_OWN,
    AppPermission.HELPDESK_READ_OWN,
    AppPermission.HELPDESK_MANAGE_OWN,
    AppPermission.NOTICE_READ,
    AppPermission.SOS_TRIGGER,
    AppPermission.SOS_READ_OWN,
    AppPermission.SERVICES_MARKETPLACE_USE,
  ],
  [AppRole.SECURITY_SUPERVISOR]: [
    AppPermission.GATE_READ,
    AppPermission.GATE_VISITOR_VERIFY,
    AppPermission.GATE_VISITOR_CHECK_IN_OUT,
    AppPermission.GATE_ACCESS_PROCESS,
    AppPermission.SOS_RESPOND,
    AppPermission.AUDIT_READ,
  ],
  [AppRole.SECURITY_GUARD]: [
    AppPermission.GATE_READ,
    AppPermission.GATE_VISITOR_VERIFY,
    AppPermission.GATE_VISITOR_CHECK_IN_OUT,
    AppPermission.GATE_ACCESS_PROCESS,
    AppPermission.SOS_RESPOND,
  ],
  [AppRole.STAFF]: [],
  [AppRole.VENDOR]: [],
};

export function hasPermission(roles: readonly AppRole[], permission: AppPermission): boolean {
  return roles.some((role) => ROLE_PERMISSIONS[role]?.includes(permission));
}
