'use client'

import { FormEvent,useEffect,useMemo,useState } from 'react'
import { api, type Session } from '../../../lib/admin-client'

type Tier='STANDARD'|'TRUSTED'|'PREMIUM'
type Recommendation={providerId:string;businessName:string;ratingCount:number;averageStars:number|null;completedJobs:number;earnedQualityTier:Tier;currentQualityTier:Tier;qualityNote:string|null;reviewedByUserId:string|null;reviewedAt:string|null;reviewNeeded:boolean}
function session():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw):null}catch{return null}}

export default function ProviderTrustReviewPage(){
  const[s,setS]=useState<Session|null>(null),[rows,setRows]=useState<Recommendation[]>([]),[selected,setSelected]=useState<Recommendation|null>(null),[tier,setTier]=useState<Tier>('STANDARD'),[note,setNote]=useState(''),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  useEffect(()=>{const x=session();setS(x);if(x)void load(x)},[])
  async function load(x=s){if(!x)return;setBusy(true);setError('');try{const data=await api<Recommendation[]>('/platform/services/provider-trust/recommendations',{},x);setRows(data);if(selected){const next=data.find(r=>r.providerId===selected.providerId)??null;setSelected(next)}}catch(e){setError(e instanceof Error?e.message:'Could not load trust recommendations')}finally{setBusy(false)}}
  function choose(row:Recommendation){setSelected(row);setTier(row.currentQualityTier);setNote(row.qualityNote??'')}
  async function review(e:FormEvent){e.preventDefault();if(!s||!selected||!note.trim())return;setBusy(true);setError('');try{await api(`/platform/services/provider-trust/providers/${selected.providerId}`,{method:'PATCH',body:JSON.stringify({qualityTier:tier,note:note.trim()})},s);await load(s)}catch(e){setError(e instanceof Error?e.message:'Could not save trust review')}finally{setBusy(false)}}
  const visible=useMemo(()=>{const q=query.trim().toLowerCase();return rows.filter(r=>!q||[r.businessName,r.earnedQualityTier,r.currentQualityTier].join(' ').toLowerCase().includes(q))},[rows,query])
  const reviewNeeded=rows.filter(r=>r.reviewNeeded).length
  if(!s)return <main style={{padding:32}}><h1>Platform access required</h1><a href="/">Return to Admin</a></main>
  return <main style={{maxWidth:1180,margin:'0 auto',padding:'28px 22px 80px'}}><header><small>Platform operations · {s.role.replaceAll('_',' ')}</small><h1>Provider trust review</h1><p>Earned recommendation is evidence only. Public trust tier changes require explicit platform review.</p><a href="/platform/providers">← Provider verification</a></header>{error&&<p style={{padding:12,background:'#fee2e2',borderRadius:10}}>{error}</p>}<section style={grid}><div style={panel}><div style={row}><div><h2 style={{margin:0}}>Review queue</h2><small>{reviewNeeded} review needed · {rows.length} verified providers</small></div><button onClick={()=>void load()} disabled={busy} style={button}>Refresh</button></div><input aria-label="Search trust recommendations" placeholder="Search provider or tier" value={query} onChange={e=>setQuery(e.target.value)} style={{...input,margin:'14px 0'}}/>{visible.length===0?<p>No matching providers.</p>:visible.map(r=><button key={r.providerId} onClick={()=>choose(r)} style={{...item,textAlign:'left',width:'100%',background:selected?.providerId===r.providerId?'#f0fdfa':'white'}}><span><b>{r.businessName}</b><br/><small>{r.completedJobs} completed · {r.ratingCount} ratings · {r.averageStars??'—'}★</small></span><span><b>{r.currentQualityTier}</b><br/><small>earned {r.earnedQualityTier}{r.reviewNeeded?' · review needed':''}</small></span></button>)}</div><div style={panel}>{selected?<><h2>{selected.businessName}</h2><div style={metrics}><div><small>Current</small><b>{selected.currentQualityTier}</b></div><div><small>Earned</small><b>{selected.earnedQualityTier}</b></div><div><small>Completed</small><b>{selected.completedJobs}</b></div><div><small>Rating</small><b>{selected.averageStars??'—'}</b></div></div><form onSubmit={review} style={{display:'grid',gap:12,marginTop:18}}><label>Reviewed public tier<select value={tier} onChange={e=>setTier(e.target.value as Tier)} style={input}><option>STANDARD</option><option>TRUSTED</option><option>PREMIUM</option></select></label><label>Review note<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={1000} rows={5} style={input}/></label><button disabled={busy||!note.trim()} style={button}>Save reviewed tier</button></form>{selected.reviewedAt&&<p><small>Last reviewed {new Date(selected.reviewedAt).toLocaleString('en-IN')}</small></p>}</>:<p>Select a provider to review evidence.</p>}<div style={noteBox}><b>Trust boundary</b><p style={{marginBottom:0}}>Featured/Sponsored placement is commercial and never changes earned or reviewed trust. Provider verification also remains a separate platform decision.</p></div></div></section></main>}
const panel={background:'white',border:'1px solid #e5e7eb',borderRadius:16,padding:18} as const,grid={display:'grid',gridTemplateColumns:'minmax(0,1.3fr) minmax(320px,.7fr)',gap:18,marginTop:20} as const,row={display:'flex',justifyContent:'space-between',alignItems:'center',gap:12} as const,item={display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',padding:'12px 0',border:0,borderBottom:'1px solid #e5e7eb',cursor:'pointer'} as const,metrics={display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:10} as const,input={display:'block',width:'100%',padding:'10px 12px',border:'1px solid #d1d5db',borderRadius:9,marginTop:5,boxSizing:'border-box'} as const,button={padding:'10px 14px',border:0,borderRadius:9,background:'#111827',color:'white',fontWeight:700,cursor:'pointer'} as const,noteBox={marginTop:18,padding:14,borderRadius:12,background:'#f8fafc'} as const