'use client'

import { useCallback, useEffect, useState } from 'react'

type Session={accessToken:string;role:string}
type Summary={windowDays:number;bookings30d:number;completed30d:number;cancelled30d:number;completionRate30d:number;cancellationRate30d:number;homeBookings30d:number;societyUnitBookings30d:number;homeBookingShare30d:number;societyUnitBookingShare30d:number;activeVerifiedProviders:number;activeCommercialPlacements:number;repeatCustomers90d:number}
type AttentionReason='REQUEST_AWAITING_CONFIRMATION'|'CONFIRMED_NOT_STARTED'|'IN_PROGRESS_OVERRUN'
type AttentionItem={bookingId:string;status:'REQUESTED'|'CONFIRMED'|'IN_PROGRESS';scheduledStart:string;scheduledEnd:string;createdAt:string;updatedAt:string;offeringName:string;providerName:string;reason:AttentionReason;attentionAgeMinutes:number}
type AttentionQueue={thresholds:{requestConfirmationMinutes:number;confirmedStartGraceMinutes:number;inProgressOverrunMinutes:number};items:AttentionItem[]}
type ProviderResponsivenessRow={providerId:string;providerName:string;requests30d:number;providerResponses30d:number;providerAccepted30d:number;providerDeclined30d:number;averageResponseMinutes30d:number;openRequestedNow:number;providerResponseRate30d:number}
type ProviderResponsiveness={windowDays:number;providers:ProviderResponsivenessRow[]}
const base=(process.env.NEXT_PUBLIC_AARAGATE_API_BASE_URL??'http://localhost:3000').replace(/\/$/,'')
function storedSession():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw) as Session:null}catch{return null}}
async function getJson<T>(s:Session,path:string):Promise<T>{const r=await fetch(`${base}/api/v1${path}`,{headers:{Accept:'application/json',Authorization:`Bearer ${s.accessToken}`}});const text=await r.text();const body=text?JSON.parse(text):null;if(!r.ok)throw new Error(body?.message??`Request failed (${r.status})`);return body as T}
function percent(value:number){return `${(value*100).toFixed(1)}%`}
function dateTime(value:string){return new Date(value).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}
function age(minutes:number){if(minutes<60)return `${minutes} min`;const hours=Math.floor(minutes/60),mins=minutes%60;return `${hours}h${mins?` ${mins}m`:''}`}
function reasonLabel(reason:AttentionReason){switch(reason){case'REQUEST_AWAITING_CONFIRMATION':return'Awaiting confirmation';case'CONFIRMED_NOT_STARTED':return'Confirmed but not started';case'IN_PROGRESS_OVERRUN':return'In progress beyond scheduled end'}}

export default function ExternalServicesOperationsPage(){
  const[session,setSession]=useState<Session|null>(null),[summary,setSummary]=useState<Summary|null>(null),[attention,setAttention]=useState<AttentionQueue|null>(null),[responsiveness,setResponsiveness]=useState<ProviderResponsiveness|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const load=useCallback(async(s:Session)=>{setLoading(true);setError('');try{const[summaryData,attentionData,responsivenessData]=await Promise.all([getJson<Summary>(s,'/platform/services/operations/summary'),getJson<AttentionQueue>(s,'/platform/services/operations/attention'),getJson<ProviderResponsiveness>(s,'/platform/services/operations/provider-responsiveness')]);setSummary(summaryData);setAttention(attentionData);setResponsiveness(responsivenessData)}catch(e){setError(e instanceof Error?e.message:'Operations data could not be loaded')}finally{setLoading(false)}},[])
  useEffect(()=>{const s=storedSession();setSession(s);if(s?.role==='SUPER_ADMIN')void load(s);else setLoading(false)},[load])
  if(loading)return <main style={{padding:32}}>Loading External Services operations…</main>
  if(session?.role!=='SUPER_ADMIN')return <main style={{padding:32}}><h1>Super Admin access required</h1><p>External Services pilot telemetry is platform-only and read-only.</p><a href="/">Return to Admin</a></main>
  return <main style={{maxWidth:1180,margin:'0 auto',padding:'28px 22px 80px'}}>
    <header style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><small>Platform marketplace · pilot readiness</small><h1 style={{margin:'4px 0'}}>External Services operations</h1><p style={{margin:0,maxWidth:760}}>Read-only pilot health from marketplace system-of-record data. These metrics do not change bookings, provider trust, paid placement, payments or ranking.</p></div><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button onClick={()=>void load(session)} style={button}>Refresh</button><a href="/marketplace-control/commercial" style={linkButton}>Commercial controls</a><a href="/" style={linkButton}>Admin console</a></div></header>
    {error&&<div style={errorBox}>{error}</div>}
    {!summary&&!error?<section style={panel}><p>No operations data is available yet.</p></section>:summary&&<>
      <section style={{...panel,display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12}}>
        <Metric label={`Bookings · ${summary.windowDays}d`} value={summary.bookings30d.toLocaleString('en-IN')} hint="Created bookings"/>
        <Metric label="Independent homes" value={summary.homeBookings30d.toLocaleString('en-IN')} hint={`${percent(summary.homeBookingShare30d)} of bookings`}/>
        <Metric label="Society units" value={summary.societyUnitBookings30d.toLocaleString('en-IN')} hint={`${percent(summary.societyUnitBookingShare30d)} of bookings`}/>
        <Metric label="Completion rate" value={percent(summary.completionRate30d)} hint={`${summary.completed30d.toLocaleString('en-IN')} completed`}/>
        <Metric label="Cancellation rate" value={percent(summary.cancellationRate30d)} hint={`${summary.cancelled30d.toLocaleString('en-IN')} cancelled`}/>
        <Metric label="Verified providers" value={summary.activeVerifiedProviders.toLocaleString('en-IN')} hint="Active and verified"/>
        <Metric label="Paid placements" value={summary.activeCommercialPlacements.toLocaleString('en-IN')} hint="Active Featured / Sponsored"/>
        <Metric label="Repeat customers · 90d" value={summary.repeatCustomers90d.toLocaleString('en-IN')} hint="2+ completed services"/>
      </section>
      <section style={panel}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start',flexWrap:'wrap'}}><div><h2 style={{margin:'0 0 5px'}}>Needs attention</h2><p style={{margin:0}}>Read-only exception queue for active bookings whose lifecycle has stalled beyond conservative pilot thresholds.</p></div><strong>{attention?.items.length??0} open</strong></div>{!attention||attention.items.length===0?<p style={{marginBottom:0}}>No active bookings currently exceed the attention thresholds.</p>:<div style={{display:'grid',gap:10,marginTop:16}}>{attention.items.map(item=><article key={item.bookingId} style={attentionCard}><div style={{flex:1,minWidth:250}}><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><strong>{item.offeringName}</strong><span style={pill}>{item.status.replaceAll('_',' ')}</span></div><div>{item.providerName}</div><small>Booking {item.bookingId}</small><div style={{marginTop:5}}>{reasonLabel(item.reason)} · attention age {age(item.attentionAgeMinutes)}</div><small>Scheduled {dateTime(item.scheduledStart)} → {dateTime(item.scheduledEnd)}</small></div><strong style={{color:'#b54708'}}>{reasonLabel(item.reason)}</strong></article>)}</div>}<p style={{margin:'14px 0 0',fontSize:13,color:'#475569'}}>Thresholds: requested for {attention?.thresholds.requestConfirmationMinutes??120} min without confirmation; confirmed {attention?.thresholds.confirmedStartGraceMinutes??30} min past scheduled start; in progress {attention?.thresholds.inProgressOverrunMinutes??60} min past scheduled end. Resolve through the existing permission-protected fulfilment workflow.</p></section>
      <section style={panel}><div><h2 style={{margin:'0 0 5px'}}>Provider responsiveness · {responsiveness?.windowDays??30}d</h2><p style={{margin:0}}>Derived only from explicit provider ACCEPT / DECLINE audit events. Platform-operated transitions are not counted as provider responses.</p></div>{!responsiveness||responsiveness.providers.length===0?<p style={{marginBottom:0}}>No provider booking activity is available in this window.</p>:<div style={{overflowX:'auto',marginTop:16}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:760}}><thead><tr><Th>Provider</Th><Th>Requests</Th><Th>Response rate</Th><Th>Accepted</Th><Th>Declined</Th><Th>Avg response</Th><Th>Open now</Th></tr></thead><tbody>{responsiveness.providers.map(row=><tr key={row.providerId}><Td><strong>{row.providerName}</strong></Td><Td>{row.requests30d}</Td><Td>{percent(row.providerResponseRate30d)}</Td><Td>{row.providerAccepted30d}</Td><Td>{row.providerDeclined30d}</Td><Td>{row.providerResponses30d>0?age(row.averageResponseMinutes30d):'—'}</Td><Td><strong style={{color:row.openRequestedNow>0?'#b54708':'#027a48'}}>{row.openRequestedNow}</strong></Td></tr>)}</tbody></table></div>}<p style={{margin:'14px 0 0',fontSize:13,color:'#475569'}}>Pilot diagnostic only. Response rate and speed must not be used as provider verification, trust-tier, sponsored-placement, or resident-ranking signals without a separately reviewed product policy.</p></section>
      <section style={panel}><h2 style={{marginTop:0}}>Pilot interpretation</h2><div style={{display:'grid',gap:10}}><Signal title="Demand" text={`${summary.bookings30d.toLocaleString('en-IN')} bookings were created in the last ${summary.windowDays} days.`}/><Signal title="Channel adoption" text={`${summary.homeBookings30d.toLocaleString('en-IN')} bookings came from independent homes and ${summary.societyUnitBookings30d.toLocaleString('en-IN')} from society units. Track this split to validate the independent-home expansion without changing society access boundaries.`}/><Signal title="Fulfilment" text={`${summary.completed30d.toLocaleString('en-IN')} completed and ${summary.cancelled30d.toLocaleString('en-IN')} cancelled; track the trend before enabling commission or heavier automation.`}/><Signal title="Supply" text={`${summary.activeVerifiedProviders.toLocaleString('en-IN')} active verified providers are currently eligible for marketplace participation.`}/><Signal title="Retention" text={`${summary.repeatCustomers90d.toLocaleString('en-IN')} customers completed at least two services in the last 90 days.`}/></div></section>
      <section style={note}><strong>Read-only boundary</strong><p style={{margin:'6px 0 0'}}>This dashboard intentionally has no mutation actions. Provider verification, society approval, commercial placement, bookings and payments remain in their existing permission-protected workflows.</p></section>
    </>}
  </main>
}
function Metric({label,value,hint}:{label:string;value:string;hint:string}){return <article style={metric}><small>{label}</small><strong style={{fontSize:28,lineHeight:1.2}}>{value}</strong><span style={{fontSize:13,color:'#475569'}}>{hint}</span></article>}
function Signal({title,text}:{title:string;text:string}){return <div style={{padding:14,border:'1px solid #e2e8f0',borderRadius:12}}><strong>{title}</strong><p style={{margin:'5px 0 0'}}>{text}</p></div>}
function Th({children}:{children:React.ReactNode}){return <th style={{textAlign:'left',padding:'10px 8px',borderBottom:'1px solid #cbd5e1',fontSize:12,color:'#475569'}}>{children}</th>}
function Td({children}:{children:React.ReactNode}){return <td style={{padding:'11px 8px',borderBottom:'1px solid #e2e8f0',verticalAlign:'top'}}>{children}</td>}
const panel:React.CSSProperties={marginTop:20,padding:20,border:'1px solid #dbe7ea',borderRadius:16,background:'white'}
const metric:React.CSSProperties={display:'grid',gap:6,padding:16,border:'1px solid #e2e8f0',borderRadius:14,background:'#f8fafc'}
const attentionCard:React.CSSProperties={display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,padding:14,border:'1px solid #fed7aa',borderRadius:12,background:'#fffaf5',flexWrap:'wrap'}
const pill:React.CSSProperties={padding:'3px 7px',borderRadius:999,background:'#e2e8f0',fontSize:11,fontWeight:800}
const button:React.CSSProperties={padding:'10px 13px',borderRadius:10,border:'1px solid #05879A',background:'#05879A',color:'white',fontWeight:700,cursor:'pointer'}
const linkButton:React.CSSProperties={padding:'10px 13px',borderRadius:10,border:'1px solid #cbd5e1',background:'white',color:'#111827',fontWeight:700,textDecoration:'none'}
const errorBox:React.CSSProperties={marginTop:18,padding:12,border:'1px solid #ef4444',borderRadius:10}
const note:React.CSSProperties={marginTop:20,padding:16,border:'1px solid #bae6fd',borderRadius:14,background:'#f0f9ff'}
