'use client'

import { useEffect, useState } from 'react'
import { ActionBar, EmptyState, ErrorState, EvidenceGrid, FormField, PageHeader, PageShell, SecondaryButton } from '../../../components/admin-ui'

type Session={accessToken:string;role:string;societyName?:string}
type TrialRow={accountId:string;code:string;name:string;type:string;debitPaise:string;creditPaise:string;netDebitPaise:string}
type IncomeRow={accountId:string;code:string;name:string;type:string;amountPaise:string}
type Balance={asOf:string;accounts:Array<{accountId:string;code:string;name:string;type:string;amountPaise:string}>;currentResultPaise:string;assetTotalPaise:string;liabilityTotalPaise:string;equityTotalPaise:string;balanceCheckPaise:string}
type Defaulter={unitId:string;buildingName:string;unitNumber:string;outstandingPaise:string;openReceivableCount:number;maxDaysOverdue:number}
const base=(process.env.NEXT_PUBLIC_AARAGATE_API_BASE_URL??'http://localhost:3000').replace(/\/$/,'')
const readRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','COMMITTEE_MEMBER','ACCOUNTANT'])
const today=()=>new Date().toISOString().slice(0,10),firstDay=()=>`${today().slice(0,8)}01`
const money=(v:string|number|undefined)=>`₹${(Number(v??0)/100).toLocaleString('en-IN',{maximumFractionDigits:2})}`
function getSession():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw) as Session:null}catch{return null}}
async function api<T>(s:Session,path:string):Promise<T>{const r=await fetch(`${base}/api/v1${path}`,{headers:{Authorization:`Bearer ${s.accessToken}`}});const text=await r.text();const body=text?JSON.parse(text):null;if(!r.ok)throw new Error(Array.isArray(body?.message)?body.message.join(', '):body?.message??`Request failed (${r.status})`);return body as T}

export default function StatementsPage(){
 const[s,setS]=useState<Session|null>(null),[from,setFrom]=useState(firstDay()),[to,setTo]=useState(today()),[trial,setTrial]=useState<TrialRow[]>([]),[income,setIncome]=useState<IncomeRow[]>([]),[balance,setBalance]=useState<Balance|null>(null),[defaulters,setDefaulters]=useState<Defaulter[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 async function load(x:Session,f=from,t=to){setLoading(true);setError('');try{const[tb,ie,bs,df]=await Promise.all([api<TrialRow[]>(x,`/accounting/reports/trial-balance?asOf=${t}`),api<IncomeRow[]>(x,`/accounting/reports/income-expense?from=${f}&to=${t}`),api<Balance>(x,`/accounting/reports/balance-sheet?asOf=${t}`),api<Defaulter[]>(x,`/accounting/reports/defaulters?asOf=${t}`)]);setTrial(tb);setIncome(ie);setBalance(bs);setDefaulters(df)}catch(e){setError(e instanceof Error?e.message:'Could not load financial statements')}finally{setLoading(false)}}
 useEffect(()=>{const x=getSession();setS(x);if(x&&readRoles.has(x.role))void load(x);else setLoading(false)},[])
 if(!s||!readRoles.has(s.role))return <PageShell><PageHeader title="Finance access required"/></PageShell>
 return <PageShell><PageHeader context={s.societyName??'Current society'} title="Financial statements" description="Ledger-backed reports. Posted history remains immutable." actions={<a href="/finance">← Finance workspace</a>}/>{error&&<ErrorState title="Financial statements unavailable" description={error}/>}<ActionBar label="Statement period"><FormField label="From" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><FormField label="To" type="date" value={to} onChange={e=>setTo(e.target.value)}/><SecondaryButton loading={loading} onClick={()=>void load(s,from,to)}>Refresh</SecondaryButton></ActionBar>{loading?<p>Loading reports…</p>:<><section style={panel}><h2>Balance sheet · {to}</h2>{balance?<EvidenceGrid items={[{id:'assets',label:'Assets',value:money(balance.assetTotalPaise)},{id:'liabilities',label:'Liabilities',value:money(balance.liabilityTotalPaise)},{id:'equity',label:'Equity',value:money(balance.equityTotalPaise)},{id:'current-result',label:'Current result',value:money(balance.currentResultPaise)},{id:'balance-check',label:'Balance check',value:money(balance.balanceCheckPaise)}]}/>:<EmptyState title="No balance-sheet data"/>}</section><section style={panel}><h2>Income & expense · {from} – {to}</h2>{income.map(r=><div key={r.accountId} style={row}><span>{r.code} · {r.name} <small>({r.type})</small></span><b>{money(r.amountPaise)}</b></div>)}</section><section style={panel}><h2>Trial balance · {to}</h2>{trial.map(r=><div key={r.accountId} style={row}><span>{r.code} · {r.name}</span><span>Dr {money(r.debitPaise)} · Cr {money(r.creditPaise)}</span></div>)}</section><section style={panel}><h2>Defaulters · {to}</h2>{defaulters.length===0?<EmptyState title="No overdue balances"/>:defaulters.map(d=><div key={d.unitId} style={row}><span>{d.buildingName} · {d.unitNumber}<br/><small>{d.openReceivableCount} open · {d.maxDaysOverdue} days max overdue</small></span><b>{money(d.outstandingPaise)}</b></div>)}</section></>}</PageShell>
}
const panel:React.CSSProperties={marginTop:20,padding:20,border:'1px solid #dbe7ea',borderRadius:16,background:'white'},row:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:16,padding:'10px 0',borderBottom:'1px solid #eef2f7',flexWrap:'wrap'}
