'use client'

import { useEffect, useState } from 'react'
import { api, type Session } from '../lib/admin-client'
import type { Notice, Ticket } from '../lib/admin-domain-types'
import type { AdminView as View } from '../lib/admin-access'
import { Empty, Header, Metric } from './admin-ui-primitives'

export function AdminOverview({session,open,allowedViews}:{session:Session;open:(v:View)=>void;allowedViews:View[]}){const[tickets,setTickets]=useState<Ticket[]>([]),[notices,setNotices]=useState<Notice[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{setLoading(true);Promise.all([api<Ticket[]>('/helpdesk/review/queue',{},session),api<Notice[]>('/notices/manage',{},session)]).then(([t,n])=>{setTickets(t);setNotices(n)}).catch(e=>setError(String(e.message))).finally(()=>setLoading(false))},[session]);const active=tickets.filter(t=>!['RESOLVED','CLOSED'].includes(t.status)),canOpen=(view:View)=>allowedViews.includes(view);return <><Header title="Operations overview" society={session.societyName}/>{error&&<div className="error">{error}</div>}{loading?<section className="panel"><Empty text="Loading operational summary…"/></section>:<div className="grid"><Metric label="Open helpdesk" value={active.length}/><Metric label="Urgent tickets" value={active.filter(t=>t.priority==='URGENT').length}/><Metric label="Published notices" value={notices.filter(n=>n.status==='PUBLISHED').length}/><Metric label="Draft notices" value={notices.filter(n=>n.status==='DRAFT').length}/></div>}<div className="actions">{canOpen('residents')&&<button onClick={()=>open('residents')}><b>Owners & occupants</b><span>Manage unit relationships</span></button>}{canOpen('gates')&&<button onClick={()=>open('gates')}><b>Gate operations</b><span>Configure gates and review activity</span></button>}{canOpen('workforce')&&<button onClick={()=>open('workforce')}><b>Domestic-help operations</b><span>Review and control workforce access</span></button>}{['SUPER_ADMIN','SOCIETY_ADMIN','FACILITY_MANAGER','COMMITTEE_MEMBER','SECURITY_SUPERVISOR','AUDITOR'].includes(session.role)&&<button onClick={()=>{window.location.href='/society-workforce'}}><b>Society workforce</b><span>Common workers, shifts and gate attendance</span></button>}{canOpen('marketplace')&&<button onClick={()=>open('marketplace')}><b>Service marketplace</b><span>Approve providers and manage bookings</span></button>}{canOpen('sos')&&<button onClick={()=>open('sos')}><b>SOS response</b><span>Acknowledge and resolve emergencies</span></button>}{canOpen('helpdesk')&&<button onClick={()=>open('helpdesk')}><b>Helpdesk queue</b><span>Review resident issues</span></button>}{canOpen('notices')&&<button onClick={()=>open('notices')}><b>Notice management</b><span>Publish announcements</span></button>}{canOpen('billing')&&<button onClick={()=>open('billing')}><b>Maintenance billing</b><span>Issue and track unit invoices</span></button>}</div></>}

