'use client'

import { FormEvent, useCallback, useEffect, useState } from 'react'

type Session={sessionId:string;accessToken:string;refreshToken:string;societyId:string;role:string;societyName:string}
type Membership={societyId:string;role:string;society?:{name?:string;code?:string}}
type Ticket={id:string;title:string;description:string;category?:string;priority:string;status:string;buildingName?:string;unitNumber?:string;createdByName?:string}
type Activity={id:string;type:string;message?:string;actorName?:string;occurredAt:string}
type Notice={id:string;title:string;body:string;category?:string;status:string;createdAt:string}
const base=(process.env.NEXT_PUBLIC_AARAGATE_API_BASE_URL??'http://localhost:3000').replace(/\/$/,'')
const adminRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','COMMITTEE_MEMBER','FACILITY_MANAGER'])

async function api<T>(path:string,init:RequestInit={},session?:Session):Promise<T>{
  const response=await fetch(`${base}/api/v1${path}`,{...init,headers:{Accept:'application/json','Content-Type':'application/json',...(session?{Authorization:`Bearer ${session.accessToken}`} : {}),...init.headers}})
  const text=await response.text();const body=text?JSON.parse(text) as unknown:null
  if(!response.ok){const message=body&&typeof body==='object'&&'message'in body?String((body as {message:unknown}).message):`Request failed (${response.status})`;throw new Error(message)}
  return body as T
}
function sessionFrom(value:Record<string,unknown>,membership:Membership):Session{const s=value.session as Record<string,unknown>|undefined;if(!s?.sessionId||!s.accessToken||!s.refreshToken)throw new Error('Authentication returned an incomplete session');return{sessionId:String(s.sessionId),accessToken:String(s.accessToken),refreshToken:String(s.refreshToken),societyId:membership.societyId,role:membership.role,societyName:membership.society?.name??membership.society?.code??'Society'}}

export function AdminConsole(){
  const[session,setSession]=useState<Session|null>(null),[restoring,setRestoring]=useState(true),[view,setView]=useState<'overview'|'helpdesk'|'notices'>('overview')
  useEffect(()=>{const raw=sessionStorage.getItem('aaraagate.admin.session');if(!raw){setRestoring(false);return}try{const stored=JSON.parse(raw)as Session;api<Record<string,unknown>>('/auth/refresh',{method:'POST',body:JSON.stringify({sessionId:stored.sessionId,refreshToken:stored.refreshToken})}).then(next=>{const fresh={...stored,sessionId:String(next.sessionId),accessToken:String(next.accessToken),refreshToken:String(next.refreshToken)};sessionStorage.setItem('aaraagate.admin.session',JSON.stringify(fresh));setSession(fresh)}).catch(()=>sessionStorage.removeItem('aaraagate.admin.session')).finally(()=>setRestoring(false))}catch{sessionStorage.removeItem('aaraagate.admin.session');setRestoring(false)}},[])
  const accept=(next:Session)=>{if(!adminRoles.has(next.role))throw new Error('This role does not have Society Admin access');sessionStorage.setItem('aaraagate.admin.session',JSON.stringify(next));setSession(next)}
  const logout=async()=>{if(session)await api('/auth/logout',{method:'POST',body:JSON.stringify({sessionId:session.sessionId,refreshToken:session.refreshToken})}).catch(()=>undefined);sessionStorage.removeItem('aaraagate.admin.session');setSession(null)}
  if(restoring)return <div className="center">Restoring secure session…</div>;if(!session)return <Login onSession={accept}/>
  return <main className="shell"><aside className="sidebar"><div className="brand">aaraagate</div><div className="society"><small>Current society</small><strong>{session.societyName}</strong><span>{session.role.replaceAll('_',' ')}</span></div><nav className="nav">{(['overview','helpdesk','notices']as const).map(item=><button key={item} className={view===item?'active':''} onClick={()=>setView(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</nav><button className="signOut" onClick={()=>void logout()}>Sign out</button></aside><section className="content">{view==='overview'&&<Overview session={session} open={setView}/>} {view==='helpdesk'&&<Helpdesk session={session}/>} {view==='notices'&&<Notices session={session}/>}</section></main>
}

function Login({onSession}:{onSession:(s:Session)=>void}){
  const[stage,setStage]=useState<'phone'|'otp'|'society'>('phone'),[phone,setPhone]=useState('+91'),[otp,setOtp]=useState(''),[challenge,setChallenge]=useState(''),[userId,setUserId]=useState(''),[token,setToken]=useState(''),[memberships,setMemberships]=useState<Membership[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Authentication failed')}finally{setBusy(false)}}
  const send=(e:FormEvent)=>{e.preventDefault();void run(async()=>{const result=await api<{challengeId:string}>('/auth/otp/request',{method:'POST',body:JSON.stringify({phone:phone.trim()})});setChallenge(result.challengeId);setStage('otp')})}
  const verify=(e:FormEvent)=>{e.preventDefault();void run(async()=>{const result=await api<Record<string,unknown>>('/auth/otp/verify',{method:'POST',body:JSON.stringify({challengeId:challenge,code:otp})});const options=((result.memberships as Membership[])??[]).filter(m=>adminRoles.has(m.role));if(!options.length)throw new Error('No active Society Admin membership');setUserId(String(result.userId));setMemberships(options);if(result.session&&options.length===1)onSession(sessionFrom(result,options[0]));else{setToken(String(result.selectionToken??''));setStage('society')}})}
  const choose=(m:Membership)=>void run(async()=>{const result=await api<Record<string,unknown>>('/auth/society/select',{method:'POST',body:JSON.stringify({userId,societyId:m.societyId,selectionToken:token})});onSession(sessionFrom(result,m))})
  return <main className="login"><section className="loginCard"><div className="brand">aaraagate</div><h1>Admin sign in</h1><p>Secure society-scoped operational access.</p>{stage==='phone'&&<form onSubmit={send}><label>Mobile number<input value={phone} onChange={e=>setPhone(e.target.value)} required/></label><button className="primary" disabled={busy}>Send OTP</button></form>}{stage==='otp'&&<form onSubmit={verify}><label>6-digit OTP<input value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} minLength={6} maxLength={6} required/></label><button className="primary" disabled={busy||otp.length!==6}>Verify securely</button></form>}{stage==='society'&&<div className="choices">{memberships.map(m=><button key={`${m.societyId}-${m.role}`} onClick={()=>choose(m)}><strong>{m.society?.name??m.society?.code??'Society'}</strong><span>{m.role.replaceAll('_',' ')}</span></button>)}</div>}{busy&&<div className="progress"/>}{error&&<div className="error">{error}</div>}</section></main>
}

function Overview({session,open}:{session:Session;open:(v:'overview'|'helpdesk'|'notices')=>void}){const[tickets,setTickets]=useState<Ticket[]>([]),[notices,setNotices]=useState<Notice[]>([]),[error,setError]=useState('');useEffect(()=>{Promise.all([api<Ticket[]>('/helpdesk/review/queue',{},session),api<Notice[]>('/notices/manage',{},session)]).then(([t,n])=>{setTickets(t);setNotices(n)}).catch(e=>setError(String(e.message)))},[session]);const active=tickets.filter(t=>!['RESOLVED','CLOSED'].includes(t.status));return <><Header title="Operations overview" society={session.societyName}/>{error&&<div className="error">{error}</div>}<div className="grid"><Metric label="Open helpdesk" value={active.length}/><Metric label="Urgent tickets" value={active.filter(t=>t.priority==='URGENT').length}/><Metric label="Published notices" value={notices.filter(n=>n.status==='PUBLISHED').length}/><Metric label="Draft notices" value={notices.filter(n=>n.status==='DRAFT').length}/></div><div className="actions"><button onClick={()=>open('helpdesk')}><b>Helpdesk queue</b><span>Review resident issues</span></button><button onClick={()=>open('notices')}><b>Notice management</b><span>Publish announcements</span></button></div></>}

function Helpdesk({session}:{session:Session}){const[tickets,setTickets]=useState<Ticket[]>([]),[selected,setSelected]=useState<Ticket|null>(null),[activities,setActivities]=useState<Activity[]>([]),[comment,setComment]=useState(''),[error,setError]=useState('');const load=useCallback(()=>api<Ticket[]>('/helpdesk/review/queue',{},session).then(setTickets).catch(e=>setError(e.message)),[session]);useEffect(()=>{void load()},[load]);const select=async(t:Ticket)=>{setSelected(t);try{setActivities(await api<Activity[]>(`/helpdesk/review/${t.id}/activities`,{},session))}catch(e){setError(e instanceof Error?e.message:'Could not load activity')}};const status=async(value:string)=>{if(!selected)return;try{await api(`/helpdesk/review/${selected.id}/status`,{method:'PATCH',body:JSON.stringify({status:value})},session);setSelected({...selected,status:value});await load()}catch(e){setError(e instanceof Error?e.message:'Update failed')}};const note=async(e:FormEvent)=>{e.preventDefault();if(!selected)return;try{await api(`/helpdesk/review/${selected.id}/comments`,{method:'POST',body:JSON.stringify({message:comment})},session);setComment('');await select(selected)}catch(e){setError(e instanceof Error?e.message:'Comment failed')}};return <><Header title="Helpdesk queue" society="Resident support"/>{error&&<div className="error">{error}</div>}<div className="split"><section className="panel">{tickets.length===0?<Empty text="No helpdesk tickets"/>:tickets.map(t=><button className={`row ${selected?.id===t.id?'selected':''}`} key={t.id} onClick={()=>void select(t)}><div><b>{t.title}</b><span>{t.buildingName??'Building'} · {t.unitNumber??'Unit'}</span></div><div><Badge text={t.priority}/><Badge text={t.status}/></div></button>)}</section><section className="panel detail">{!selected?<Empty text="Select a ticket to review"/>:<><h2>{selected.title}</h2><p>{selected.description}</p><div className="buttons">{['OPEN','IN_PROGRESS','RESOLVED','CLOSED'].map(v=><button key={v} disabled={selected.status===v} onClick={()=>void status(v)}>{v.replaceAll('_',' ')}</button>)}</div><h3>Activity</h3>{activities.map(a=><div className="activity" key={a.id}><b>{a.type.replaceAll('_',' ')}</b><small>{a.actorName??'Admin'} · {new Date(a.occurredAt).toLocaleString()}</small>{a.message&&<p>{a.message}</p>}</div>)}<form className="note" onSubmit={note}><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add operational note" maxLength={1000}/><button className="primary" disabled={!comment.trim()}>Add</button></form></>}</section></div></>}

function Notices({session}:{session:Session}){const[list,setList]=useState<Notice[]>([]),[show,setShow]=useState(false),[title,setTitle]=useState(''),[body,setBody]=useState(''),[category,setCategory]=useState(''),[error,setError]=useState('');const load=useCallback(()=>api<Notice[]>('/notices/manage',{},session).then(setList).catch(e=>setError(e.message)),[session]);useEffect(()=>{void load()},[load]);const create=async(e:FormEvent)=>{e.preventDefault();try{await api('/notices/manage',{method:'POST',body:JSON.stringify({title,body,category:category||undefined})},session);setTitle('');setBody('');setCategory('');setShow(false);await load()}catch(e){setError(e instanceof Error?e.message:'Create failed')}};const act=async(n:Notice,value:'publish'|'archive')=>{try{await api(`/notices/manage/${n.id}/${value}`,{method:'PATCH',body:'{}'},session);await load()}catch(e){setError(e instanceof Error?e.message:'Update failed')}};return <><Header title="Notices" society="Community communication"/><button className="primary new" onClick={()=>setShow(!show)}>{show?'Cancel':'New notice'}</button>{error&&<div className="error">{error}</div>}{show&&<form className="panel form" onSubmit={create}><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} minLength={3} maxLength={160} required/></label><label>Category<input value={category} onChange={e=>setCategory(e.target.value)} maxLength={80}/></label><label className="wide">Notice<textarea value={body} onChange={e=>setBody(e.target.value)} minLength={5} maxLength={5000} required/></label><button className="primary">Save draft</button></form>}<div className="noticeGrid">{list.length===0?<Empty text="No notices created"/>:list.map(n=><article className="notice" key={n.id}><div><small>{n.category??'General'}</small><Badge text={n.status}/></div><h2>{n.title}</h2><p>{n.body}</p><div className="buttons">{n.status==='DRAFT'&&<button className="primary" onClick={()=>void act(n,'publish')}>Publish</button>}{n.status!=='ARCHIVED'&&<button onClick={()=>void act(n,'archive')}>Archive</button>}</div></article>)}</div></>}

function Header({title,society}:{title:string;society:string}){return <header><small>{society}</small><h1>{title}</h1></header>};function Metric({label,value}:{label:string;value:number}){return <div className="metric"><span>{label}</span><b>{value}</b></div>};function Badge({text}:{text:string}){return <span className={`badge ${text.toLowerCase()}`}>{text.replaceAll('_',' ')}</span>};function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
