from pathlib import Path

path = Path('apps/resident/lib/data/demo_resident_repository.dart')
text = path.read_text()

start_marker = "  final List<Map<String, dynamic>> _offerings = const ["
end_marker = "\n  ];\n\n  @override\n  Future<List<Map<String, dynamic>>> serviceOfferings"
start = text.index(start_marker)
end = text.index(end_marker, start) + len("\n  ];")

offerings = '''  final List<Map<String, dynamic>> _offerings = const [
    {
      'id': 'demo-offering-1',
      'categoryId': 'demo-category-1',
      'name': 'AC service',
      'description': 'General inspection, filter cleaning and basic servicing',
      'pricePaise': 59900,
      'durationMinutes': 55,
      'provider': {
        'id': 'demo-provider-coolcare',
        'businessName': 'CoolCare Services',
        'description': 'Home AC servicing and cooling-system maintenance specialists.',
        'ratingAverage': 4.8,
        'ratingCount': 184,
        'completedJobs': 612,
      },
    },
    {
      'id': 'demo-offering-1b',
      'categoryId': 'demo-category-1',
      'name': 'AC service',
      'description': 'AC inspection, coil cleaning and performance check',
      'pricePaise': 69900,
      'durationMinutes': 60,
      'provider': {
        'id': 'demo-provider-airpro',
        'businessName': 'AirPro Home Care',
        'description': 'Verified residential AC and appliance service team.',
        'ratingAverage': 4.6,
        'ratingCount': 126,
        'completedJobs': 438,
      },
    },
    {
      'id': 'demo-offering-1c',
      'categoryId': 'demo-category-1',
      'name': 'AC service',
      'description': 'Routine split/window AC service with drain-line check',
      'pricePaise': 79900,
      'durationMinutes': 70,
      'provider': {
        'id': 'demo-provider-freshair',
        'businessName': 'FreshAir Technical Services',
        'description': 'Society-approved technicians for AC service and repair visits.',
        'ratingAverage': 4.9,
        'ratingCount': 92,
        'completedJobs': 321,
      },
    },
    {
      'id': 'demo-offering-2',
      'categoryId': 'demo-category-2',
      'name': 'Deep cleaning',
      'description': '2 BHK home deep-cleaning package',
      'pricePaise': 149900,
      'durationMinutes': 240,
      'provider': {
        'id': 'demo-provider-neatnest',
        'businessName': 'NeatNest Home Services',
        'description': 'Deep cleaning and move-in/move-out cleaning specialists.',
        'ratingAverage': 4.7,
        'ratingCount': 211,
        'completedJobs': 705,
      },
    },
    {
      'id': 'demo-offering-2b',
      'categoryId': 'demo-category-2',
      'name': 'Deep cleaning',
      'description': '2 BHK intensive kitchen, bathroom and floor cleaning',
      'pricePaise': 169900,
      'durationMinutes': 270,
      'provider': {
        'id': 'demo-provider-sparkle',
        'businessName': 'SparkleCrew',
        'description': 'Background-verified home cleaning professionals.',
        'ratingAverage': 4.5,
        'ratingCount': 153,
        'completedJobs': 489,
      },
    },
    {
      'id': 'demo-offering-3',
      'categoryId': 'demo-category-3',
      'name': 'Electrician visit',
      'description': 'Switch, fan and light troubleshooting visit',
      'pricePaise': 24900,
      'durationMinutes': 45,
      'provider': {
        'id': 'demo-provider-powerfix',
        'businessName': 'PowerFix Electricals',
        'description': 'Residential electrical repair and installation services.',
        'ratingAverage': 4.8,
        'ratingCount': 167,
        'completedJobs': 544,
      },
    },
    {
      'id': 'demo-offering-3b',
      'categoryId': 'demo-category-3',
      'name': 'Electrician visit',
      'description': 'Electrical fault inspection and minor repair visit',
      'pricePaise': 29900,
      'durationMinutes': 50,
      'provider': {
        'id': 'demo-provider-voltwise',
        'businessName': 'VoltWise Services',
        'description': 'Society-approved electricians for household jobs.',
        'ratingAverage': 4.6,
        'ratingCount': 118,
        'completedJobs': 376,
      },
    },
    {
      'id': 'demo-offering-4',
      'categoryId': 'demo-category-4',
      'name': 'Plumber visit',
      'description': 'Tap, flush and minor leakage repair visit',
      'pricePaise': 29900,
      'durationMinutes': 45,
      'provider': {
        'id': 'demo-provider-flowcare',
        'businessName': 'FlowCare Plumbing',
        'description': 'Household plumbing maintenance and leak-fix professionals.',
        'ratingAverage': 4.7,
        'ratingCount': 142,
        'completedJobs': 463,
      },
    },
    {
      'id': 'demo-offering-4b',
      'categoryId': 'demo-category-4',
      'name': 'Plumber visit',
      'description': 'Minor plumbing repair and fitting inspection',
      'pricePaise': 34900,
      'durationMinutes': 50,
      'provider': {
        'id': 'demo-provider-pipepro',
        'businessName': 'PipePro Home Repairs',
        'description': 'Verified plumbing and sanitary fitting service team.',
        'ratingAverage': 4.5,
        'ratingCount': 97,
        'completedJobs': 301,
      },
    },
    {
      'id': 'demo-offering-5',
      'categoryId': 'demo-category-5',
      'name': 'Washing machine service',
      'description': 'Inspection and basic repair visit',
      'pricePaise': 44900,
      'durationMinutes': 60,
      'provider': {
        'id': 'demo-provider-appliancecare',
        'businessName': 'ApplianceCare Plus',
        'description': 'Multi-brand washing machine and refrigerator service.',
        'ratingAverage': 4.7,
        'ratingCount': 136,
        'completedJobs': 420,
      },
    },
    {
      'id': 'demo-offering-5b',
      'categoryId': 'demo-category-5',
      'name': 'Washing machine service',
      'description': 'Diagnostic visit for common washer faults',
      'pricePaise': 54900,
      'durationMinutes': 70,
      'provider': {
        'id': 'demo-provider-hometech',
        'businessName': 'HomeTech Repairs',
        'description': 'Society-approved home appliance repair technicians.',
        'ratingAverage': 4.6,
        'ratingCount': 109,
        'completedJobs': 358,
      },
    },
    {
      'id': 'demo-offering-6',
      'categoryId': 'demo-category-6',
      'name': 'Salon at home',
      'description': 'Basic grooming package at home',
      'pricePaise': 79900,
      'durationMinutes': 75,
      'provider': {
        'id': 'demo-provider-glowdoor',
        'businessName': 'GlowDoor Beauty',
        'description': 'Verified at-home grooming and beauty professionals.',
        'ratingAverage': 4.8,
        'ratingCount': 201,
        'completedJobs': 669,
      },
    },
    {
      'id': 'demo-offering-6b',
      'categoryId': 'demo-category-6',
      'name': 'Salon at home',
      'description': 'At-home grooming and self-care package',
      'pricePaise': 89900,
      'durationMinutes': 90,
      'provider': {
        'id': 'demo-provider-carecanvas',
        'businessName': 'CareCanvas Home Salon',
        'description': 'Society-approved home salon professionals.',
        'ratingAverage': 4.6,
        'ratingCount': 144,
        'completedJobs': 452,
      },
    },
  ];'''

text = text[:start] + offerings + text[end:]
path.write_text(text)
print('Resident demo marketplace fixture enriched with realistic multi-provider offerings.')
