'use client'
import { FormEvent,useCallback,useEffect,useState } from 'react'

type Session={accessToken:string;role:string;societyName?:string}
type Receivable={id:string;receivableNumber:string;description:string;outstandingPaise:string}
type Waiver={id:string;entryNumber:string;entryDate:string;description:string;status:string;sourceType:string;sourceId?:string;externalReference?:string;createdByUserId:string;postedByUserId?:string|null;postedAt?:string|null}
const base=(process.env.NEXT_PUBLIC_AARAGATE_API_BASE_URL??'http://localhost:3000').replace(/\/$/,'')
const manageRoles=new Set(['SUPER_ADMIN','ACCOUNTANT'])
function getSession():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw) as Session:null}catch{return null}}
async function api<T>(s:Session,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${base}/api/v1${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.accessToken}`,...init.headers}});const t=await r.text();const b=t?JSON.parse(t):null;if(!r.ok)throw new Error(Array.isArray(b?.message)?b.message.join(', '):b?.message??`Request failed (${r.status})`);return b as T}
const money=(v:string|number)=>`₹${(Number(v)/100).toLocaleString('en-IN',{maximumFractionDigits:2})}`
const today=()=>new Date().toISOString().slice(0,10)
export default function WaiverWorkspace(){
 const[session,setSession]=useState<Session|null>(null),[rows,setRows]=useState<Waiver[]>([]),[receivables,setReceivables]=useState<Receivable[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const[receivableId,setReceivableId]=useState(''),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[entryNumber,setEntryNumber]=useState(''),[requestKey,setRequestKey]=useState('')
 const load=useCallback(async(s:Session)=>{setError('');try{const[w,r]=await Promise.all([api<Waiver[]>(s,'/accounting/waivers/requests'),api<Receivable[]>(s,'/accounting/receivables')]);setRows(w);setReceivables(r)}catch(e){setError(e instanceof Error?e.message:'Could not load waiver controls')}},[])
 useEffect(()=>{const s=getSession();setSession(s);if(s)void load(s)},[load])
 const canManage=!!session&&manageRoles.has(session.role)
 async function submit(e:FormEvent){e.preventDefault();if(!session||!canManage)return;const rupees=Number(amount);if(!Number.isFinite(rupees)||rupees<=0){setError('Enter a positive waiver amount.');return}setBusy(true);setError('');try{await api(session,'/accounting/waivers/requests',{method:'POST',body:JSON.stringify({receivableId,amountPaise:Math.round(rupees*100),reason,entryDate:today(),journalEntryNumber:entryNumber,requestKey})});setAmount('');setReason('');setEntryNumber('');setRequestKey('');await load(session)}catch(e){setError(e instanceof Error?e.message:'Could not submit waiver request')}finally{setBusy(false)}}
 async function review(id:string,decision:'approve'|'reject'){if(!session||!canManage)return;if(!confirm(`${decision==='approve'?'Approve':'Reject'} this waiver request? The requester cannot review their own request.`))return;setBusy(true);setError('');try{await api(session,`/accounting/waivers/requests/${id}/${decision}`,{method:'POST',body:decision==='reject'?JSON.stringify({reason:'Rejected from finance workspace'}):undefined});await load(session)}catch(e){setError(e instanceof Error?e.message:'Could not review waiver request')}finally{setBusy(false)}}
 if(!session)return <main style={{padding:32}}><h1>Finance access required</h1></main>
 return <main style={{maxWidth:1240,margin:'0 auto',padding:'28px 22px 80px'}}><header><small>{session.societyName??'Current society'} · {session.role.replaceAll('_',' ')}</small><h1>Waiver approvals</h1><p>Maker–checker control for high-impact receivable waivers. Debit and credit notes remain append-only finance adjustments; waivers require a different finance reviewer.</p></header>{error&&<div role="alert" style={{margin:'16px 0',padding:12,border:'1px solid #d33',borderRadius:12}}>{error}</div>}
 {canManage&&<section style={panel}><h2>Request waiver</h2><form onSubmit={submit} style={{display:'grid',gap:12,gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))'}}><label>Receivable<select required value={receivableId} onChange={e=>setReceivableId(e.target.value)} style={input}><option value="">Choose receivable</option>{receivables.filter(r=>Number(r.outstandingPaise)>0).map(r=><option key={r.id} value={r.id}>{r.receivableNumber} · {money(r.outstandingPaise)}</option>)}</select></label><label>Amount (₹)<input required type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} style={input}/></label><label>Journal number<input required value={entryNumber} onChange={e=>setEntryNumber(e.target.value)} placeholder="WV-2026-0001" style={input}/></label><label>Stable request key<input required value={requestKey} onChange={e=>setRequestKey(e.target.value)} placeholder="waiver-unit-period-001" style={input}/></label><label style={{gridColumn:'1/-1'}}>Reason<textarea required value={reason} onChange={e=>setReason(e.target.value)} style={{...input,minHeight:90}}/></label><button disabled={busy||!receivableId||!amount||!reason||!entryNumber||!requestKey} style={primary}>Submit for approval</button></form></section>}
 <section style={panel}><h2>Waiver requests</h2>{rows.length===0?<p>No waiver requests.</p>:<div style={{display:'grid',gap:10}}>{rows.map(w=><article key={w.id} style={{padding:14,border:'1px solid #e1ecee',borderRadius:14}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><b>{w.entryNumber}</b> · {w.description}<br/><small>{w.sourceType==='WAIVER_REQUEST'&&w.status==='DRAFT'?'PENDING APPROVAL':w.sourceType==='WAIVER_REQUEST_REJECTED'?'REJECTED':w.status} · {new Date(w.entryDate).toLocaleDateString('en-IN')}</small></div>{canManage&&w.sourceType==='WAIVER_REQUEST'&&w.status==='DRAFT'&&<div style={{display:'flex',gap:8}}><button disabled={busy} style={primary} onClick={()=>void review(w.id,'approve')}>Approve</button><button disabled={busy} style={secondary} onClick={()=>void review(w.id,'reject')}>Reject</button></div>}</div></article>)}</div>}</section></main>
}
const panel={marginTop:18,padding:20,border:'1px solid #d5e8eb',borderRadius:18,background:'#fff'} as const
const input={width:'100%',boxSizing:'border-box' as const,marginTop:6,padding:'10px 12px',border:'1px solid #c8dce0',borderRadius:11}
const primary={padding:'10px 16px',border:0,borderRadius:11,fontWeight:800,cursor:'pointer',background:'#0eabbe',color:'#fff'} as const
const secondary={...primary,background:'#eef7f8',color:'#17323a',border:'1px solid #d5e8eb'} as const
