'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'

type Session={accessToken:string;role:string;societyName?:string}
type ParkingRow={householdId:string;unit:{id:string;number:string;building:{id:string;name:string;code:string}};vehicle:{id:string;plateNumber:string;vehicleType:string;make?:string|null;model?:string|null;color?:string|null};parkingSlot?:string|null}
const base=(process.env.NEXT_PUBLIC_AARAGATE_API_BASE_URL??'http://localhost:3000').replace(/\/$/,'')
function getSession():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw) as Session:null}catch{return null}}
async function api<T>(s:Session,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${base}/api/v1${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.accessToken}`,...init.headers}});const t=await r.text();const b=t?JSON.parse(t):null;if(!r.ok)throw new Error(b?.message??`Request failed (${r.status})`);return b as T}

export default function ParkingPage(){
  const[session,setSession]=useState<Session|null>(null),[rows,setRows]=useState<ParkingRow[]>([]),[loading,setLoading]=useState(true),[busyId,setBusyId]=useState(''),[error,setError]=useState(''),[query,setQuery]=useState('')
  const allowed=(s:Session|null)=>!!s&&['SUPER_ADMIN','SOCIETY_ADMIN'].includes(s.role)
  const load=useCallback(async(s:Session)=>{setLoading(true);setError('');try{setRows(await api<ParkingRow[]>(s,'/parking/admin'))}catch(e){setError(e instanceof Error?e.message:'Could not load parking')}finally{setLoading(false)}},[])
  useEffect(()=>{const s=getSession();setSession(s);if(s&&allowed(s))void load(s);else setLoading(false)},[load])
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return rows;return rows.filter(r=>[r.vehicle.plateNumber,r.unit.number,r.unit.building.name,r.parkingSlot??'',r.vehicle.make??'',r.vehicle.model??''].some(v=>v.toLowerCase().includes(q)))},[rows,query])
  const update=async(row:ParkingRow)=>{if(!session)return;const value=prompt(`Parking bay for ${row.vehicle.plateNumber}. Leave blank to clear.`,row.parkingSlot??'');if(value===null)return;setBusyId(row.vehicle.id);setError('');try{await api(session,`/parking/admin/${row.householdId}/vehicles/${row.vehicle.id}`,{method:'PATCH',body:JSON.stringify({parkingSlot:value.trim()||undefined})});await load(session)}catch(e){setError(e instanceof Error?e.message:'Could not update parking')}finally{setBusyId('')}}
  if(loading)return <main style={{padding:32}}>Loading parking assignments…</main>
  if(!allowed(session))return <main style={{padding:32}}><h1>Society administration required</h1><a href="/">Return to Admin</a></main>
  return <main style={{maxWidth:1120,margin:'0 auto',padding:'28px 22px 80px'}}><header style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><small>{session?.societyName??'Current society'}</small><h1 style={{margin:'4px 0'}}>Vehicle & parking management</h1><p style={{margin:0}}>Residents register vehicles; society administration owns bay assignment and changes.</p></div><a href="/">← Admin console</a></header>{error&&<div style={errorBox}>{error}</div>}<section style={panel}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><b>{rows.length} active vehicles</b><div><small>{rows.filter(r=>r.parkingSlot).length} assigned · {rows.filter(r=>!r.parkingSlot).length} unassigned</small></div></div><input aria-label="Search vehicles" placeholder="Search plate, unit or bay" value={query} onChange={e=>setQuery(e.target.value)} style={{padding:11,border:'1px solid #cbd5e1',borderRadius:10,minWidth:260}}/></div><div style={{display:'grid',gap:10,marginTop:16}}>{filtered.length===0?<p>No matching active vehicles.</p>:filtered.map(row=><article key={row.vehicle.id} style={card}><div><b style={{fontSize:17}}>{row.vehicle.plateNumber}</b><div>{row.vehicle.make??''} {row.vehicle.model??''}{row.vehicle.color?` · ${row.vehicle.color}`:''}</div><small>{row.unit.building.name} · Unit {row.unit.number} · {row.vehicle.vehicleType.replaceAll('_',' ')}</small></div><div style={{display:'flex',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><small>Assigned bay</small><div style={{fontWeight:800,fontSize:18}}>{row.parkingSlot||'Unassigned'}</div></div><button disabled={busyId===row.vehicle.id} onClick={()=>void update(row)} style={primary}>{busyId===row.vehicle.id?'Saving…':row.parkingSlot?'Change / clear':'Assign bay'}</button></div></article>)}</div></section></main>
}
const panel:React.CSSProperties={marginTop:20,padding:20,border:'1px solid #dbe7ea',borderRadius:16,background:'white'}
const card:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',padding:14,border:'1px solid #e5e7eb',borderRadius:12,flexWrap:'wrap'}
const primary:React.CSSProperties={padding:'10px 14px',borderRadius:10,border:'1px solid #05879A',background:'#05879A',color:'white',fontWeight:700}
const errorBox:React.CSSProperties={marginTop:18,padding:12,border:'1px solid #ef4444',borderRadius:10}
