'use client'

import { FormEvent, useCallback, useEffect, useState } from 'react'
import { ActionBar, EmptyState, ErrorState, FormField, PageHeader, PageShell, PrimaryButton, SecondaryButton, SelectField } from '../../../components/admin-ui'
import { api, type Session } from '../../../lib/admin-client'

type Expense={id:string;expenseNumber:string;vendorName:string;invoiceReference?:string|null;expenseDate:string;dueDate?:string|null;description:string;amountPaise:string;status:string;expenseAccountId:string;fundId?:string|null;journalEntryId?:string|null;payableId?:string|null;payableStatus?:string|null;payableOutstandingRaw?:string|number}
type Payable={id:string;expenseId:string;expenseNumber:string;vendorName:string;status:string;dueDate?:string|null;originalAmountPaise:string;outstandingPaise:string}
type Budget={id:string;code:string;name:string;startsOn:string;endsOn:string;status:string;budgetPaise:string}
type Actual={accountId:string;fundId?:string|null;budgetPaise:string;actualPaise:string}
type Fund={id:string;code:string;name:string;utilizedPaise:string}
type Account={id:string;code:string;name:string;type:string;active:boolean}
type Journal={id:string;entryNumber:string;status:string;debitPaise:string;creditPaise:string}

const readRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','COMMITTEE_MEMBER','ACCOUNTANT'])
const manageRoles=new Set(['SUPER_ADMIN','ACCOUNTANT'])
const money=(v:string|number|undefined)=>`₹${(Number(v??0)/100).toLocaleString('en-IN',{maximumFractionDigits:2})}`
const today=()=>new Date().toISOString().slice(0,10)
function session():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw) as Session:null}catch{return null}}

export default function FinanceOperationsPage(){
  const[s,setS]=useState<Session|null>(null),[expenses,setExpenses]=useState<Expense[]>([]),[payables,setPayables]=useState<Payable[]>([]),[budgets,setBudgets]=useState<Budget[]>([]),[funds,setFunds]=useState<Fund[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[journals,setJournals]=useState<Journal[]>([]),[actuals,setActuals]=useState<Actual[]>([]),[selectedBudget,setSelectedBudget]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const[expenseNo,setExpenseNo]=useState(''),[vendor,setVendor]=useState(''),[description,setDescription]=useState(''),[amount,setAmount]=useState(''),[expenseDate,setExpenseDate]=useState(today()),[dueDate,setDueDate]=useState(''),[expenseAccount,setExpenseAccount]=useState('')
  const[budgetCode,setBudgetCode]=useState(''),[budgetName,setBudgetName]=useState(''),[budgetStart,setBudgetStart]=useState(today()),[budgetEnd,setBudgetEnd]=useState(today()),[budgetAccount,setBudgetAccount]=useState(''),[budgetAmount,setBudgetAmount]=useState('')
  const[actionExpense,setActionExpense]=useState<Expense|null>(null),[expenseAction,setExpenseAction]=useState<'approve'|'post'|null>(null),[payableAccount,setPayableAccount]=useState(''),[journalNumber,setJournalNumber]=useState('')
  const[settlementPayable,setSettlementPayable]=useState<Payable|null>(null),[settlementAmount,setSettlementAmount]=useState(''),[settlementJournal,setSettlementJournal]=useState('')
  const canRead=!!s&&readRoles.has(s.role),canManage=!!s&&manageRoles.has(s.role)
  const load=useCallback(async(x:Session)=>{setLoading(true);setError('');try{const[e,p,b,f,a,j]=await Promise.all([api<Expense[]>('/accounting/finance-operations/expenses',{},x),api<Payable[]>('/accounting/finance-operations/payables',{},x),api<Budget[]>('/accounting/finance-operations/budgets',{},x),api<Fund[]>('/accounting/finance-operations/fund-utilization',{},x),api<Account[]>('/accounting/accounts',{},x),api<Journal[]>('/accounting/journals',{},x)]);setExpenses(e);setPayables(p);setBudgets(b);setFunds(f);setAccounts(a);setJournals(j)}catch(err){setError(err instanceof Error?err.message:'Could not load finance operations')}finally{setLoading(false)}},[])
  useEffect(()=>{const x=session();setS(x);if(x&&readRoles.has(x.role))void load(x);else setLoading(false)},[load])

  async function mutate(path:string,body?:unknown){if(!s||!canManage)return;setBusy(true);setError('');try{await api(path,{method:'POST',body:body===undefined?undefined:JSON.stringify(body)},s);await load(s)}catch(err){setError(err instanceof Error?err.message:'Finance operation failed')}finally{setBusy(false)}}
  async function createExpense(e:FormEvent){e.preventDefault();const rupees=Number(amount);if(!Number.isFinite(rupees)||rupees<=0||!expenseAccount)return setError('Enter a valid amount and expense account.');await mutate('/accounting/finance-operations/expenses',{expenseNumber:expenseNo,vendorName:vendor,expenseDate,dueDate:dueDate||undefined,description,amountPaise:Math.round(rupees*100),expenseAccountId:expenseAccount});setExpenseNo('');setVendor('');setDescription('');setAmount('')}
  function approveExpense(x:Expense){setActionExpense(x);setExpenseAction('approve');setPayableAccount('')}
  function postExpense(x:Expense){setActionExpense(x);setExpenseAction('post');setJournalNumber(`EXP-${x.expenseNumber}`)}
  async function submitExpenseAction(e:FormEvent){e.preventDefault();if(!actionExpense||!expenseAction)return;if(expenseAction==='approve'){if(!payableAccount)return setError('Choose a payable liability account.');await mutate(`/accounting/finance-operations/expenses/${actionExpense.id}/approve`,{payableAccountId:payableAccount})}else{if(!journalNumber.trim())return setError('Enter a journal entry number.');await mutate(`/accounting/finance-operations/expenses/${actionExpense.id}/post`,{entryNumber:journalNumber.trim()})}setActionExpense(null);setExpenseAction(null);setPayableAccount('');setJournalNumber('')}
  function settlePayable(p:Payable){setSettlementPayable(p);setSettlementAmount((Number(p.outstandingPaise)/100).toString());setSettlementJournal('')}
  async function submitSettlement(e:FormEvent){e.preventDefault();if(!settlementPayable)return;const amountR=Number(settlementAmount);if(!Number.isFinite(amountR)||amountR<=0)return setError('Enter a positive settlement amount.');if(amountR*100>Number(settlementPayable.outstandingPaise))return setError('Settlement cannot exceed the outstanding payable amount.');if(!settlementJournal)return setError('Choose a posted payment journal.');await mutate(`/accounting/finance-operations/payables/${settlementPayable.id}/settle`,{amountPaise:Math.round(amountR*100),settlementDate:today(),journalEntryId:settlementJournal,idempotencyKey:`admin-${settlementPayable.id}-${Date.now()}`});setSettlementPayable(null);setSettlementAmount('');setSettlementJournal('')}
  async function createBudget(e:FormEvent){e.preventDefault();const rupees=Number(budgetAmount);if(!budgetAccount||!Number.isFinite(rupees)||rupees<0)return setError('Choose an account and enter a valid budget amount.');await mutate('/accounting/finance-operations/budgets',{code:budgetCode,name:budgetName,startsOn:budgetStart,endsOn:budgetEnd,lines:[{accountId:budgetAccount,amountPaise:Math.round(rupees*100)}]});setBudgetCode('');setBudgetName('');setBudgetAmount('')}
  async function showActuals(id:string){if(!s)return;setSelectedBudget(id);setError('');try{setActuals(await api<Actual[]>(`/accounting/finance-operations/budgets/${id}/actuals`,{},s))}catch(err){setError(err instanceof Error?err.message:'Could not load budget actuals')}}
  async function exportSnapshot(){if(!s)return;setBusy(true);try{const data=await api<unknown>('/accounting/finance-operations/export',{},s);const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`aaraagate-finance-${today()}.json`;a.click();URL.revokeObjectURL(url)}catch(err){setError(err instanceof Error?err.message:'Could not export finance snapshot')}finally{setBusy(false)}}

  if(loading)return <PageShell><PageHeader title="Finance operations" description="Loading finance operations…"/></PageShell>
  if(!canRead)return <PageShell><PageHeader title="Finance access required" actions={<a href="/finance">Return to Finance</a>}/></PageShell>
  const expenseAccounts=accounts.filter(a=>a.type==='EXPENSE'&&a.active),liabilityAccounts=accounts.filter(a=>a.type==='LIABILITY'&&a.active)
  return <PageShell>
    <PageHeader context={`${s?.societyName??'Current society'} · ${s?.role.replaceAll('_',' ')}`} title="Finance operations" description="Expenses, payables, budgets, utilization and export-ready controls." actions={<a href="/finance">← Finance</a>}/>
    {error&&<ErrorState title="Finance operation failed" description={error}/>}<ActionBar label="Finance operations actions"><SecondaryButton disabled={busy} onClick={()=>void exportSnapshot()}>Export snapshot</SecondaryButton><SecondaryButton disabled={busy} onClick={()=>s&&void load(s)}>Refresh</SecondaryButton></ActionBar>{!canManage&&<div style={notice}>Read-only mode. Posting and approvals require Accountant/Treasurer or platform finance access.</div>}
    {canManage&&actionExpense&&expenseAction&&<section style={panel}><div style={header}><div><h2 style={{margin:'0 0 4px'}}>{expenseAction==='approve'?'Approve expense':'Post expense'}</h2><small>{actionExpense.expenseNumber} · {actionExpense.vendorName} · {money(actionExpense.amountPaise)}</small></div><SecondaryButton type="button" onClick={()=>{setActionExpense(null);setExpenseAction(null)}}>Cancel</SecondaryButton></div><form onSubmit={submitExpenseAction} style={{...grid,marginTop:14}}>{expenseAction==='approve'?<SelectField label="Payable liability account" required value={payableAccount} onChange={e=>setPayableAccount(e.target.value)}><option value="">Choose liability account</option>{accounts.filter(a=>a.type==='LIABILITY'&&a.active).map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</SelectField>:<FormField label="Journal entry number" required value={journalNumber} onChange={e=>setJournalNumber(e.target.value)}/>}<PrimaryButton type="submit" loading={busy}>{expenseAction==='approve'?'Approve expense':'Post expense'}</PrimaryButton></form></section>}
    {canManage&&settlementPayable&&<section style={panel}><div style={header}><div><h2 style={{margin:'0 0 4px'}}>Record payable settlement</h2><small>{settlementPayable.expenseNumber} · {settlementPayable.vendorName} · outstanding {money(settlementPayable.outstandingPaise)}</small></div><SecondaryButton type="button" onClick={()=>setSettlementPayable(null)}>Cancel</SecondaryButton></div><form onSubmit={submitSettlement} style={{...grid,marginTop:14}}><FormField label="Settlement amount (₹)" required type="number" min="0.01" step="0.01" max={(Number(settlementPayable.outstandingPaise)/100).toString()} value={settlementAmount} onChange={e=>setSettlementAmount(e.target.value)}/><SelectField label="Posted payment journal" required value={settlementJournal} onChange={e=>setSettlementJournal(e.target.value)}><option value="">Choose posted journal</option>{journals.filter(j=>j.status==='POSTED').map(j=><option key={j.id} value={j.id}>{j.entryNumber} · {money(j.debitPaise)}</option>)}</SelectField><PrimaryButton type="submit" loading={busy} disabled={!settlementJournal}>Record settlement</PrimaryButton></form></section>}

    {canManage&&<section style={panel}><h2 style={{marginTop:0}}>New expense</h2><form onSubmit={createExpense} style={grid}><FormField label="Expense no." required value={expenseNo} onChange={e=>setExpenseNo(e.target.value)}/><FormField label="Vendor / payee" required value={vendor} onChange={e=>setVendor(e.target.value)}/><FormField label="Expense date" type="date" value={expenseDate} onChange={e=>setExpenseDate(e.target.value)}/><FormField label="Due date" type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/><FormField label="Amount (₹)" type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/><SelectField label="Expense account" required value={expenseAccount} onChange={e=>setExpenseAccount(e.target.value)}><option value="">Choose account</option>{expenseAccounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</SelectField><FormField label="Description" required value={description} onChange={e=>setDescription(e.target.value)}/><PrimaryButton type="submit" loading={busy}>Create draft</PrimaryButton></form></section>}

    <section style={panel}><h2 style={{marginTop:0}}>Expense register</h2><div style={{overflowX:'auto'}}><table style={table}><thead><tr><th>No.</th><th>Vendor</th><th>Date</th><th>Status</th><th style={right}>Amount</th><th>Action</th></tr></thead><tbody>{expenses.map(x=><tr key={x.id}><td><b>{x.expenseNumber}</b><br/><small>{x.description}</small></td><td>{x.vendorName}</td><td>{new Date(x.expenseDate).toLocaleDateString('en-IN')}</td><td>{x.status}</td><td style={right}>{money(x.amountPaise)}</td><td>{canManage&&x.status==='DRAFT'?<SecondaryButton onClick={()=>void approveExpense(x)}>Approve</SecondaryButton>:canManage&&x.status==='APPROVED'?<PrimaryButton onClick={()=>void postExpense(x)}>Post</PrimaryButton>:<small>{x.journalEntryId?'Posted to journal':'—'}</small>}</td></tr>)}</tbody></table></div></section>

    <section style={panel}><h2 style={{marginTop:0}}>Payables</h2><div style={{display:'grid',gap:8}}>{payables.map(p=><div key={p.id} style={row}><div><b>{p.vendorName}</b> · {p.expenseNumber}<br/><small>{p.dueDate?`Due ${new Date(p.dueDate).toLocaleDateString('en-IN')}`:'No due date'} · {p.status}</small></div><div style={{display:'flex',gap:10,alignItems:'center'}}><b>{money(p.outstandingPaise)}</b>{canManage&&Number(p.outstandingPaise)>0&&<PrimaryButton onClick={()=>void settlePayable(p)}>Record settlement</PrimaryButton>}</div></div>)}</div></section>

    {canManage&&<section style={panel}><h2 style={{marginTop:0}}>New budget</h2><form onSubmit={createBudget} style={grid}><FormField label="Code" required value={budgetCode} onChange={e=>setBudgetCode(e.target.value)}/><FormField label="Name" required value={budgetName} onChange={e=>setBudgetName(e.target.value)}/><FormField label="Starts" type="date" value={budgetStart} onChange={e=>setBudgetStart(e.target.value)}/><FormField label="Ends" type="date" value={budgetEnd} onChange={e=>setBudgetEnd(e.target.value)}/><SelectField label="Expense account" required value={budgetAccount} onChange={e=>setBudgetAccount(e.target.value)}><option value="">Choose account</option>{expenseAccounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</SelectField><FormField label="Amount (₹)" type="number" min="0" step="0.01" value={budgetAmount} onChange={e=>setBudgetAmount(e.target.value)}/><PrimaryButton type="submit" loading={busy}>Create budget</PrimaryButton></form></section>}

    <section style={panel}><h2 style={{marginTop:0}}>Budgets</h2><div style={{display:'grid',gap:8}}>{budgets.map(b=><div key={b.id} style={row}><div><b>{b.code} · {b.name}</b><br/><small>{new Date(b.startsOn).toLocaleDateString('en-IN')} – {new Date(b.endsOn).toLocaleDateString('en-IN')} · {b.status}</small></div><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><b>{money(b.budgetPaise)}</b><SecondaryButton onClick={()=>void showActuals(b.id)}>Actuals</SecondaryButton>{canManage&&b.status==='DRAFT'&&<PrimaryButton onClick={()=>void mutate(`/accounting/finance-operations/budgets/${b.id}/approve`)}>Approve</PrimaryButton>}{canManage&&b.status==='APPROVED'&&<PrimaryButton onClick={()=>void mutate(`/accounting/finance-operations/budgets/${b.id}/lock`)}>Lock</PrimaryButton>}</div></div>)}</div>{selectedBudget&&<div style={{marginTop:16}}><h3>Budget vs actual</h3>{actuals.map((a,i)=><div key={`${a.accountId}-${a.fundId??i}`} style={row}><span>{a.accountId}{a.fundId?` · fund ${a.fundId}`:''}</span><span>{money(a.budgetPaise)} budget · <b>{money(a.actualPaise)} actual</b></span></div>)}</div>}</section>

    <section style={panel}><h2 style={{marginTop:0}}>Fund utilization</h2>{funds.length===0?<EmptyState title="No accounting funds configured or utilized"/>:funds.map(f=><div key={f.id} style={row}><span><b>{f.code}</b> · {f.name}</span><b>{money(f.utilizedPaise)}</b></div>)}</section>
    <section style={panel}><h2 style={{marginTop:0}}>Settlement journal helper</h2><p style={{marginTop:0}}>Payable settlements require an already-posted payment journal. Recent posted journals are listed for reference.</p>{journals.filter(j=>j.status==='POSTED').slice(0,12).map(j=><div key={j.id} style={row}><span><b>{j.entryNumber}</b><br/><small>{j.id}</small></span><span>{money(j.debitPaise)}</span></div>)}{liabilityAccounts.length>0&&<small>{liabilityAccounts.length} active liability ledger account{liabilityAccounts.length===1?'':'s'} available for payable approval.</small>}</section>
  </PageShell>
}

const header:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}
const panel:React.CSSProperties={marginTop:20,padding:20,border:'1px solid #dbe7ea',borderRadius:16,background:'white'}
const row:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',padding:'11px 0',borderBottom:'1px solid #eef2f7',flexWrap:'wrap'}
const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12,alignItems:'end'}
const notice:React.CSSProperties={marginTop:18,padding:12,border:'1px solid #f59e0b',borderRadius:10,background:'#fffbeb'}
const table:React.CSSProperties={width:'100%',borderCollapse:'collapse'}
const right:React.CSSProperties={textAlign:'right'}
