'use client'

import { FormEvent, useCallback, useEffect, useState } from 'react'

type Session={accessToken:string;role:string;societyName?:string}
type Expense={id:string;expenseNumber:string;vendorName:string;invoiceReference?:string|null;expenseDate:string;dueDate?:string|null;description:string;amountPaise:string;status:string;expenseAccountId:string;fundId?:string|null;journalEntryId?:string|null;payableId?:string|null;payableStatus?:string|null;payableOutstandingRaw?:string|number}
type Payable={id:string;expenseId:string;expenseNumber:string;vendorName:string;status:string;dueDate?:string|null;originalAmountPaise:string;outstandingPaise:string}
type Budget={id:string;code:string;name:string;startsOn:string;endsOn:string;status:string;budgetPaise:string}
type Actual={accountId:string;fundId?:string|null;budgetPaise:string;actualPaise:string}
type Fund={id:string;code:string;name:string;utilizedPaise:string}
type Account={id:string;code:string;name:string;type:string;active:boolean}
type Journal={id:string;entryNumber:string;status:string;debitPaise:string;creditPaise:string}

const base=(process.env.NEXT_PUBLIC_AARAGATE_API_BASE_URL??'http://localhost:3000').replace(/\/$/,'')
const readRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','COMMITTEE_MEMBER','ACCOUNTANT'])
const manageRoles=new Set(['SUPER_ADMIN','ACCOUNTANT'])
const money=(v:string|number|undefined)=>`₹${(Number(v??0)/100).toLocaleString('en-IN',{maximumFractionDigits:2})}`
const today=()=>new Date().toISOString().slice(0,10)
function session():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw) as Session:null}catch{return null}}
async function api<T>(s:Session,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${base}/api/v1${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.accessToken}`,...init.headers}});const text=await r.text();const body=text?JSON.parse(text):null;if(!r.ok)throw new Error(Array.isArray(body?.message)?body.message.join(', '):body?.message??`Request failed (${r.status})`);return body as T}

export default function FinanceOperationsPage(){
  const[s,setS]=useState<Session|null>(null),[expenses,setExpenses]=useState<Expense[]>([]),[payables,setPayables]=useState<Payable[]>([]),[budgets,setBudgets]=useState<Budget[]>([]),[funds,setFunds]=useState<Fund[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[journals,setJournals]=useState<Journal[]>([]),[actuals,setActuals]=useState<Actual[]>([]),[selectedBudget,setSelectedBudget]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const[expenseNo,setExpenseNo]=useState(''),[vendor,setVendor]=useState(''),[description,setDescription]=useState(''),[amount,setAmount]=useState(''),[expenseDate,setExpenseDate]=useState(today()),[dueDate,setDueDate]=useState(''),[expenseAccount,setExpenseAccount]=useState('')
  const[budgetCode,setBudgetCode]=useState(''),[budgetName,setBudgetName]=useState(''),[budgetStart,setBudgetStart]=useState(today()),[budgetEnd,setBudgetEnd]=useState(today()),[budgetAccount,setBudgetAccount]=useState(''),[budgetAmount,setBudgetAmount]=useState('')
  const canRead=!!s&&readRoles.has(s.role),canManage=!!s&&manageRoles.has(s.role)
  const load=useCallback(async(x:Session)=>{setLoading(true);setError('');try{const[e,p,b,f,a,j]=await Promise.all([api<Expense[]>(x,'/accounting/finance-operations/expenses'),api<Payable[]>(x,'/accounting/finance-operations/payables'),api<Budget[]>(x,'/accounting/finance-operations/budgets'),api<Fund[]>(x,'/accounting/finance-operations/fund-utilization'),api<Account[]>(x,'/accounting/accounts'),api<Journal[]>(x,'/accounting/journals')]);setExpenses(e);setPayables(p);setBudgets(b);setFunds(f);setAccounts(a);setJournals(j)}catch(err){setError(err instanceof Error?err.message:'Could not load finance operations')}finally{setLoading(false)}},[])
  useEffect(()=>{const x=session();setS(x);if(x&&readRoles.has(x.role))void load(x);else setLoading(false)},[load])

  async function mutate(path:string,body?:unknown){if(!s||!canManage)return;setBusy(true);setError('');try{await api(s,path,{method:'POST',body:body===undefined?undefined:JSON.stringify(body)});await load(s)}catch(err){setError(err instanceof Error?err.message:'Finance operation failed')}finally{setBusy(false)}}
  async function createExpense(e:FormEvent){e.preventDefault();const rupees=Number(amount);if(!Number.isFinite(rupees)||rupees<=0||!expenseAccount)return setError('Enter a valid amount and expense account.');await mutate('/accounting/finance-operations/expenses',{expenseNumber:expenseNo,vendorName:vendor,expenseDate,dueDate:dueDate||undefined,description,amountPaise:Math.round(rupees*100),expenseAccountId:expenseAccount});setExpenseNo('');setVendor('');setDescription('');setAmount('')}
  async function approveExpense(x:Expense){const payableAccountId=prompt('Payable ledger account UUID');if(payableAccountId)await mutate(`/accounting/finance-operations/expenses/${x.id}/approve`,{payableAccountId})}
  async function postExpense(x:Expense){const entryNumber=prompt('Journal entry number',`EXP-${x.expenseNumber}`);if(entryNumber)await mutate(`/accounting/finance-operations/expenses/${x.id}/post`,{entryNumber})}
  async function settlePayable(p:Payable){const amountR=prompt('Settlement amount in ₹',(Number(p.outstandingPaise)/100).toString());if(!amountR)return;const journalEntryId=prompt('Posted payment journal UUID');if(!journalEntryId)return;await mutate(`/accounting/finance-operations/payables/${p.id}/settle`,{amountPaise:Math.round(Number(amountR)*100),settlementDate:today(),journalEntryId,idempotencyKey:`admin-${p.id}-${Date.now()}`})}
  async function createBudget(e:FormEvent){e.preventDefault();const rupees=Number(budgetAmount);if(!budgetAccount||!Number.isFinite(rupees)||rupees<0)return setError('Choose an account and enter a valid budget amount.');await mutate('/accounting/finance-operations/budgets',{code:budgetCode,name:budgetName,startsOn:budgetStart,endsOn:budgetEnd,lines:[{accountId:budgetAccount,amountPaise:Math.round(rupees*100)}]});setBudgetCode('');setBudgetName('');setBudgetAmount('')}
  async function showActuals(id:string){if(!s)return;setSelectedBudget(id);setError('');try{setActuals(await api<Actual[]>(s,`/accounting/finance-operations/budgets/${id}/actuals`))}catch(err){setError(err instanceof Error?err.message:'Could not load budget actuals')}}
  async function exportSnapshot(){if(!s)return;setBusy(true);try{const data=await api<unknown>(s,'/accounting/finance-operations/export');const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`aaraagate-finance-${today()}.json`;a.click();URL.revokeObjectURL(url)}catch(err){setError(err instanceof Error?err.message:'Could not export finance snapshot')}finally{setBusy(false)}}

  if(loading)return <main style={{padding:32}}>Loading finance operations…</main>
  if(!canRead)return <main style={{padding:32}}><h1>Finance access required</h1><a href="/finance">Return to Finance</a></main>
  const expenseAccounts=accounts.filter(a=>a.type==='EXPENSE'&&a.active),liabilityAccounts=accounts.filter(a=>a.type==='LIABILITY'&&a.active)
  return <main style={{maxWidth:1240,margin:'0 auto',padding:'28px 22px 80px'}}>
    <header style={header}><div><small>{s?.societyName??'Current society'} · {s?.role.replaceAll('_',' ')}</small><h1 style={{margin:'4px 0'}}>Finance operations</h1><p style={{margin:0}}>Expenses, payables, budgets, utilization and export-ready controls.</p></div><div style={{display:'flex',gap:8}}><button style={secondary} onClick={()=>void exportSnapshot()} disabled={busy}>Export snapshot</button><a href="/finance" style={link}>← Finance</a></div></header>
    {error&&<div style={errorBox}>{error}</div>}{!canManage&&<div style={notice}>Read-only mode. Posting and approvals require Accountant/Treasurer or platform finance access.</div>}

    {canManage&&<section style={panel}><h2 style={{marginTop:0}}>New expense</h2><form onSubmit={createExpense} style={grid}><label>Expense no.<input required value={expenseNo} onChange={e=>setExpenseNo(e.target.value)} style={input}/></label><label>Vendor / payee<input required value={vendor} onChange={e=>setVendor(e.target.value)} style={input}/></label><label>Expense date<input type="date" value={expenseDate} onChange={e=>setExpenseDate(e.target.value)} style={input}/></label><label>Due date<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} style={input}/></label><label>Amount (₹)<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} style={input}/></label><label>Expense account<select required value={expenseAccount} onChange={e=>setExpenseAccount(e.target.value)} style={input}><option value="">Choose account</option>{expenseAccounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label><label style={{gridColumn:'1/-1'}}>Description<input required value={description} onChange={e=>setDescription(e.target.value)} style={input}/></label><button disabled={busy} style={primary}>Create draft</button></form></section>}

    <section style={panel}><h2 style={{marginTop:0}}>Expense register</h2><div style={{overflowX:'auto'}}><table style={table}><thead><tr><th>No.</th><th>Vendor</th><th>Date</th><th>Status</th><th style={right}>Amount</th><th>Action</th></tr></thead><tbody>{expenses.map(x=><tr key={x.id}><td><b>{x.expenseNumber}</b><br/><small>{x.description}</small></td><td>{x.vendorName}</td><td>{new Date(x.expenseDate).toLocaleDateString('en-IN')}</td><td>{x.status}</td><td style={right}>{money(x.amountPaise)}</td><td>{canManage&&x.status==='DRAFT'?<button style={secondary} onClick={()=>void approveExpense(x)}>Approve</button>:canManage&&x.status==='APPROVED'?<button style={primary} onClick={()=>void postExpense(x)}>Post</button>:<small>{x.journalEntryId?'Posted to journal':'—'}</small>}</td></tr>)}</tbody></table></div></section>

    <section style={panel}><h2 style={{marginTop:0}}>Payables</h2><div style={{display:'grid',gap:8}}>{payables.map(p=><div key={p.id} style={row}><div><b>{p.vendorName}</b> · {p.expenseNumber}<br/><small>{p.dueDate?`Due ${new Date(p.dueDate).toLocaleDateString('en-IN')}`:'No due date'} · {p.status}</small></div><div style={{display:'flex',gap:10,alignItems:'center'}}><b>{money(p.outstandingPaise)}</b>{canManage&&Number(p.outstandingPaise)>0&&<button style={primary} onClick={()=>void settlePayable(p)}>Record settlement</button>}</div></div>)}</div></section>

    {canManage&&<section style={panel}><h2 style={{marginTop:0}}>New budget</h2><form onSubmit={createBudget} style={grid}><label>Code<input required value={budgetCode} onChange={e=>setBudgetCode(e.target.value)} style={input}/></label><label>Name<input required value={budgetName} onChange={e=>setBudgetName(e.target.value)} style={input}/></label><label>Starts<input type="date" value={budgetStart} onChange={e=>setBudgetStart(e.target.value)} style={input}/></label><label>Ends<input type="date" value={budgetEnd} onChange={e=>setBudgetEnd(e.target.value)} style={input}/></label><label>Expense account<select required value={budgetAccount} onChange={e=>setBudgetAccount(e.target.value)} style={input}><option value="">Choose account</option>{expenseAccounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label><label>Amount (₹)<input type="number" min="0" step="0.01" value={budgetAmount} onChange={e=>setBudgetAmount(e.target.value)} style={input}/></label><button disabled={busy} style={primary}>Create budget</button></form></section>}

    <section style={panel}><h2 style={{marginTop:0}}>Budgets</h2><div style={{display:'grid',gap:8}}>{budgets.map(b=><div key={b.id} style={row}><div><b>{b.code} · {b.name}</b><br/><small>{new Date(b.startsOn).toLocaleDateString('en-IN')} – {new Date(b.endsOn).toLocaleDateString('en-IN')} · {b.status}</small></div><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><b>{money(b.budgetPaise)}</b><button style={secondary} onClick={()=>void showActuals(b.id)}>Actuals</button>{canManage&&b.status==='DRAFT'&&<button style={primary} onClick={()=>void mutate(`/accounting/finance-operations/budgets/${b.id}/approve`)}>Approve</button>}{canManage&&b.status==='APPROVED'&&<button style={primary} onClick={()=>void mutate(`/accounting/finance-operations/budgets/${b.id}/lock`)}>Lock</button>}</div></div>)}</div>{selectedBudget&&<div style={{marginTop:16}}><h3>Budget vs actual</h3>{actuals.map((a,i)=><div key={`${a.accountId}-${a.fundId??i}`} style={row}><span>{a.accountId}{a.fundId?` · fund ${a.fundId}`:''}</span><span>{money(a.budgetPaise)} budget · <b>{money(a.actualPaise)} actual</b></span></div>)}</div>}</section>

    <section style={panel}><h2 style={{marginTop:0}}>Fund utilization</h2>{funds.length===0?<p>No accounting funds configured or utilized.</p>:funds.map(f=><div key={f.id} style={row}><span><b>{f.code}</b> · {f.name}</span><b>{money(f.utilizedPaise)}</b></div>)}</section>
    <section style={panel}><h2 style={{marginTop:0}}>Settlement journal helper</h2><p style={{marginTop:0}}>Payable settlements require an already-posted payment journal. Recent posted journals are listed for reference.</p>{journals.filter(j=>j.status==='POSTED').slice(0,12).map(j=><div key={j.id} style={row}><span><b>{j.entryNumber}</b><br/><small>{j.id}</small></span><span>{money(j.debitPaise)}</span></div>)}{liabilityAccounts.length>0&&<small>{liabilityAccounts.length} active liability ledger account{liabilityAccounts.length===1?'':'s'} available for payable approval.</small>}</section>
  </main>
}

const header:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}
const panel:React.CSSProperties={marginTop:20,padding:20,border:'1px solid #dbe7ea',borderRadius:16,background:'white'}
const row:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',padding:'11px 0',borderBottom:'1px solid #eef2f7',flexWrap:'wrap'}
const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12,alignItems:'end'}
const input:React.CSSProperties={display:'block',width:'100%',boxSizing:'border-box',marginTop:6,padding:10,border:'1px solid #cbd5e1',borderRadius:10,font:'inherit'}
const primary:React.CSSProperties={padding:'10px 14px',borderRadius:10,border:'1px solid #05879A',background:'#05879A',color:'white',fontWeight:700,cursor:'pointer'}
const secondary:React.CSSProperties={padding:'9px 13px',borderRadius:10,border:'1px solid #94a3b8',background:'white',fontWeight:700,cursor:'pointer'}
const link:React.CSSProperties={...secondary,textDecoration:'none',color:'#111827'}
const errorBox:React.CSSProperties={marginTop:18,padding:12,border:'1px solid #ef4444',borderRadius:10,background:'#fff7f7'}
const notice:React.CSSProperties={marginTop:18,padding:12,border:'1px solid #f59e0b',borderRadius:10,background:'#fffbeb'}
const table:React.CSSProperties={width:'100%',borderCollapse:'collapse'}
const right:React.CSSProperties={textAlign:'right'}
