'use client'

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { operatorPrompt } from '../../lib/operator-dialog'

type AuthSession={sessionId:string;accessToken:string;refreshToken:string}
type Membership={societyId:string;role:string;society?:{name?:string;code?:string}}
type Provider={providerId:string;businessName:string;verification:string;providerActive:boolean}
type Booking={id:string;offeringId:string;offeringName:string;addressSnapshot:Record<string,unknown>;status:string;scheduledFrom:string;scheduledUntil:string;servicePricePaise:number;notes?:string|null;createdAt:string}
type Agent={id:string;displayName:string;phone?:string|null;externalRef?:string|null;active:boolean}
type Area={id:string;postalCode:string;active:boolean}
type Offering={id:string;name:string;description?:string|null;pricePaise:number;durationMinutes?:number|null;active:boolean;categoryId:string}
type Window={id:string;dayOfWeek:number;startMinute:number;endMinute:number;slotCapacity:number;active:boolean}
type Assignment={id:string;bookingId:string;agentId:string;status:string;agentDisplayName?:string;assignedAt:string}
type SettlementSummary={paidPaise:number;approvedPaise:number;draftPaise:number;openRecoveryPaise:number;openRecoveryCount:number}
type SettlementBatch={id:string;status:string;grossAmountPaise:number;platformFeePaise:number;providerAmountPaise:number;approvedAt?:string|null;paidAt?:string|null;paymentReference?:string|null;createdAt:string;entryCount:number}
type SettlementRecovery={id:string;status:string;providerAmountPaise:number;reason:string;offeringName?:string;createdAt:string;resolvedAt?:string|null}
type Category={id:string;name:string;slug:string}
type ReadinessCheck={key:string;ready:boolean;count:number}
type ProviderReadiness={ready:boolean;checks:ReadinessCheck[];pendingProposals:number;openDisputes:number}
type AvailabilityException={id:string;serviceDate:string;closed:boolean;slotCapacity?:number|null;note?:string|null;active:boolean}
type View='bookings'|'catalogue'|'agents'|'coverage'|'schedule'|'earnings'|'readiness'

const base=(process.env.NEXT_PUBLIC_AARAGATE_API_BASE_URL??'http://localhost:3000').replace(/\/$/,'')
const storageKey='aaraagate.provider.session'
const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat']

async function api<T>(path:string,init:RequestInit={},session?:AuthSession):Promise<T>{
  const response=await fetch(`${base}/api/v1${path}`,{...init,headers:{Accept:'application/json','Content-Type':'application/json',...(session?{Authorization:`Bearer ${session.accessToken}`}:{}) ,...init.headers}})
  const text=await response.text();const body=text?JSON.parse(text):null
  if(!response.ok)throw new Error(body?.message??`Request failed (${response.status})`)
  return body as T
}
function fromResult(value:Record<string,unknown>):AuthSession{const s=value.session as Record<string,unknown>|undefined;if(!s?.sessionId||!s.accessToken||!s.refreshToken)throw new Error('Authentication returned an incomplete session');return{sessionId:String(s.sessionId),accessToken:String(s.accessToken),refreshToken:String(s.refreshToken)}}
function money(paise:number){return `₹${(paise/100).toLocaleString('en-IN')}`}
function time(minute:number){const h=Math.floor(minute/60),m=minute%60;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`}
function addressText(snapshot:Record<string,unknown>){return [snapshot.label,snapshot.addressLine1,snapshot.addressLine2,snapshot.locality,snapshot.city,snapshot.state,snapshot.postalCode].filter(Boolean).join(', ')}

export default function ProviderPage(){
  const[session,setSession]=useState<AuthSession|null>(null),[restoring,setRestoring]=useState(true)
  useEffect(()=>{const raw=sessionStorage.getItem(storageKey);if(!raw){setRestoring(false);return}try{const stored=JSON.parse(raw) as AuthSession;api<Record<string,unknown>>('/auth/refresh',{method:'POST',body:JSON.stringify({sessionId:stored.sessionId,refreshToken:stored.refreshToken})}).then(next=>{const fresh={sessionId:String(next.sessionId),accessToken:String(next.accessToken),refreshToken:String(next.refreshToken)};sessionStorage.setItem(storageKey,JSON.stringify(fresh));setSession(fresh);return Promise.resolve()}).catch(()=>sessionStorage.removeItem(storageKey)).finally(()=>setRestoring(false))}catch{sessionStorage.removeItem(storageKey);setRestoring(false)}},[])
  const accept=(next:AuthSession)=>{sessionStorage.setItem(storageKey,JSON.stringify(next));setSession(next)}
  const logout=async()=>{if(session)await api('/auth/logout',{method:'POST',body:JSON.stringify({sessionId:session.sessionId,refreshToken:session.refreshToken})}).catch(()=>undefined);sessionStorage.removeItem(storageKey);setSession(null)}
  if(restoring)return <main style={center}>Restoring provider session…</main>
  if(!session)return <ProviderLogin onSession={accept}/>
  return <ProviderEntry session={session} onLogout={logout}/>
}

function ProviderEntry({session,onLogout}:{session:AuthSession;onLogout:()=>Promise<void>}){
  const[checking,setChecking]=useState(true),[hasProvider,setHasProvider]=useState(false)
  useEffect(()=>{api('/provider/services/me',{},session).then(()=>setHasProvider(true)).catch(()=>setHasProvider(false)).finally(()=>setChecking(false))},[session])
  if(checking)return <main style={center}>Checking provider access…</main>
  return hasProvider?<ProviderConsole session={session} onLogout={onLogout}/>:<ProviderOnboarding session={session} onLogout={onLogout}/>
}

function ProviderOnboarding({session,onLogout}:{session:AuthSession;onLogout:()=>Promise<void>}){
  const[businessName,setBusinessName]=useState(''),[contactName,setContactName]=useState(''),[phone,setPhone]=useState('+91'),[email,setEmail]=useState(''),[description,setDescription]=useState(''),[evidence,setEvidence]=useState(''),[application,setApplication]=useState<Record<string,unknown>|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const load=useCallback(async()=>{try{const a=await api<Record<string,unknown>|null>('/provider-onboarding/me',{},session);setApplication(a);if(a){setBusinessName(String(a.businessName??''));setContactName(String(a.contactName??''));setPhone(String(a.phone??'+91'));setEmail(String(a.email??''));setDescription(String(a.description??''));setEvidence(Array.isArray(a.evidenceRefs)?(a.evidenceRefs as unknown[]).join('\n'):'')}}catch(e){setError(e instanceof Error?e.message:'Could not load provider application')}},[session])
  useEffect(()=>{void load()},[load])
  const save=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await api('/provider-onboarding/applications',{method:'POST',body:JSON.stringify({businessName:businessName.trim(),contactName:contactName.trim()||undefined,phone:phone.trim(),email:email.trim()||undefined,description:description.trim()||undefined,evidenceRefs:evidence.split('\n').map(x=>x.trim()).filter(Boolean)})},session);await load()}catch(e){setError(e instanceof Error?e.message:'Could not save provider application')}finally{setBusy(false)}}
  const submit=async()=>{setBusy(true);setError('');try{await api('/provider-onboarding/applications/submit',{method:'POST'},session);await load()}catch(e){setError(e instanceof Error?e.message:'Could not submit provider application')}finally{setBusy(false)}}
  const status=String(application?.status??'DRAFT')
  return <main style={login}><section style={{...loginCard,width:'min(680px,100%)'}}><div style={brand}>aaraagate</div><h1>Provider onboarding</h1><p style={muted}>Create your provider profile and submit non-sensitive evidence references for platform review. Live KYC verification remains a separate operational step.</p>{error&&<div style={errorBox}>{error}</div>}<div style={{...badge,display:'inline-block',marginBottom:12}}>{status}</div><form onSubmit={save} style={stack}><label>Business name<input required style={input} value={businessName} onChange={e=>setBusinessName(e.target.value)}/></label><label>Contact name<input style={input} value={contactName} onChange={e=>setContactName(e.target.value)}/></label><label>Mobile<input required style={input} value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Email<input type="email" style={input} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Description<textarea style={{...input,minHeight:90}} value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Evidence references<textarea style={{...input,minHeight:90}} value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="One non-sensitive document/reference identifier per line"/></label>{status==='DRAFT'&&<><button style={button} disabled={busy}>Save draft</button><button type="button" style={primary} disabled={busy||!businessName.trim()} onClick={()=>void submit()}>Submit for review</button></>}</form>{Boolean(application?.reviewNote)&&<p><b>Review note:</b> {String(application?.reviewNote)}</p>}<button style={{...button,marginTop:12}} onClick={()=>void onLogout()}>Sign out</button></section></main>
}

function ProviderLogin({onSession}:{onSession:(s:AuthSession)=>void}){
  const[stage,setStage]=useState<'phone'|'otp'|'context'>('phone'),[phone,setPhone]=useState('+91'),[otp,setOtp]=useState(''),[challenge,setChallenge]=useState(''),[userId,setUserId]=useState(''),[selectionToken,setSelectionToken]=useState(''),[memberships,setMemberships]=useState<Membership[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Authentication failed')}finally{setBusy(false)}}
  const send=(e:FormEvent)=>{e.preventDefault();void run(async()=>{const result=await api<{challengeId:string}>('/auth/otp/request',{method:'POST',body:JSON.stringify({phone:phone.trim()})});setChallenge(result.challengeId);setStage('otp')})}
  const verify=(e:FormEvent)=>{e.preventDefault();void run(async()=>{const result=await api<Record<string,unknown>>('/auth/otp/verify',{method:'POST',body:JSON.stringify({challengeId:challenge,code:otp})});if(result.session){const s=fromResult(result);onSession(s);return}const options=(result.memberships as Membership[]|undefined)??[];if(!options.length)throw new Error('No provider-capable session could be created');setUserId(String(result.userId??''));setSelectionToken(String(result.selectionToken??''));setMemberships(options);setStage('context')})}
  const choose=(membership:Membership)=>void run(async()=>{const result=await api<Record<string,unknown>>('/auth/society/select',{method:'POST',body:JSON.stringify({userId,societyId:membership.societyId,selectionToken})});const s=fromResult(result);onSession(s)})
  return <main style={login}><section style={loginCard}><div style={brand}>aaraagate</div><h1 style={{marginBottom:8}}>Provider operations</h1><p style={muted}>Manage service coverage, availability, bookings and field dispatch with your registered mobile number.</p>{stage==='phone'&&<form onSubmit={send} style={stack}><label>Mobile number<input style={input} value={phone} onChange={e=>setPhone(e.target.value)} required/></label><button style={primary} disabled={busy}>Send OTP</button></form>}{stage==='otp'&&<form onSubmit={verify} style={stack}><label>6-digit OTP<input style={input} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} minLength={6} maxLength={6} required/></label><button style={primary} disabled={busy||otp.length!==6}>Verify securely</button></form>}{stage==='context'&&<div style={stack}><p style={muted}>Choose any active property context to establish your secure session. Provider access remains separately scoped to your provider account.</p>{memberships.map(m=><button key={`${m.societyId}-${m.role}`} style={choice} onClick={()=>choose(m)}><strong>{m.society?.name??m.society?.code??'Property'}</strong><span>{m.role.replaceAll('_',' ')}</span></button>)}</div>}{error&&<div style={errorBox}>{error}</div>}<a href="/" style={{display:'inline-block',marginTop:18}}>Admin & society operations</a></section></main>
}

function ProviderConsole({session,onLogout}:{session:AuthSession;onLogout:()=>Promise<void>}){
  const[view,setView]=useState<View>('bookings'),[provider,setProvider]=useState<Provider|null>(null),[bookings,setBookings]=useState<Booking[]>([]),[agents,setAgents]=useState<Agent[]>([]),[areas,setAreas]=useState<Area[]>([]),[offerings,setOfferings]=useState<Offering[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');try{const[p,b,a,r,o]=await Promise.all([api<Provider>('/provider/services/me',{},session),api<Booking[]>('/provider/services/bookings',{},session),api<Agent[]>('/provider/services/agents',{},session),api<Area[]>('/provider/services/areas',{},session),api<Offering[]>('/provider/services/offerings',{},session)]);setProvider(p);setBookings(b);setAgents(a);setAreas(r);setOfferings(o)}catch(e){setError(e instanceof Error?e.message:'Provider operations could not be loaded')}finally{setLoading(false)}},[session])
  useEffect(()=>{void load()},[load])
  const counts=useMemo(()=>({requested:bookings.filter(b=>b.status==='REQUESTED').length,confirmed:bookings.filter(b=>b.status==='CONFIRMED').length,activeAgents:agents.filter(a=>a.active).length,areas:areas.filter(a=>a.active).length}),[bookings,agents,areas])
  return <main style={{minHeight:'100vh',background:'#f5f8f9'}}><header style={topbar}><div><div style={brand}>aaraagate</div><small style={muted}>Provider workspace</small></div><div style={{textAlign:'right'}}><strong>{provider?.businessName??'Provider'}</strong><div><small>{provider?.verification??''}</small></div></div><button style={button} onClick={()=>void onLogout()}>Sign out</button></header><div style={{maxWidth:1180,margin:'0 auto',padding:'24px 20px 64px'}}>{error&&<div style={errorBox}>{error}</div>}<section style={metrics}><Metric label="New requests" value={counts.requested}/><Metric label="Confirmed jobs" value={counts.confirmed}/><Metric label="Active agents" value={counts.activeAgents}/><Metric label="Service PINs" value={counts.areas}/></section><nav style={tabs}>{(['bookings','catalogue','agents','coverage','schedule','earnings','readiness'] as View[]).map(v=><button key={v} style={view===v?activeTab:tab} onClick={()=>setView(v)}>{v[0].toUpperCase()+v.slice(1)}</button>)}</nav>{loading?<section style={panel}>Loading provider operations…</section>:<>{view==='bookings'&&<Bookings session={session} bookings={bookings} agents={agents} reload={load}/>} {view==='catalogue'&&<Catalogue session={session} offerings={offerings} reload={load}/>} {view==='agents'&&<Agents session={session} agents={agents} reload={load}/>} {view==='coverage'&&<Coverage session={session} areas={areas} offerings={offerings}/>} {view==='schedule'&&<Schedule session={session} offerings={offerings}/>} {view==='earnings'&&<Earnings session={session}/>} {view==='readiness'&&<Readiness session={session}/>}</>}</div></main>
}

function Bookings({session,bookings,agents,reload}:{session:AuthSession;bookings:Booking[];agents:Agent[];reload:()=>Promise<void>}){
  const[busy,setBusy]=useState(''),[error,setError]=useState(''),[assignments,setAssignments]=useState<Record<string,Assignment[]>>({})
  const respond=async(b:Booking,decision:'ACCEPT'|'DECLINE')=>{const note=await operatorPrompt(decision==='ACCEPT'?'Optional acceptance note':'Optional decline note')??undefined;setBusy(b.id);setError('');try{await api(`/provider/services/bookings/${b.id}/respond`,{method:'POST',body:JSON.stringify({decision,note})},session);await reload()}catch(e){setError(e instanceof Error?e.message:'Booking could not be updated')}finally{setBusy('')}}
  const propose=async(b:Booking)=>{const from=await operatorPrompt('Proposed start (ISO date/time)',b.scheduledFrom)??'';if(!from.trim())return;const until=await operatorPrompt('Proposed end (ISO date/time)',b.scheduledUntil)??'';if(!until.trim())return;const note=await operatorPrompt('Reason for alternate time (optional)')??undefined;setBusy(b.id);setError('');try{await api(`/provider/services/bookings/${b.id}/proposals`,{method:'POST',body:JSON.stringify({proposedFrom:new Date(from).toISOString(),proposedUntil:new Date(until).toISOString(),note})},session);await reload()}catch(e){setError(e instanceof Error?e.message:'Counter-proposal could not be created')}finally{setBusy('')}}
  const addEvidence=async(b:Booking)=>{const note=await operatorPrompt('Completion evidence note')??'';if(!note.trim())return;setBusy(b.id);setError('');try{await api(`/provider/services/bookings/${b.id}/completion-evidence`,{method:'POST',body:JSON.stringify({evidenceType:'NOTE',note:note.trim()})},session)}catch(e){setError(e instanceof Error?e.message:'Completion evidence could not be added')}finally{setBusy('')}}
  const loadAssignments=async(id:string)=>{setBusy(id);setError('');try{const rows=await api<Assignment[]>(`/provider/services/bookings/${id}/assignments`,{},session);setAssignments(x=>({...x,[id]:rows}))}catch(e){setError(e instanceof Error?e.message:'Assignments could not be loaded')}finally{setBusy('')}}
  const assign=async(bookingId:string,agentId:string)=>{if(!agentId)return;setBusy(bookingId);setError('');try{await api(`/provider/services/bookings/${bookingId}/assignments`,{method:'POST',body:JSON.stringify({agentId})},session);await loadAssignments(bookingId)}catch(e){setError(e instanceof Error?e.message:'Agent could not be assigned')}finally{setBusy('')}}
  const transition=async(bookingId:string,assignment:Assignment,status:string)=>{setBusy(assignment.id);setError('');try{await api(`/provider/services/assignments/${assignment.id}/status`,{method:'POST',body:JSON.stringify({status})},session);await loadAssignments(bookingId)}catch(e){setError(e instanceof Error?e.message:'Dispatch status could not be updated')}finally{setBusy('')}}
  return <section style={panel}><h2>Booking queue</h2><p style={muted}>New requests are shown first. Delivery details are immutable booking snapshots.</p>{error&&<div style={errorBox}>{error}</div>}<div style={stack}>{bookings.length===0?<p>No bookings yet.</p>:bookings.map(b=>{const rows=assignments[b.id];const active=rows?.find(a=>!['REJECTED','RELEASED'].includes(a.status));return <article key={b.id} style={card}><div style={{flex:1,minWidth:240}}><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><strong>{b.offeringName}</strong><span style={badge}>{b.status}</span></div><div>{new Date(b.scheduledFrom).toLocaleString('en-IN')} → {new Date(b.scheduledUntil).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</div><small>{money(b.servicePricePaise)} · {addressText(b.addressSnapshot)}</small>{b.notes&&<div style={{marginTop:6}}>Note: {b.notes}</div>}</div><div style={{display:'grid',gap:8,minWidth:210}}>{b.status==='REQUESTED'&&<><button style={primary} disabled={!!busy} onClick={()=>void respond(b,'ACCEPT')}>Accept</button><button style={button} disabled={!!busy} onClick={()=>void propose(b)}>Suggest another time</button><button style={button} disabled={!!busy} onClick={()=>void respond(b,'DECLINE')}>Decline</button></>}{b.status==='IN_PROGRESS'&&<button style={button} disabled={!!busy} onClick={()=>void addEvidence(b)}>Add completion note</button>}{['CONFIRMED','IN_PROGRESS'].includes(b.status)&&<>{!rows?<button style={button} disabled={!!busy} onClick={()=>void loadAssignments(b.id)}>Manage dispatch</button>:active?<><div><b>{active.agentDisplayName??'Assigned agent'}</b> · {active.status}</div>{active.status==='ASSIGNED'&&<button style={primary} onClick={()=>void transition(b.id,active,'ACCEPTED')}>Agent accepted</button>}{active.status==='ACCEPTED'&&<button style={primary} onClick={()=>void transition(b.id,active,'EN_ROUTE')}>Mark en route</button>}{active.status==='EN_ROUTE'&&<button style={primary} onClick={()=>void transition(b.id,active,'ARRIVED')}>Mark arrived</button>}{['ASSIGNED','ACCEPTED','EN_ROUTE','ARRIVED'].includes(active.status)&&<button style={button} onClick={()=>void transition(b.id,active,'RELEASED')}>Release assignment</button>}</>:<select style={input} defaultValue="" onChange={e=>void assign(b.id,e.target.value)}><option value="">Assign field agent…</option>{agents.filter(a=>a.active).map(a=><option key={a.id} value={a.id}>{a.displayName}</option>)}</select>}</>}</div></article>})}</div></section>
}

function Catalogue({session,offerings,reload}:{session:AuthSession;offerings:Offering[];reload:()=>Promise<void>}){
  const[categories,setCategories]=useState<Category[]>([]),[categoryId,setCategoryId]=useState(''),[name,setName]=useState(''),[description,setDescription]=useState(''),[price,setPrice]=useState('0'),[duration,setDuration]=useState('60'),[busy,setBusy]=useState(false),[error,setError]=useState('')
  useEffect(()=>{api<Category[]>('/provider/services/categories',{},session).then(rows=>{setCategories(rows);if(!categoryId&&rows[0])setCategoryId(rows[0].id)}).catch(e=>setError(e instanceof Error?e.message:'Categories could not be loaded'))},[session])
  const create=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await api('/provider/services/offerings',{method:'POST',body:JSON.stringify({categoryId,name:name.trim(),description:description.trim()||undefined,pricePaise:Math.round(Number(price)*100),durationMinutes:Number(duration),active:true})},session);setName('');setDescription('');setPrice('0');await reload()}catch(e){setError(e instanceof Error?e.message:'Offering could not be created')}finally{setBusy(false)}}
  const toggle=async(o:Offering)=>{setBusy(true);setError('');try{await api(`/provider/services/offerings/${o.id}`,{method:'PATCH',body:JSON.stringify({active:!o.active})},session);await reload()}catch(e){setError(e instanceof Error?e.message:'Offering could not be updated')}finally{setBusy(false)}}
  return <section style={panel}><h2>Service catalogue</h2><p style={muted}>Create and maintain your provider-owned offerings. Existing booking prices remain immutable snapshots.</p>{error&&<div style={errorBox}>{error}</div>}<form onSubmit={create} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10,alignItems:'end'}}><label>Category<select required style={input} value={categoryId} onChange={e=>setCategoryId(e.target.value)}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Name<input required style={input} value={name} onChange={e=>setName(e.target.value)}/></label><label>Price (₹)<input type="number" min="0" step="0.01" style={input} value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Duration (minutes)<input type="number" min="5" style={input} value={duration} onChange={e=>setDuration(e.target.value)}/></label><label style={{gridColumn:'1/-1'}}>Description<textarea style={{...input,minHeight:70}} value={description} onChange={e=>setDescription(e.target.value)}/></label><button style={primary} disabled={busy||!categoryId||!name.trim()}>Add offering</button></form><div style={{...stack,marginTop:18}}>{offerings.map(o=><article key={o.id} style={card}><div><strong>{o.name}</strong><div><small>{money(o.pricePaise)} · {o.durationMinutes??'-'} min · {o.active?'ACTIVE':'INACTIVE'}</small></div></div><button style={button} disabled={busy} onClick={()=>void toggle(o)}>{o.active?'Disable':'Enable'}</button></article>)}</div></section>
}

function Agents({session,agents,reload}:{session:AuthSession;agents:Agent[];reload:()=>Promise<void>}){
  const[name,setName]=useState(''),[phone,setPhone]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const create=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await api('/provider/services/agents',{method:'POST',body:JSON.stringify({displayName:name.trim(),phone:phone.trim()||undefined})},session);setName('');setPhone('');await reload()}catch(e){setError(e instanceof Error?e.message:'Agent could not be created')}finally{setBusy(false)}}
  const toggle=async(a:Agent)=>{setBusy(true);setError('');try{await api(`/provider/services/agents/${a.id}`,{method:'PATCH',body:JSON.stringify({active:!a.active})},session);await reload()}catch(e){setError(e instanceof Error?e.message:'Agent status could not be updated')}finally{setBusy(false)}}
  return <section style={panel}><h2>Field-agent roster</h2><p style={muted}>Agents are operational identities only; provider operator actions remain the authenticated audit source.</p>{error&&<div style={errorBox}>{error}</div>}<form onSubmit={create} style={{display:'flex',gap:8,flexWrap:'wrap',margin:'16px 0'}}><input style={input} placeholder="Agent name" value={name} onChange={e=>setName(e.target.value)} required/><input style={input} placeholder="Phone (optional)" value={phone} onChange={e=>setPhone(e.target.value)}/><button style={primary} disabled={busy}>Add agent</button></form><div style={stack}>{agents.map(a=><article key={a.id} style={card}><div><strong>{a.displayName}</strong><div><small>{a.phone??'No phone'} · {a.active?'ACTIVE':'INACTIVE'}</small></div></div><button style={button} disabled={busy} onClick={()=>void toggle(a)}>{a.active?'Deactivate':'Activate'}</button></article>)}</div></section>
}

function Coverage({session,areas,offerings}:{session:AuthSession;areas:Area[];offerings:Offering[]}){
  const[providerAreas,setProviderAreas]=useState(areas),[postal,setPostal]=useState(''),[offeringId,setOfferingId]=useState(offerings[0]?.id??''),[offeringAreas,setOfferingAreas]=useState<Area[]>([]),[offeringPostal,setOfferingPostal]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const loadOffering=useCallback(async(id:string)=>{if(!id){setOfferingAreas([]);return}try{setOfferingAreas(await api<Area[]>(`/provider/services/offerings/${id}/areas`,{},session))}catch(e){setError(e instanceof Error?e.message:'Offering coverage could not be loaded')}},[session])
  useEffect(()=>{if(offeringId)void loadOffering(offeringId)},[offeringId,loadOffering])
  const add=async(scope:'provider'|'offering')=>{const code=(scope==='provider'?postal:offeringPostal).trim();if(!/^[1-9][0-9]{5}$/.test(code)){setError('Enter a valid 6-digit Indian PIN code');return}setBusy(true);setError('');try{if(scope==='provider'){await api('/provider/services/areas',{method:'POST',body:JSON.stringify({postalCode:code})},session);setProviderAreas(await api('/provider/services/areas',{},session) as Area[]);setPostal('')}else{await api(`/provider/services/offerings/${offeringId}/areas`,{method:'POST',body:JSON.stringify({postalCode:code})},session);await loadOffering(offeringId);setOfferingPostal('')}}catch(e){setError(e instanceof Error?e.message:'Coverage could not be updated')}finally{setBusy(false)}}
  const toggle=async(scope:'provider'|'offering',area:Area)=>{setBusy(true);setError('');try{const path=scope==='provider'?`/provider/services/areas/${area.id}`:`/provider/services/offerings/${offeringId}/areas/${area.id}`;await api(path,{method:'PATCH',body:JSON.stringify({active:!area.active})},session);if(scope==='provider')setProviderAreas(await api('/provider/services/areas',{},session) as Area[]);else await loadOffering(offeringId)}catch(e){setError(e instanceof Error?e.message:'Coverage could not be updated')}finally{setBusy(false)}}
  return <section style={panel}><h2>Areas I serve</h2><p style={muted}>Provider-level PIN codes are the V1 serviceability authority. Offering-specific rows override provider coverage for that offering.</p>{error&&<div style={errorBox}>{error}</div>}<h3>Provider coverage</h3><div style={{display:'flex',gap:8,marginBottom:12}}><input style={input} placeholder="PIN code" value={postal} onChange={e=>setPostal(e.target.value.replace(/\D/g,'').slice(0,6))}/><button style={primary} disabled={busy} onClick={()=>void add('provider')}>Add</button></div><div style={chips}>{providerAreas.map(a=><button key={a.id} style={a.active?chip:chipOff} onClick={()=>void toggle('provider',a)}>{a.postalCode} {a.active?'✓':'off'}</button>)}</div><hr style={{margin:'24px 0',border:'none',borderTop:'1px solid #e2e8f0'}}/><h3>Offering-specific coverage</h3><select style={input} value={offeringId} onChange={e=>setOfferingId(e.target.value)}>{offerings.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><div style={{display:'flex',gap:8,margin:'12px 0'}}><input style={input} placeholder="PIN override" value={offeringPostal} onChange={e=>setOfferingPostal(e.target.value.replace(/\D/g,'').slice(0,6))}/><button style={primary} disabled={busy||!offeringId} onClick={()=>void add('offering')}>Add override</button></div><div style={chips}>{offeringAreas.map(a=><button key={a.id} style={a.active?chip:chipOff} onClick={()=>void toggle('offering',a)}>{a.postalCode} {a.active?'✓':'off'}</button>)}</div></section>
}

function Schedule({session,offerings}:{session:AuthSession;offerings:Offering[]}){
  const[offeringId,setOfferingId]=useState(offerings[0]?.id??''),[windows,setWindows]=useState<Window[]>([]),[exceptions,setExceptions]=useState<AvailabilityException[]>([]),[day,setDay]=useState(1),[start,setStart]=useState('09:00'),[end,setEnd]=useState('17:00'),[capacity,setCapacity]=useState(1),[exceptionDate,setExceptionDate]=useState(''),[exceptionClosed,setExceptionClosed]=useState(true),[exceptionCapacity,setExceptionCapacity]=useState('1'),[exceptionNote,setExceptionNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const load=useCallback(async(id:string)=>{if(!id){setWindows([]);setExceptions([]);return}try{const[w,x]=await Promise.all([api<Window[]>(`/provider/services/offerings/${id}/availability-windows`,{},session),api<AvailabilityException[]>(`/provider/services/offerings/${id}/availability-exceptions`,{},session)]);setWindows(w);setExceptions(x)}catch(e){setError(e instanceof Error?e.message:'Availability could not be loaded')}},[session])
  useEffect(()=>{if(offeringId)void load(offeringId)},[offeringId,load])
  const minute=(v:string)=>{const[h,m]=v.split(':').map(Number);return h*60+m}
  const create=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await api(`/provider/services/offerings/${offeringId}/availability-windows`,{method:'POST',body:JSON.stringify({dayOfWeek:day,startMinute:minute(start),endMinute:minute(end),slotCapacity:capacity,active:true})},session);await load(offeringId)}catch(e){setError(e instanceof Error?e.message:'Availability window could not be created')}finally{setBusy(false)}}
  const saveException=async()=>{if(!offeringId||!exceptionDate)return;setBusy(true);setError('');try{await api(`/provider/services/offerings/${offeringId}/availability-exceptions`,{method:'POST',body:JSON.stringify({serviceDate:`${exceptionDate}T00:00:00.000Z`,closed:exceptionClosed,slotCapacity:exceptionClosed?undefined:Number(exceptionCapacity),note:exceptionNote.trim()||undefined,active:true})},session);setExceptionNote('');await load(offeringId)}catch(e){setError(e instanceof Error?e.message:'Date exception could not be saved')}finally{setBusy(false)}}
  const toggle=async(w:Window)=>{setBusy(true);setError('');try{await api(`/provider/services/offerings/${offeringId}/availability-windows/${w.id}`,{method:'PATCH',body:JSON.stringify({active:!w.active})},session);await load(offeringId)}catch(e){setError(e instanceof Error?e.message:'Availability window could not be updated')}finally{setBusy(false)}}
  return <section style={panel}><h2>Weekly availability & capacity</h2><p style={muted}>These windows feed the same booking-capacity engine used by consumer availability checks.</p>{error&&<div style={errorBox}>{error}</div>}<select style={input} value={offeringId} onChange={e=>setOfferingId(e.target.value)}>{offerings.map(o=><option key={o.id} value={o.id}>{o.name} · {money(o.pricePaise)}</option>)}</select><form onSubmit={create} style={{display:'flex',gap:8,flexWrap:'wrap',alignItems:'end',margin:'16px 0'}}><label>Day<select style={input} value={day} onChange={e=>setDay(Number(e.target.value))}>{days.map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label><label>Start<input type="time" style={input} value={start} onChange={e=>setStart(e.target.value)}/></label><label>End<input type="time" style={input} value={end} onChange={e=>setEnd(e.target.value)}/></label><label>Capacity<input type="number" min={1} style={{...input,width:90}} value={capacity} onChange={e=>setCapacity(Number(e.target.value))}/></label><button style={primary} disabled={busy||!offeringId}>Add window</button></form><h3 style={{marginTop:24}}>Date-specific exceptions</h3><div style={{display:'flex',gap:8,flexWrap:'wrap',alignItems:'end'}}><label>Date<input type="date" style={input} value={exceptionDate} onChange={e=>setExceptionDate(e.target.value)}/></label><label>Mode<select style={input} value={exceptionClosed?'CLOSED':'CAPACITY'} onChange={e=>setExceptionClosed(e.target.value==='CLOSED')}><option value="CLOSED">Closed</option><option value="CAPACITY">Capacity override</option></select></label>{!exceptionClosed&&<label>Capacity<input type="number" min={1} style={{...input,width:100}} value={exceptionCapacity} onChange={e=>setExceptionCapacity(e.target.value)}/></label>}<label>Note<input style={input} value={exceptionNote} onChange={e=>setExceptionNote(e.target.value)}/></label><button type="button" style={button} disabled={busy||!exceptionDate} onClick={()=>void saveException()}>Save exception</button></div><div style={{...chips,margin:'12px 0 20px'}}>{exceptions.map(x=><span key={x.id} style={x.active?chip:chipOff}>{String(x.serviceDate).slice(0,10)} · {x.closed?'Closed':`Capacity ${x.slotCapacity??'-'}`}</span>)}</div><div style={stack}>{windows.map(w=><article key={w.id} style={card}><div><strong>{days[w.dayOfWeek]} · {time(w.startMinute)}–{time(w.endMinute)}</strong><div><small>Capacity {w.slotCapacity} · {w.active?'ACTIVE':'INACTIVE'}</small></div></div><button style={button} disabled={busy} onClick={()=>void toggle(w)}>{w.active?'Disable':'Enable'}</button></article>)}</div></section>
}

function Readiness({session}:{session:AuthSession}){
  const[data,setData]=useState<ProviderReadiness|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await api<ProviderReadiness>('/provider/services/readiness',{},session))}catch(e){setError(e instanceof Error?e.message:'Provider readiness could not be loaded')}finally{setLoading(false)}},[session])
  useEffect(()=>{void load()},[load])
  if(loading)return <section style={panel}>Loading readiness…</section>
  return <section style={panel}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'start',flexWrap:'wrap'}}><div><h2>Provider readiness</h2><p style={muted}>Repository readiness across catalogue, coverage, availability and field-agent capacity.</p></div><span style={{...badge,background:data?.ready?'#ecfdf5':'#fff7df',color:data?.ready?'#065f46':'#8a6100'}}>{data?.ready?'READY':'ACTION NEEDED'}</span></div>{error&&<div style={errorBox}>{error}</div>}<div style={{...metrics,marginTop:12}}>{data?.checks.map(c=><article key={c.key} style={metric}><strong>{c.ready?'✓':'!'}</strong><span>{c.key.replaceAll('_',' ')}</span><small>{c.count} configured</small></article>)}</div><div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:18}}><span style={chip}>{data?.pendingProposals??0} pending proposal(s)</span><span style={(data?.openDisputes??0)>0?{...chip,background:'#fff7df'}:chip}>{data?.openDisputes??0} open dispute(s)</span></div><button style={{...button,marginTop:16}} onClick={()=>void load()}>Refresh</button></section>
}

function Earnings({session}:{session:AuthSession}){
  const[summary,setSummary]=useState<SettlementSummary|null>(null),[batches,setBatches]=useState<SettlementBatch[]>([]),[recoveries,setRecoveries]=useState<SettlementRecovery[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');try{const[s,b,r]=await Promise.all([api<SettlementSummary>('/provider/services/settlements/summary',{},session),api<SettlementBatch[]>('/provider/services/settlements',{},session),api<SettlementRecovery[]>('/provider/services/settlements/recoveries',{},session)]);setSummary(s);setBatches(b);setRecoveries(r)}catch(e){setError(e instanceof Error?e.message:'Settlement data could not be loaded')}finally{setLoading(false)}},[session])
  useEffect(()=>{void load()},[load])
  if(loading)return <section style={panel}>Loading earnings & settlements…</section>
  return <section style={panel}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'start',flexWrap:'wrap'}}><div><h2>Earnings & settlements</h2><p style={muted}>Read-only settlement evidence. A “PAID” batch means platform finance recorded an external payment reference; Aaraagate does not initiate provider payouts from this screen.</p></div><button style={button} onClick={()=>void load()}>Refresh</button></div>{error&&<div style={errorBox}>{error}</div>}{summary&&<section style={metrics}><MoneyMetric label="Paid" value={summary.paidPaise}/><MoneyMetric label="Approved" value={summary.approvedPaise}/><MoneyMetric label="Draft" value={summary.draftPaise}/><MoneyMetric label="Open recoveries" value={summary.openRecoveryPaise} detail={`${summary.openRecoveryCount} recovery item(s)`}/></section>}<h3>Settlement batches</h3><div style={stack}>{batches.length===0?<p>No settlement batches yet.</p>:batches.map(b=><article key={b.id} style={card}><div><strong>{b.status} · {money(b.providerAmountPaise)}</strong><div><small>Gross {money(b.grossAmountPaise)} · platform fee {money(b.platformFeePaise)} · {b.entryCount} payment(s)</small></div><small>Created {new Date(b.createdAt).toLocaleString('en-IN')}{b.paymentReference?` · ref ${b.paymentReference}`:''}</small></div></article>)}</div><h3 style={{marginTop:24}}>Refund recoveries</h3><div style={stack}>{recoveries.length===0?<p>No provider recovery items.</p>:recoveries.map(r=><article key={r.id} style={card}><div><strong>{r.status} · {money(r.providerAmountPaise)}</strong><div><small>{r.offeringName??'Service booking'} · {r.reason}</small></div><small>Created {new Date(r.createdAt).toLocaleString('en-IN')}</small></div></article>)}</div></section>
}

function MoneyMetric({label,value,detail}:{label:string;value:number;detail?:string}){return <article style={metric}><strong style={{fontSize:24}}>{money(value)}</strong><span style={muted}>{label}</span>{detail&&<small>{detail}</small>}</article>}

function Metric({label,value}:{label:string;value:number}){return <article style={metric}><strong style={{fontSize:28}}>{value}</strong><span style={muted}>{label}</span></article>}

const center:React.CSSProperties={minHeight:'100vh',display:'grid',placeItems:'center'}
const login:React.CSSProperties={minHeight:'100vh',display:'grid',placeItems:'center',padding:20,background:'linear-gradient(135deg,#eef8f9,#f8fafc)'}
const loginCard:React.CSSProperties={width:'min(460px,100%)',background:'white',padding:28,borderRadius:20,boxShadow:'0 18px 50px rgba(15,23,42,.10)'}
const brand:React.CSSProperties={fontWeight:900,fontSize:24,letterSpacing:'-.03em',color:'#057f91'}
const muted:React.CSSProperties={color:'#64748b'}
const stack:React.CSSProperties={display:'grid',gap:12}
const input:React.CSSProperties={display:'block',width:'100%',boxSizing:'border-box',marginTop:5,padding:'10px 12px',border:'1px solid #cbd5e1',borderRadius:10,background:'white'}
const button:React.CSSProperties={padding:'9px 13px',border:'1px solid #cbd5e1',borderRadius:10,background:'white',fontWeight:700,cursor:'pointer'}
const primary:React.CSSProperties={...button,background:'#05879A',borderColor:'#05879A',color:'white'}
const choice:React.CSSProperties={...button,display:'flex',justifyContent:'space-between',textAlign:'left',padding:14}
const errorBox:React.CSSProperties={margin:'12px 0',padding:12,border:'1px solid #ef4444',borderRadius:10,background:'#fff7f7'}
const topbar:React.CSSProperties={display:'flex',alignItems:'center',justifyContent:'space-between',gap:16,padding:'14px 22px',background:'white',borderBottom:'1px solid #e2e8f0',position:'sticky',top:0,zIndex:5}
const metrics:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:12}
const metric:React.CSSProperties={display:'grid',gap:3,padding:16,background:'white',border:'1px solid #e2e8f0',borderRadius:14}
const tabs:React.CSSProperties={display:'flex',gap:8,overflowX:'auto',margin:'20px 0 14px'}
const tab:React.CSSProperties={...button,whiteSpace:'nowrap'}
const activeTab:React.CSSProperties={...primary,whiteSpace:'nowrap'}
const panel:React.CSSProperties={background:'white',border:'1px solid #e2e8f0',borderRadius:16,padding:20}
const card:React.CSSProperties={display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,border:'1px solid #e2e8f0',borderRadius:12,padding:14,flexWrap:'wrap'}
const badge:React.CSSProperties={fontSize:12,fontWeight:800,padding:'3px 7px',borderRadius:999,background:'#e8f6f7',color:'#046b78'}
const chips:React.CSSProperties={display:'flex',gap:8,flexWrap:'wrap'}
const chip:React.CSSProperties={...button,borderColor:'#8fd3da',background:'#edf9fa'}
const chipOff:React.CSSProperties={...button,opacity:.55}
