'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'

type Session={sessionId:string;accessToken:string;refreshToken:string;societyId:string;role:string;societyName:string}
type Summary={range:{from:string;to:string};access:{visitorRequests:number;visitorEntries:number;workforceEntries:number};maintenance:{billedCount:number;billedPaise:number|null;collectedCount:number;collectedPaise:number|null;outstandingCount:number;outstandingPaise:number|null};helpdesk:{open:number;inProgress:number;resolved:number;closed:number};audit:{eventCount:number}}
type UnitRef={number:string;building:{name:string}}
type AccessItem={id:string;subjectType:string;subjectName:string;purpose?:string|null;status:string;createdAt:string;enteredAt?:string|null;exitedAt?:string|null;unit:UnitRef}
type HelpdeskItem={id:string;title:string;category?:string|null;priority:string;status:string;createdAt:string;resolvedAt?:string|null;closedAt?:string|null;unit:UnitRef}
type MaintenanceItem={id:string;invoiceNumber:string;billingPeriod:string;amountPaise:number;dueDate:string;status:string;issuedAt:string;paidAt?:string|null;unit:UnitRef}
type AuditItem={id:string;event:string;occurredAt:string;actorUserId:string;gateId?:string|null;accessRequestId?:string|null;visitorPassId?:string|null}
type Feed<T>={page:number;pageSize:number;total:number;items:T[]}
type AuditFeed=Feed<AuditItem>

const base=(process.env.NEXT_PUBLIC_AARAGATE_API_BASE_URL??'http://localhost:3000').replace(/\/$/,'')
const auditRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','COMMITTEE_MEMBER'])
const financeRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','ACCOUNTANT'])

async function api<T>(path:string,session:Session):Promise<T>{
  const response=await fetch(`${base}/api/v1${path}`,{headers:{Accept:'application/json',Authorization:`Bearer ${session.accessToken}`}})
  const text=await response.text();const body=text?JSON.parse(text) as unknown:null
  if(!response.ok){const message=body&&typeof body==='object'&&'message'in body?String((body as {message:unknown}).message):`Request failed (${response.status})`;throw new Error(message)}
  return body as T
}

const currency=(paise:number|null)=>paise===null?'Restricted':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(paise/100)
const isoDay=(date:Date)=>date.toISOString().slice(0,10)
const location=(unit:UnitRef)=>`${unit.building.name} · ${unit.number}`

export default function ReportsPage(){
  const[session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[summary,setSummary]=useState<Summary|null>(null),[audit,setAudit]=useState<AuditFeed|null>(null),[page,setPage]=useState(1)
  const[visitors,setVisitors]=useState<Feed<AccessItem>|null>(null),[workforce,setWorkforce]=useState<Feed<AccessItem>|null>(null),[helpdesk,setHelpdesk]=useState<Feed<HelpdeskItem>|null>(null),[maintenance,setMaintenance]=useState<Feed<MaintenanceItem>|null>(null)
  const[to,setTo]=useState(()=>isoDay(new Date())),[from,setFrom]=useState(()=>isoDay(new Date(Date.now()-30*24*60*60*1000)))

  useEffect(()=>{try{const raw=sessionStorage.getItem('aaraagate.admin.session');if(!raw){setError('Sign in to the Admin console before opening reports.');setLoading(false);return}setSession(JSON.parse(raw) as Session)}catch{setError('Admin session could not be restored.');setLoading(false)}},[])
  const canAudit=useMemo(()=>!!session&&auditRoles.has(session.role),[session])
  const canFinance=useMemo(()=>!!session&&financeRoles.has(session.role),[session])
  const load=useCallback(async(currentPage=1)=>{if(!session)return;setLoading(true);setError('');try{const query=`from=${encodeURIComponent(`${from}T00:00:00.000Z`)}&to=${encodeURIComponent(`${to}T23:59:59.999Z`)}`;const [s,a,v,w,h,m]=await Promise.all([api<Summary>(`/reports/summary?${query}`,session),canAudit?api<AuditFeed>(`/reports/audit?page=${currentPage}&pageSize=25`,session):Promise.resolve(null),api<Feed<AccessItem>>(`/reports/access?subjectType=VISITOR&${query}&page=1&pageSize=10`,session),api<Feed<AccessItem>>(`/reports/access?subjectType=DOMESTIC_HELP&${query}&page=1&pageSize=10`,session),api<Feed<HelpdeskItem>>(`/reports/helpdesk?${query}&page=1&pageSize=10`,session),canFinance?api<Feed<MaintenanceItem>>(`/reports/maintenance?${query}&page=1&pageSize=10`,session):Promise.resolve(null)]);setSummary(s);setAudit(a);setVisitors(v);setWorkforce(w);setHelpdesk(h);setMaintenance(m);setPage(currentPage)}catch(e){setError(e instanceof Error?e.message:'Reports could not be loaded')}finally{setLoading(false)}},[session,from,to,canAudit,canFinance])
  useEffect(()=>{if(session)void load(1)},[session,load])

  if(!session&&!loading)return <main className="login"><section className="loginCard"><div className="brand">aaraagate</div><h1>Reports unavailable</h1><div className="error">{error}</div><a href="/">Return to Admin sign in</a></section></main>
  return <main className="content" style={{maxWidth:1200,margin:'0 auto',padding:'32px 24px'}}><header><small>{session?.societyName??'Society'} · {session?.role.replaceAll('_',' ')}</small><h1>Operational reports</h1><p>Society-scoped V1 summaries and privacy-safe operational drill-downs.</p><a href="/">← Back to operations</a></header><section className="panel form" style={{marginTop:20}}><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)} max={to}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)} min={from} max={isoDay(new Date())}/></label><button className="primary" disabled={loading} onClick={()=>void load(1)}>{loading?'Loading…':'Refresh report'}</button></section>{error&&<div className="error">{error}</div>}{summary&&<><div className="grid" style={{marginTop:20}}><Metric label="Visitor requests" value={summary.access.visitorRequests}/><Metric label="Visitor entries" value={summary.access.visitorEntries}/><Metric label="Domestic-help entries" value={summary.access.workforceEntries}/><Metric label="Audit events" value={summary.audit.eventCount}/></div><div className="relationshipGrid" style={{marginTop:20}}><section className="panel"><h2>Maintenance</h2><ReportRow label="Billed" value={`${summary.maintenance.billedCount} · ${currency(summary.maintenance.billedPaise)}`}/><ReportRow label="Collected" value={`${summary.maintenance.collectedCount} · ${currency(summary.maintenance.collectedPaise)}`}/><ReportRow label="Outstanding" value={`${summary.maintenance.outstandingCount} · ${currency(summary.maintenance.outstandingPaise)}`}/></section><section className="panel"><h2>Helpdesk</h2><ReportRow label="Open" value={String(summary.helpdesk.open)}/><ReportRow label="In progress" value={String(summary.helpdesk.inProgress)}/><ReportRow label="Resolved" value={String(summary.helpdesk.resolved)}/><ReportRow label="Closed" value={String(summary.helpdesk.closed)}/></section></div><p><small>Range: {new Date(summary.range.from).toLocaleDateString('en-IN')} – {new Date(summary.range.to).toLocaleDateString('en-IN')}</small></p></>}

  <section className="relationshipGrid" style={{marginTop:20}}><FeedPanel title="Visitor activity" total={visitors?.total??0} empty="No visitor activity in this range">{visitors?.items.map(item=><article className="relationshipCard" key={item.id}><div><b>{item.subjectName}</b><span>{location(item.unit)} · {item.status.replaceAll('_',' ')}</span><small>{new Date(item.createdAt).toLocaleString('en-IN')}{item.enteredAt?` · Entered ${new Date(item.enteredAt).toLocaleString('en-IN')}`:''}</small></div></article>)}</FeedPanel><FeedPanel title="Domestic-help activity" total={workforce?.total??0} empty="No workforce activity in this range">{workforce?.items.map(item=><article className="relationshipCard" key={item.id}><div><b>{item.subjectName}</b><span>{location(item.unit)} · {item.status.replaceAll('_',' ')}</span><small>{item.enteredAt?`Entered ${new Date(item.enteredAt).toLocaleString('en-IN')}`:new Date(item.createdAt).toLocaleString('en-IN')}{item.exitedAt?` · Exited ${new Date(item.exitedAt).toLocaleString('en-IN')}`:''}</small></div></article>)}</FeedPanel></section>

  <section className="relationshipGrid" style={{marginTop:20}}><FeedPanel title="Helpdesk tickets" total={helpdesk?.total??0} empty="No helpdesk tickets in this range">{helpdesk?.items.map(item=><article className="relationshipCard" key={item.id}><div><b>{item.title}</b><span>{location(item.unit)} · {item.priority} · {item.status.replaceAll('_',' ')}</span><small>{new Date(item.createdAt).toLocaleString('en-IN')}</small></div></article>)}</FeedPanel>{canFinance&&<FeedPanel title="Maintenance invoices" total={maintenance?.total??0} empty="No maintenance invoices in this range">{maintenance?.items.map(item=><article className="relationshipCard" key={item.id}><div><b>{item.invoiceNumber} · {currency(item.amountPaise)}</b><span>{location(item.unit)} · {item.billingPeriod} · {item.status}</span><small>Due {new Date(item.dueDate).toLocaleDateString('en-IN')}</small></div></article>)}</FeedPanel>}</section>

  {canAudit&&<section className="panel" style={{marginTop:20}}><div className="toolbar"><div><h2>Audit activity</h2><p>Identifiers only; no visitor credentials, phone numbers or payment payloads are exposed.</p></div>{audit&&<span>{audit.total} events</span>}</div>{audit?.items.length?audit.items.map(item=><article className="relationshipCard" key={item.id}><div><b>{item.event.replaceAll('_',' ')}</b><span>{new Date(item.occurredAt).toLocaleString('en-IN')} · Actor {item.actorUserId.slice(0,8)}…</span><small>{[item.gateId&&`Gate ${item.gateId.slice(0,8)}…`,item.accessRequestId&&`Access ${item.accessRequestId.slice(0,8)}…`,item.visitorPassId&&`Pass ${item.visitorPassId.slice(0,8)}…`].filter(Boolean).join(' · ')||'General audit event'}</small></div></article>):!loading&&<div className="empty">No audit events</div>}{audit&&<div className="buttons" style={{marginTop:16}}><button disabled={page<=1||loading} onClick={()=>void load(page-1)}>Previous</button><span>Page {page} of {Math.max(1,Math.ceil(audit.total/audit.pageSize))}</span><button disabled={page*audit.pageSize>=audit.total||loading} onClick={()=>void load(page+1)}>Next</button></div>}</section>}</main>
}

function Metric({label,value}:{label:string;value:number}){return <div className="metric"><span>{label}</span><b>{value}</b></div>}
function ReportRow({label,value}:{label:string;value:string}){return <div className="relationshipCard"><span>{label}</span><b>{value}</b></div>}
function FeedPanel({title,total,empty,children}:{title:string;total:number;empty:string;children:React.ReactNode}){return <section className="panel"><div className="toolbar"><h2>{title}</h2><span>{total} total</span></div>{total?children:<div className="empty">{empty}</div>}{total>10&&<p><small>Showing the latest 10. API drill-down is paginated for bounded operational access.</small></p>}</section>}
