'use client'

import { useEffect,useState } from 'react'
import { ActionBar, DangerButton, EmptyState, ErrorState, EvidenceGrid, PageHeader, PageShell, PrimaryButton, ReadinessPanel, SecondaryButton, StatusPill } from '../../../components/admin-ui'
import { api, type Session } from '../../../lib/admin-client'

type Metrics={activeAssets:number;activePlans:number;activeWorkOrders:number;overdueWorkOrders:number;openAlerts:number;criticalAlerts:number;contractsExpiring30d:number;continuity?:{status:'STABLE'|'WATCH'|'AT_RISK';blockers:string[];nextActions:string[];boundary:string}}
type Asset={id:string;code:string;name:string;category:string;location?:string|null;status:'ACTIVE'|'OUT_OF_SERVICE'|'RETIRED'}
type ReadinessItem={id:string;title:string;priority:string;status:string;dueAt?:string|null;assetCode?:string|null;assetName?:string|null;assetStatus?:string|null;assignedUserId?:string|null;assignedUserName?:string|null;evidenceCount:number;verifiedEvidenceCount:number;overdue:boolean;signals:string[];nextActions:string[]}
type Readiness={summary:{activeWorkOrders:number;criticalActive:number;overdue:number;unassigned:number;outOfServiceAssetWork:number};items:ReadinessItem[];boundary:string}
const readRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','FACILITY_MANAGER','COMMITTEE_MEMBER'])
const manageRoles=new Set(['SUPER_ADMIN','SOCIETY_ADMIN','FACILITY_MANAGER'])
function getSession():Session|null{try{const raw=sessionStorage.getItem('aaraagate.admin.session');return raw?JSON.parse(raw):null}catch{return null}}
export default function FacilitiesHealthPage(){
 const s=typeof window==='undefined'?null:getSession(),canRead=!!s&&readRoles.has(s.role),canManage=!!s&&manageRoles.has(s.role)
 const[metrics,setMetrics]=useState<Metrics|null>(null),[assets,setAssets]=useState<Asset[]>([]),[readiness,setReadiness]=useState<Readiness|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function load(){if(!s||!canRead)return;setBusy(true);setError('');try{const[m,a,r]=await Promise.all([api<Metrics>('/facilities/preventive-plans/metrics',{},s),api<Asset[]>('/facilities/assets',{},s),api<Readiness>('/facilities/readiness',{},s)]);setMetrics(m);setAssets(a);setReadiness(r)}catch(e){setError(e instanceof Error?e.message:'Could not load facilities health')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 async function setAssetStatus(id:string,status:Asset['status']){if(!s||!canManage)return;setBusy(true);setError('');try{await api(`/facilities/assets/${id}/status`,{method:'POST',body:JSON.stringify({status})},s);await load()}catch(e){setError(e instanceof Error?e.message:'Could not update asset status')}finally{setBusy(false)}}
 if(!s||!canRead)return <PageShell><PageHeader title="Facilities access required" actions={<a href="/">Return to Admin</a>}/></PageShell>
 const cards:[string,number,string][]=[['Active assets',metrics?.activeAssets??0,'Current common-area equipment in service'],['Preventive plans',metrics?.activePlans??0,'Enabled maintenance schedules'],['Active work orders',metrics?.activeWorkOrders??0,'Open or in progress'],['Overdue work orders',metrics?.overdueWorkOrders??0,'Past due and still active'],['Open alerts',metrics?.openAlerts??0,'Operational alerts needing attention'],['Critical alerts',metrics?.criticalAlerts??0,'Highest priority facilities alerts'],['Contracts ≤30 days',metrics?.contractsExpiring30d??0,'AMC/warranty/service contracts nearing expiry']]
 return <PageShell><PageHeader context={`${s.societyName??'Current society'} · ${s.role.replaceAll('_',' ')}`} title="Facilities health" description="Operational health, maintenance risk and asset service state for common-area facilities." actions={<div style={links}><a href="/facilities">Facilities ops</a><a href="/facilities/preventive">Preventive maintenance</a><a href="/facilities/alerts">Alerts</a><a href="/facilities/contracts">AMC & evidence</a></div>}/>{error&&<ErrorState title="Facilities health unavailable" description={error}/>}<ActionBar label="Facilities health actions"><SecondaryButton loading={busy} onClick={()=>void load()}>Refresh health</SecondaryButton></ActionBar><section style={panel}><h2>Facilities metrics</h2><EvidenceGrid items={cards.map(([label,value,description])=>({id:label,label,value:<><strong>{value}</strong><div>{description}</div></>}))}/></section>{metrics?.continuity&&<ReadinessPanel title="Service continuity posture" state="ready" status={{label:metrics.continuity.status.replaceAll('_',' '),tone:metrics.continuity.status==='STABLE'?'success':metrics.continuity.status==='AT_RISK'?'warning':'info'}} boundary={metrics.continuity.boundary} checks={<><EvidenceGrid items={[
  {id:'critical-alerts',label:'Critical alerts',value:metrics.criticalAlerts},
  {id:'overdue-work',label:'Overdue work orders',value:metrics.overdueWorkOrders},
  {id:'contract-expiry',label:'Contracts ≤30 days',value:metrics.contractsExpiring30d},
]}/>{metrics.continuity.nextActions.length>0&&<ul>{metrics.continuity.nextActions.map(action=><li key={action}>{action}</li>)}</ul>}</>}/>}<ReadinessPanel title="Priority work readiness" state={readiness?'ready':'loading'} status={{label:readiness&&readiness.summary.criticalActive===0&&readiness.summary.overdue===0?'STABLE':'ACTION REQUIRED',tone:readiness&&readiness.summary.criticalActive===0&&readiness.summary.overdue===0?'success':'warning'}} boundary={readiness?.boundary} checks={readiness?<><EvidenceGrid items={[{id:'critical-active',label:'Critical active',value:readiness.summary.criticalActive},{id:'overdue',label:'Overdue',value:readiness.summary.overdue},{id:'unassigned',label:'Unassigned',value:readiness.summary.unassigned},{id:'asset-state-risk',label:'Asset-state risk',value:readiness.summary.outOfServiceAssetWork}]}/><div style={readinessList}>{readiness.items.length===0?<EmptyState title="No active work orders require readiness review"/>:readiness.items.slice(0,12).map(item=><article key={item.id} style={readinessItem}><div style={badgeRow}><strong>{item.priority} · {item.title}</strong><StatusPill label={item.status.replaceAll('_',' ')} tone={item.status==='COMPLETED'?'success':'info'}/>{item.signals.map(signal=><StatusPill key={signal} label={signal.replaceAll('_',' ')} tone="warning"/>)}</div><p><small>{item.assetCode?item.assetCode+' · '+(item.assetName??'')+' · ':''}Assignee {item.assignedUserName??'Unassigned'} · Due {item.dueAt?new Date(item.dueAt).toLocaleString('en-IN'):'—'}</small></p><p><small>Evidence {item.verifiedEvidenceCount}/{item.evidenceCount} verified</small></p>{item.nextActions.length>0&&<ul>{item.nextActions.map(action=><li key={action}>{action}</li>)}</ul>}</article>)}</div></>:undefined}/><section style={panel}><h2>Asset lifecycle</h2><p>Move equipment out of service for maintenance or retire it permanently.</p>{assets.length===0?<EmptyState title="No facility assets"/>:assets.map(a=><div key={a.id} style={item}><span><b>{a.code} · {a.name}</b><br/><small>{a.category}{a.location?` · ${a.location}`:''}</small><br/><StatusPill label={a.status.replaceAll('_',' ')} tone={a.status==='ACTIVE'?'success':a.status==='RETIRED'?'danger':'warning'}/></span>{canManage&&<span style={actions}>{a.status==='ACTIVE'&&<SecondaryButton disabled={busy} onClick={()=>void setAssetStatus(a.id,'OUT_OF_SERVICE')}>Mark out of service</SecondaryButton>}{a.status==='OUT_OF_SERVICE'&&<PrimaryButton disabled={busy} onClick={()=>void setAssetStatus(a.id,'ACTIVE')}>Return to service</PrimaryButton>}{a.status!=='RETIRED'&&<DangerButton disabled={busy} onClick={()=>void setAssetStatus(a.id,'RETIRED')}>Retire</DangerButton>}</span>}</div>)}</section></PageShell>
}
const panel={background:'#fff',border:'1px solid #e5e7eb',borderRadius:18,padding:20,boxShadow:'0 8px 24px rgba(15,23,42,.05)'}
const item={display:'flex',alignItems:'center',justifyContent:'space-between',gap:16,padding:'14px 0',borderBottom:'1px solid #eef2f7'}
const actions={display:'flex',gap:8,flexWrap:'wrap' as const,justifyContent:'flex-end'}
const links={display:'flex',gap:14,flexWrap:'wrap' as const}
const readinessItem={display:'flex',gap:12,padding:'14px 0',borderBottom:'1px solid #eef2f7',alignItems:'flex-start'}

const readinessList:React.CSSProperties={display:'grid',gap:12,marginTop:16}
const badgeRow:React.CSSProperties={display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}
